Fix ./mk* for autoconf 2.60 (fakeroot ./configure caused problems)
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@286 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mkmake b/mkmake
--- a/mkmake
+++ b/mkmake
@@ -1,20 +1,28 @@
 #! /bin/bash
 
 usage() {
-	echo "Usage: mkmake [-q] args-for-make"
+	echo "Usage: ./${0##*/} [options] args-for-make
+Available options are
+  -q  quiet
+  -n  Stop after ./configure, i.e. do not run make"
 }
 
 die() {
-	echo $1
+	echo "$1"
 	exit ${2:-1}
 }
 
 QUIET=''
-if [[ "$1" = '-q' ]]; then
-  QUIET='&>/dev/null'
-  shift
-fi
-MAKEEXEC="$(type -P make)" || die "cannot find make"
+EARLYSTOP=''
+while getopts 'qn?hH' OPTION; do
+case "$OPTION" in
+  q) QUIET='&>/dev/null';;
+  n) EARLYSTOP=1;;
+  *) Usage;;
+esac
+done
+shift $((OPTIND-1))
+
 if ! [[ -e Makefile ]]; then
 	if ! [[ -e configure && -e Makefile.in ]]; then
 		echo "Running autotools..."
@@ -23,7 +31,9 @@ if ! [[ -e Makefile ]]; then
 	echo "Running configure..."
 	eval ./configure $QUIET || die "configure failed"
 fi
+[[ "$EARLYSTOP" ]] && exit 0
 echo "Making $@..."
+MAKEEXEC="$(type -P make)" || die "cannot find make"
 if [[ "$QUIET" ]]; then
 	exec "$MAKEEXEC" "$@" &>/dev/null
 else
diff --git a/mktarball b/mktarball
--- a/mktarball
+++ b/mktarball
@@ -5,7 +5,7 @@ usage() {
 }
 
 die() {
-	echo $1
+	echo "$1"
 	exit ${2:-1}
 }
 
@@ -14,6 +14,7 @@ pushd build/ &>/dev/null || die "pushd build failed"
 popd &>/dev/null || die "popd failed"
 
 if FAKEROOT="$(type -P fakeroot)"; then
+	./mkmake -qn || die "mkmake -qn failed"
 	"$FAKEROOT" ./mkmake -q dist || die "mkmake dist failed"
 else
 	./mkmake -q dist || die "mkmake dist failed"
