Add optimistic infrastructure for portage-2.1.2 cache support.
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@324 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mkmake b/mkmake
--- a/mkmake
+++ b/mkmake
@@ -6,6 +6,7 @@ Available options are
   -q  quiet
   -n  Stop after ./configure, i.e. do not run make
   -e  Keep environment - do not modify LDFLAGS, CXXFLAGS, CFLAGS
+  -S  No sqlite
   -c  Use only debugging-safe CXXFLAGS"
 	exit ${1}
 }
@@ -19,11 +20,13 @@ QUIET=''
 EARLYSTOP=''
 KEEPENV=''
 SAVEFLAGS=''
-while getopts 'qnec?hH' OPTION; do
+SQLITE='--with-sqlite'
+while getopts 'qSnec?hH' OPTION; do
 case "$OPTION" in
 	q) QUIET='&>/dev/null';;
 	n) EARLYSTOP=1;;
 	e) KEEPENV='';;
+	S) SQLITE='--without-sqlite';;
 	c) SAFEFLAGS=1;;
 	*) Usage 1;;
 esac
@@ -46,7 +49,7 @@ if ! [[ -e Makefile ]]; then
 		eval ./autogen.sh $QUIET || die "autogen failed"
 	fi
 	echo "Running configure..."
-	eval ./configure --with-sqlite $QUIET || die "configure failed"
+	eval ./configure $SQLITE $QUIET || die "configure failed"
 fi
 [[ "$EARLYSTOP" ]] && exit 0
 echo "Making $@..."
