Make ./mk* scripts more compatible. Thanks to Arfrever Frehtes Taifersar Arahesis <arfrever.fta@gmail.com>
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@456 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mkmake b/mkmake
--- a/mkmake
+++ b/mkmake
@@ -1,4 +1,6 @@
-#! /bin/bash
+#! /bin/sh
+
+export LC_ALL=C
 
 Usage() {
 	echo "Usage: ./${0##*/} [options] args-for-make
@@ -22,41 +24,41 @@ die() {
 }
 
 QUIET=''
-EARLYSTOP=''
-KEEPENV=''
-SAVEFLAGS=''
-NOT_FULL_USE=''
+EARLYSTOP=false
+KEEPENV=false
+SAFEFLAGS=false
+NOT_FULL_USE=false
 SQLITE=''
 BZLIB=''
-PEDANTIC=''
+PEDANTIC=false
 while getopts 'qnepusSbBc?hH' OPTION; do
 case "$OPTION" in
-	q) QUIET='&>/dev/null';;
-	n) EARLYSTOP=1;;
-	e) KEEPENV=1;;
-	p) PEDANTIC=1;;
-	u) NOT_FULL_USE=1;;
+	q) QUIET='>/dev/null 2>&1';;
+	n) EARLYSTOP=true;;
+	e) KEEPENV=true;;
+	p) PEDANTIC=true;;
+	u) NOT_FULL_USE=true;;
 	s) SQLITE='--with-sqlite';;
 	S) SQLITE='--without-sqlite';;
 	b) BZLIB='--with-bzip2';;
 	B) BZLIB='--without-bzip2';;
-	c) SAFEFLAGS=1;;
+	c) SAFEFLAGS=true;;
 	*) Usage 1;;
 esac
 done
-shift $((OPTIND-1))
+shift $(( $OPTIND - 1 ))
 
-if [ -z "${KEEPENV}" ]; then
+if ${KEEPENV}; then
 	MARCH=$(sed -n 's/^CFLAGS *= *.*-march=\([^ \"]*\)[ \"].*/\1/p' \
 		/etc/make.conf)
 	export CXXFLAGS CFLAGS LDFLAGS
 	LDFLAGS='-Wl,--sort-common -Wl,-O1 -Wl,-z,combreloc -Wl,--relax -Wl,-z,now'
 	CFLAGS="-march=${MARCH} -O2 -pipe"
-	[ -n "${SAFEFLAGS}" ] || CFLAGS="${CFLAGS} -fomit-frame-pointer -O3 -O4 -fno-ident -fPIC -ftracer -ftree-vectorize -ftree-vectorizer-verbose=0 -funswitch-loops -frename-registers -fweb -finline-functions -fgcse-after-reload -DNDEBUG -DG_DISABLE_ASSERT -DNO_DEBUG -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE"
-	[ -n "${NOT_FULL_USE}" ] && CFLAGS="${CFLAGS} -DNOT_FULL_USE"
+	${SAFEFLAGS} || CFLAGS="${CFLAGS} -fomit-frame-pointer -O3 -O4 -fno-ident -fPIC -ftracer -ftree-vectorize -ftree-vectorizer-verbose=0 -funswitch-loops -frename-registers -fweb -finline-functions -fgcse-after-reload -DNDEBUG -DG_DISABLE_ASSERT -DNO_DEBUG -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE"
+	${NOT_FULL_USE} && CFLAGS="${CFLAGS} -DNOT_FULL_USE"
 	CFLAGS="${CFLAGS} -g -ggdb3 -Wall -Wextra"
-	[ -n "${SAFEFLAGS}" ] || CFLAGS="${CFLAGS} -pedantic -Wno-variadic-macros"
-	if [ -n "${PEDANTIC}" ]; then
+	${SAFEFLAGS} || CFLAGS="${CFLAGS} -pedantic -Wno-variadic-macros"
+	if ${PEDANTIC}; then
 		CFLAGS="${CFLAGS} -fstrict-aliasing -fstack-protector"
 		CFLAGS="${CFLAGS} -Wformat=2 -Winit-self -Wmissing-include-dirs -Wswitch-default -Wunused -Wunused-parameter -Wstrict-aliasing=2"
 		CFLAGS="${CFLAGS} -Wfloat-equal  -Wundef -Wshadow -Wunsafe-loop-optimizations -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wsign-compare -Wmissing-field-initializers -Wmissing-noreturn -Wnormalized=nfkc -Wpacked -Wredundant-decls -Winvalid-pch -Wlong-long -Wvolatile-register-var -Wdisabled-optimization -Wstack-protector"
@@ -69,24 +71,24 @@ if [ -z "${KEEPENV}" ]; then
 	else
 		CXXFLAGS="${CFLAGS} -Werror"
 	fi
-	[ -n "${SAFEFLAGS}" ] || CXXFLAGS="${CXXFLAGS} -fvisibility-inlines-hidden -fno-enforce-eh-specs"
+	${SAFEFLAGS} || CXXFLAGS="${CXXFLAGS} -fvisibility-inlines-hidden -fno-enforce-eh-specs"
 fi
 [ -n "$QUIET" ] || echo "CFLAGS=$CFLAGS
 CXXFLAGS=$CXXFLAGS
 LDFLAGS=$LDFLAGS"
-if ! [ -e Makefile ]; then
-	if ! [ -e configure -a -e Makefile.in ]; then
+if ! test -e Makefile; then
+	if ! test -e configure || ! test -e Makefile.in; then
 		echo "Running autotools..."
 		eval ./autogen.sh $QUIET || die "autogen failed"
 	fi
 	echo "Running configure..."
 	eval ./configure $SQLITE $BZLIB $QUIET || die "configure failed"
 fi
-[ -n "$EARLYSTOP" ] && exec make config.h
+$EARLYSTOP && exec make config.h
 echo "Making $@..."
-MAKEEXEC="$(type -P make)" || die "cannot find make"
+type make >/dev/null 2>&1 || die "cannot find make"
 if [ -n "$QUIET" ]; then
-	exec "$MAKEEXEC" "$@" &>/dev/null
+	exec make "$@" >/dev/null 2>&1
 else
-	exec "$MAKEEXEC" "$@"
+	exec make "$@"
 fi
diff --git a/mkrelease b/mkrelease
--- a/mkrelease
+++ b/mkrelease
@@ -1,4 +1,6 @@
-#!/bin/bash
+#!/bin/sh
+
+export LC_ALL=C
 
 proj="eix"
 svnroot="https://svn.gentooexperimental.org/${proj}"
@@ -31,4 +33,4 @@ done
 echo "Creating release tag... "
 
 svn copy ${svnroot}/trunk ${svnroot}/tags/release-${ver} \
-	-m "Tagging the ${ver} release of the ${proj} project" &>/dev/null || die "svn copy failed"
+	-m "Tagging the ${ver} release of the ${proj} project" >/dev/null || die "svn copy failed"
diff --git a/mktarball b/mktarball
--- a/mktarball
+++ b/mktarball
@@ -1,4 +1,6 @@
-#! /bin/bash
+#! /bin/sh
+
+export LC_ALL=C
 
 usage() {
 	echo "Usage: mktarball"
@@ -9,14 +11,13 @@ die() {
 	exit ${2:-1}
 }
 
-mkdir build &>/dev/null
-pushd build/ &>/dev/null || die "pushd build failed"
-popd &>/dev/null || die "popd failed"
+test -d build || mkdir build >/dev/null
+test -d build || die "cannot create directory build"
 
 unset LDFLAGS CFLAGS CXXFLAGS
-if FAKEROOT="$(type -P fakeroot)"; then
+if type fakeroot >/dev/null 2>&1; then
 	./mkmake -eqn || die "mkmake -qn failed"
-	"$FAKEROOT" ./mkmake -q dist || die "mkmake dist failed"
+	fakeroot ./mkmake -q dist || die "mkmake dist failed"
 else
 	./mkmake -eq dist || die "mkmake dist failed"
 fi
