Fix [ quoting in update-eix-remote. Code cleanup. metabuilds: Use proper default CFLAGS.
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@314 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mkmake b/mkmake
--- a/mkmake
+++ b/mkmake
@@ -4,7 +4,9 @@ usage() {
 	echo "Usage: ./${0##*/} [options] args-for-make
 Available options are
   -q  quiet
-  -n  Stop after ./configure, i.e. do not run make"
+  -n  Stop after ./configure, i.e. do not run make
+  -e  Keep environment - do not modify LDFLAGS, CXXFLAGS, CFLAGS
+  -c  Use only debugging-safe CXXFLAGS"
 }
 
 die() {
@@ -14,22 +16,36 @@ die() {
 
 QUIET=''
 EARLYSTOP=''
+KEEPENV=''
+SAVEFLAGS=''
 while getopts 'qn?hH' OPTION; do
 case "$OPTION" in
-  q) QUIET='&>/dev/null';;
-  n) EARLYSTOP=1;;
-  *) Usage;;
+	q) QUIET='&>/dev/null';;
+	n) EARLYSTOP=1;;
+	e) KEEPENV='';;
+	c) SAFEFLAGS=1;;
+	*) Usage;;
 esac
 done
 shift $((OPTIND-1))
 
+if [[ -z "${KEEPENV}" ]]; then
+	MARCH=$(sed -n 's/^CFLAGS *= *.*-march=\([^ \"]*\)[ \"].*/\1/p' \
+		/etc/make.conf)
+	export LDFLAGS='-Wl,--sort-common -Wl,-O1 -Wl,-z,combreloc -Wl,--relax -Wl,-z,now'
+	export CFLAGS="-march=${MARCH} -O2 -pipe"
+	CFLAGS="${CFLAGS} -g -ggdb3 -Wall -Werror"
+	[[ "${SAFEFLAGS}" ]] || CFLAGS="${CFLAGS} -fomit-frame-pointer -O3 -O4 -fno-ident -fPIC -ftracer -ftree-vectorize -ftree-vectorizer-verbose=0 -funswitch-loops -frename-registers -fweb -finline-functions -fgcse-after-reload -DNDEBUG -DG_DISABLE_ASSERT -DNO_DEBUG -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE"
+	export CXXFLAGS="${CFLAGS}"
+	[[ "${SAFEFLAGS}" ]] || CXXFLAGS="${CXXFLAGS} -fvisibility-inlines-hidden -fno-enforce-eh-specs"
+fi
 if ! [[ -e Makefile ]]; then
 	if ! [[ -e configure && -e Makefile.in ]]; then
 		echo "Running autotools..."
 		eval ./autogen.sh $QUIET || die "autogen failed"
 	fi
 	echo "Running configure..."
-	eval ./configure $QUIET || die "configure failed"
+	eval ./configure --with-sqlite $QUIET || die "configure failed"
 fi
 [[ "$EARLYSTOP" ]] && exit 0
 echo "Making $@..."
diff --git a/mktarball b/mktarball
--- a/mktarball
+++ b/mktarball
@@ -13,11 +13,12 @@ mkdir build &>/dev/null
 pushd build/ &>/dev/null || die "pushd build failed"
 popd &>/dev/null || die "popd failed"
 
+unset LDFLAGS CFLAGS CXXFLAGS
 if FAKEROOT="$(type -P fakeroot)"; then
-	./mkmake -qn || die "mkmake -qn failed"
+	./mkmake -eqn || die "mkmake -qn failed"
 	"$FAKEROOT" ./mkmake -q dist || die "mkmake dist failed"
 else
-	./mkmake -q dist || die "mkmake dist failed"
+	./mkmake -eq dist || die "mkmake dist failed"
 fi
 
 for i in *.tar*; do
