Install dummy /etc/eixrc to avoid http://bugs.gentoo.org/show_bug.cgi?id=211192 Better honour SYSCONFDIR. Let autoconf try to define uint*_t
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@564 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mkmake b/mkmake
--- a/mkmake
+++ b/mkmake
@@ -85,11 +85,12 @@ if ! test -e Makefile; then
 		eval ./autogen.sh ${QUIET} || die "autogen failed"
 	fi
 	echo "Running configure..."
-	eval ./configure ${SQLITE} ${BZLIB} ${QUIET} || die "configure failed"
+	eval ./configure '--prefix=' ${SQLITE} ${BZLIB} ${QUIET} || \
+		die "configure failed"
 fi
 ${EARLYSTOP} && exec make config.h
 echo "Making ${*}..."
-type make >/dev/null 2>&1 || die "cannot find make"
+command -v make >/dev/null 2>&1 || die "cannot find make"
 if [ -n "${QUIET}" ]; then
 	exec make "${@}" >/dev/null 2>&1
 else
