Push previous script changes and make more trivial script changes.
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@1010 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mkmake b/mkmake
--- a/mkmake
+++ b/mkmake
@@ -1,9 +1,10 @@
 #! /usr/bin/env sh
 
-export LC_ALL=C
+export LC_ALL
+LC_ALL=C
 
 Usage () {
-	printf "%s\n" "Usage: ${0##*/} [options] args-for-make
+	printf '%s\n' "Usage: ${0##*/} [options] args-for-make
 Available options are
   -q  quiet
   -n  Stop after ./configure, i.e. do not run make
@@ -29,11 +30,11 @@ Available options are
 
 Info () {
 	${quiet} && return
-	printf "%s\n" "${*}"
+	printf '%s\n' "${*}"
 }
 
 Die () {
-	printf "%s: %s\n" "${0##*/}" "${1}"
+	printf '%s: %s\n' "${0##*/}" "${1}"
 	exit ${2:-1}
 }
 
@@ -45,15 +46,13 @@ SetCcache () {
 		"${i}:"*|*":${i}:"*) return;;
 	esac
 	if [ -n "${PATH}" ]
-	then
-		Info "PATH=${i}:\${PATH}"
+	then	Info "PATH=${i}:\${PATH}"
 		PATH="${i}:${PATH}"
 		export PATH
 	fi
 	[ -n "${CCACHE_DIR}" ] && return
 	for i in "${HOME}/.ccache" ../ccache ../../ccache
-	do
-		[ -z "${i}" ] && continue
+	do	[ -z "${i}" ] && continue
 		j=`readlink -f -- "${i}"` && [ -n "${j}" ] \
 			&& test -d "${j}" && break
 	done
@@ -68,45 +67,43 @@ earlystop=false
 keepenv=false
 not_full_use=false
 pedantic=false
-extra_cache=true
-separate_all=true
+extra_cache=:
+separate_all=:
 use_chown=false
 jarg='-j3'
-use_ccache=true
-configure_extra='--prefix=""'
-optimization=true
-quickcheck=true
+use_ccache=:
+configure_extra='--prefix=/usr'
+optimization=:
+quickcheck=:
 OPTIND=1
 while getopts 'qE01234nepusSbBrOQCc:j:?hH' opt
-do
-case "${opt}" in
-	q) quiet=true;;
+do	case "${opt}" in
+	q) quiet=:;;
 	E) extra_cache=false;;
 	0) separate_all=false;;
 	1) configure_extra="${configure_extra} --disable-separate-binaries";;
 	2) configure_extra="${configure_extra} --enable-separate-update";;
 	3) configure_extra="${configure_extra} --enable-separate-binaries";;
 	4) configure_extra="${configure_extra} --enable-separate-tools";;
-	n) earlystop=true;;
-	e) keepenv=true;;
-	p) pedantic=true;;
-	u) not_full_use=true;;
+	n) earlystop=:;;
+	e) keepenv=:;;
+	p) pedantic=:;;
+	u) not_full_use=:;;
 	s) configure_extra="${configure_extra} --with-sqlite";;
 	S) configure_extra="${configure_extra} --without-sqlite";;
 	b) configure_extra="${configure_extra} --with-bzip2";;
 	B) configure_extra="${configure_extra} --without-bzip2";;
-	r) use_chown=true;;
+	r) use_chown=:;;
 	O) optimization=false;;
 	Q) quickcheck=false;;
 	C) use_ccache=false;;
 	c) configure_extra="${configure_extra} ${OPTARG}";;
 	j) [ -n "${OPTARG}" ] && jarg='-j${OPTARG}' || jarg='';;
 	*) Usage 0;;
-esac
+	esac
 done
 if [ ${OPTIND} -gt 1 ]
-then
-	( eval '[ "$(( 0 + 1 ))" = 1 ]' ) >/dev/null 2>&1 &&
+then	( eval '[ "$(( 0 + 1 ))" = 1 ]' ) >/dev/null 2>&1 && \
 	eval 'shift "$(( ${OPTIND} - 1 ))"' || shift "`expr ${OPTIND} - 1`"
 fi
 
@@ -118,8 +115,7 @@ ${optimization} && configure_extra="${configure_extra} --enable-strong-optimizat
 ${quiet} && quietredirect='>/dev/null 2>&1' || quietredirect=''
 
 if ${use_chown}
-then
-	ls /root >/dev/null 2>&1 && \
+then	ls /root >/dev/null 2>&1 && \
 		Die "You should not really be root when you use -r" 2
 	chown -R root:root .
 fi
@@ -127,8 +123,7 @@ fi
 ${use_ccache} && SetCcache
 
 if ! ${keepenv}
-then
-	march="`sed -n 's/^CFLAGS *= *.*-march=\([^ \"]*\)[ \"].*/\1/p' \
+then	march="`sed -n 's/^CFLAGS *= *.*-march=\([^ \"]*\)[ \"].*/\1/p' \
 		/etc/make.conf`"
 	export CXXFLAGS LDFLAGS
 	CFLAGS="-march=${march} -O2 -pipe"
@@ -145,24 +140,21 @@ fi
 Info "CXXFLAGS=${CXXFLAGS}
 LDFLAGS=${LDFLAGS}"
 if ! test -e Makefile
-then
-	if ! test -e configure || ! test -e Makefile.in
-	then
-		echo "Running autotools..."
+then	if ! test -e configure || ! test -e Makefile.in
+	then	Info "Running autotools..."
 		eval ./autogen.sh ${quietredirect} || Die "autogen failed"
 	fi
-	echo "Running configure" ${configure_extra}
+	Info "Running configure" ${configure_extra}
 	eval ./configure ${configure_extra} ${quietredirect} || \
 		Die "configure failed"
 fi
 ${earlystop} && {
-	exec make ${jarg} config.h || Die "cannot exec make"
+	exec make ${jarg} config.h
+	Die "cannot exec make"
 }
-echo "Making ${*}..."
+Info "Making ${*}..."
 command -v make >/dev/null 2>&1 || Die "cannot find make"
 if ${quiet}
-then
-	exec make ${jarg} "${@}" >/dev/null 2>&1
-else
-	exec make ${jarg} "${@}"
+then	exec make ${jarg} "${@}" >/dev/null 2>&1
+else	exec make ${jarg} "${@}"
 fi
diff --git a/src/eix-functions.sh.in b/src/eix-functions.sh.in
--- a/src/eix-functions.sh.in
+++ b/src/eix-functions.sh.in
@@ -10,21 +10,27 @@
 # It contains helper functions for eix-remote, eix-layman,
 # and perhaps similar local scripts. (@PACKAGE_STRING@).
 
-local_eprefix_portage_exec="`eix-update --print EPREFIX_PORTAGE_EXEC`"
-
 # This must happen in a function to enforce an empty argument list.
 ReadFunctions () {
 	local i
 	ReadGettext
+	[ "${local_eprefix_portage_exec-unset}" = 'unset' ] &&
+		ReadVar local_eprefix_portage_exec EPREFIX_PORTAGE_EXEC
 	for i in "${local_eprefix_portage_exec}/etc/init.d/functions.sh" \
 		"${local_eprefix_portage_exec}/sbin/functions.sh"
-	do
-		test -r "${i}" || continue
+	do	test -r "${i}" || continue
 		. "${i}"
 		return
 	done
 	printf '%s: %s' "${0##*/}" "`gettext 'cannot read functions.sh'`" >&2
 	exit 2
+}
+
+: ${read_var_prg:=eix-update}
+ReadVar () {
+	local ReadVar_
+	ReadVar_=`PRINT_APPEND='X' "${3:-${read_var_prg}}" --print "${2}"`
+	eval "${1}=\"\${ReadVar_%X}\" && [ \"\${1}\" != \"\${ReadVar_}\" ]"
 }
 
 die () {
@@ -37,15 +43,12 @@ PerLine () {
 	local i
 	while IFS='
 ' read i
-	do
-		"${@}" "${i}"
+	do	"${@}" "${i}"
 	done
 }
 
-local_portdir=''
 GetPortdir () {
-	[ -n "${local_portdir}" ] && return
-	local_portdir="`eix-update --print PORTDIR`"
+	[ -n "${local_portdir}" ] || ReadVar local_portdir PORTDIR
 }
 
 verbose=:
@@ -53,8 +56,7 @@ verbose=:
 RunCommand () {
 	local ret c
 	if ${verbose}
-	then
-		einfo "${1}"
+	then	einfo "${1}"
 		shift
 		"${@}"
 		return ${?}
@@ -75,30 +77,27 @@ expr () {
 
 # Usage: Replace [-g] VAR Search Replace
 # Option -g means: Replace all occurrences
-# Exit status is the number of replacements (or 127 if there are more)
+# Exit status is 0 if at least one replacement took place, and
+# $replace_count contains at string of length(number of replacements) x'en.
 Replace () {
 	local ReplaceA_ ReplaceB_ ReplaceC_
 	ReplaceA_=''
-	ReplaceC_=''
+	ReplaceC_='break'
 	case "${1}" in
-		-*) ReplaceC_=0; shift;;
+		-*) ReplaceC_=''; shift;;
 	esac
+	replace_count=''
 	eval "while {
-		ReplaceB_=\${${1}%%\"\$2\"*}
+		ReplaceB_=\${${1}%%\"\${2}\"*}
 		[ \"\${ReplaceB_}\" != \"\${${1}}\" ]
 	}
-	do
-		ReplaceA_=\"\${ReplaceA_}\${ReplaceB_}\${3}\"
-		${1}=\${${1}#*\"\$2\"}
-		if [ -z \"\${ReplaceC_}\" ]; then
-			${1}=\"\${ReplaceA_}\${${1}}\"
-			return 1
-		fi
-		[ \${ReplaceC_} -ge 127 ] || \
-			ReplaceC_=\`expr \${ReplaceC_} + 1\`
+	do	ReplaceA_=\"\${ReplaceA_}\${ReplaceB_}\${3}\"
+		${1}=\${${1}#*\"\${2}\"}
+		replace_count=\"\${replace_count}x\"
+		${ReplaceC_}
 	done
 	${1}=\"\${ReplaceA_}\${${1}}\""
-	return ${ReplaceC_}
+	[ -n "${replace_count}" ]
 }
 
 # Usage: Push [-c] VAR Args
@@ -113,12 +112,10 @@ Push () {
 	PushA_="${1}"
 	shift
 	eval "for PushB_
-	do
-		Replace -g PushB_ \"'\" \"'\\\\''\"
-		if [ -z \"\${${PushA_}}\" ]; then
-			${PushA_}=\"'\${PushB_}'\"
-		else
-			${PushA_}=\"\${${PushA_}} '\${PushB_}'\"
+	do	Replace -g PushB_ \"'\" \"'\\\\''\"
+		if [ -z \"\${${PushA_}}\" ]
+		then	${PushA_}=\"'\${PushB_}'\"
+		else	${PushA_}=\"\${${PushA_}} '\${PushB_}'\"
 		fi
 	done"
 }
@@ -150,16 +147,14 @@ AddRepoName () {
 AddOverlays () {
 	local j
 	for j
-	do
-		AddUpdateArgs '-a' "${j}"
+	do	AddUpdateArgs '-a' "${j}"
 	done
 }
 
 AddExcludes () {
 	local j
 	for j
-	do
-		AddUpdateArgs '-x'
+	do	AddUpdateArgs '-x'
 		AddUpdateQuoting "${j}"
 	done
 }
@@ -168,7 +163,7 @@ ClearUpdateArgs () {
 	update_args=''
 }
 
-die_on_update_failure=:
+: ${die_on_update_failure=:}
 CallUpdate () {
 	eval "set -- ${update_args}"
 	RunCommand "`gettext 'Calling eix-update'`" eix-update "${@}" && return
@@ -180,8 +175,7 @@ AddLocalMethods () {
 	GetPortdir
 	AddMethod "${local_portdir}" "eix"
 	for i in `portageq portdir_overlay` `eix-update --print ADD_OVERLAY`
-	do
-		l="${i}"
+	do	l="${i}"
 		Replace -g l '\' '\\'
 		Replace -g l ':' '\:'
 		AddMethod "${i}" "eix::${l}"
@@ -193,8 +187,7 @@ AddLocalMethods () {
 Chomp () {
 	local ChompA_ ChompB_
 	for ChompA_
-	do
-		eval "ChompB_=\"\${${ChompA_}}\""
+	do	eval "ChompB_=\"\${${ChompA_}}\""
 		case "${ChompB_}" in
 			*'
 ')
@@ -210,8 +203,7 @@ Chomp () {
 Pathify () {
 	local PathifyA_ PathifyB_ PathifyC_
 	for PathifyC_
-	do
-		eval "PathifyA_=\"\${${PathifyC_}}\""
+	do	eval "PathifyA_=\"\${${PathifyC_}}\""
 		PathifyB_=`command -v "${PathifyA_}"; printf A` && \
 			PathifyB_="${PathifyB_%A}" && Chomp PathifyB_ && \
 			[ -n "${PathifyB_}" ] && test -x "${PathifyB_}" || \
@@ -231,33 +223,31 @@ Pathify () {
 NormalizeNames () {
 	local NormA_ NormB_ NormC_ NormD_
 	if [ -z "${have_readlink}" ]
-	then
-		command -v readlink >/dev/null 2>&1 \
+	then	command -v readlink >/dev/null 2>&1 \
 			&& have_readlink=: || have_readlink=false
 	fi
 	NormD_=0
 	relative=''
 	for NormC_
-	do
-		eval "NormA_=\"\${${NormC_}}\""
-		if [ -z "${NormA_}" ]; then
-			NormD_=1
+	do	eval "NormA_=\"\${${NormC_}}\""
+		if [ -z "${NormA_}" ]
+		then	NormD_=1
 			continue
 		fi
 		case "${NormA_}" in
 			/*) :;;
 			*) relative="${relative} ${NormC_}";;
 		esac
-		if ${have_readlink}; then
-			# Append A to avoid loss of trailing space in `...`
+		if ${have_readlink}
+		then	# Append A to avoid loss of trailing space in `...`
 			NormB_=`readlink -f -- "${NormA_}"; printf A` && \
 				NormB_="${NormB_%A}" && Chomp NormB_ && \
 				[ -n "${NormB_}" ] && \
 					NormA_="${NormB_}"
 		fi
 		eval "${NormC_}=\"\${NormA_}\""
-		while :; do
-			Replace -g "${NormC_}" '//' '/' && break
+		while Replace -g "${NormC_}" '//' '/'
+		do :
 		done
 		eval "[ \"\${${NormC_}}\" = '/' ] || \
 			${NormC_}=\"\${${NormC_}%/}\""
@@ -265,7 +255,7 @@ NormalizeNames () {
 	return ${NormD_}
 }
 
-read_gettext_status=''
+: ${read_gettext_status=}
 ReadGettext () {
 	[ -n "${read_gettext_status}" ] && return ${read_gettext_status}
 	case "${USE_NLS-@USE_NLS@}" in
@@ -275,8 +265,7 @@ ReadGettext () {
 			read_gettext_status=${?};;
 	esac
 	if [ ${read_gettext_status} -eq 0 ]
-	then
-		export TEXTDOMAIN='@TEXTDOMAIN@'
+	then	export TEXTDOMAIN='@TEXTDOMAIN@'
 		export TEXTDOMAINDIR='@TEXTDOMAINDIR@'
 		return
 	fi
@@ -313,37 +302,30 @@ AssignTempEmulate () {
 	local AssignTempA_ AssignTempB_ AssignTempC_
 	AssignTempA_=0
 	while [ ${AssignTempA_} -le 9999 ]
-	do
-		AssignTempB_="`od -An -N2 -x /dev/random 2>/dev/null`" || \
+	do	AssignTempB_="`od -An -N2 -x /dev/random 2>/dev/null`" || \
 			AssignTempB_=''
 		AssignTempB_="${AssignTempB_#* }${AssignTempA_}${RANDOM}"
 		AssignTempB_="/tmp/${0##*/}.${$}${RANDOM}${AssignTempB_}"
 		# We cannot avoid a race condition:
 		# So at least we minimize it to one line.
 		if [ "${2}" = '-d' ]
-		then
-			test ! -e "${AssignTempB_}" && mkdir "${AssignTempB_}"
-		else
-			test ! -e "${AssignTempB_}" && : >"${AssignTempB_}"
+		then	test ! -e "${AssignTempB_}" && mkdir "${AssignTempB_}"
+		else	test ! -e "${AssignTempB_}" && : >"${AssignTempB_}"
 		fi && eval "${1}=\"\${AssignTempB_}\"" && return
 		AssignTempA_="`expr ${AssignTempA_} + 1`"
 	done
 	die "`gettext 'found no free tempname after 10000 attempts'`"
 }
 
-have_mktemp=''
 AssignTemp () {
 	eval "${1}=''"
 	if [ -z "${have_mktemp}" ]
-	then
-		command -v mktemp >/dev/null 2>&1 \
+	then	command -v mktemp >/dev/null 2>&1 \
 			&& have_mktemp=: || have_mktemp=false
 	fi
 	if ${have_mktemp}
-	then
-		eval "${1}=\`mktemp ${2} \"/tmp/\${0##*/}.XXXXXXXX\"\`"
-	else
-		AssignTempEmulate "${@}"
+	then	eval "${1}=\`mktemp ${2} \"/tmp/\${0##*/}.XXXXXXXX\"\`"
+	else	AssignTempEmulate "${@}"
 	fi && return
 	[ "${2}" = '-d' ] && \
 		die "`gettext 'cannot create temporary directory'`"
