Add --installed-from-overlay/-J (old meaning: --installed-in-some-overlay) Callback to add overlays from installed display when OVERLAYS_LIST=renumbered
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@383 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mkmake b/mkmake
--- a/mkmake
+++ b/mkmake
@@ -9,12 +9,14 @@ Available options are
   -p  Use pedantic warnings (but no error on warnings) when modifying flags
   -s  With sqlite
   -S  Without sqlite
+  -b  With bzlib
+  -B  Without bzlib
   -c  Use only debugging-safe CXXFLAGS"
 	exit ${1}
 }
 
 die() {
-	echo "$1"
+	echo "${1}"
 	exit ${2:-1}
 }
 
@@ -23,8 +25,9 @@ EARLYSTOP=''
 KEEPENV=''
 SAVEFLAGS=''
 SQLITE=''
+BZLIB=''
 PEDANTIC=''
-while getopts 'qsSnepc?hH' OPTION; do
+while getopts 'qnepsSbBc?hH' OPTION; do
 case "$OPTION" in
 	q) QUIET='&>/dev/null';;
 	n) EARLYSTOP=1;;
@@ -32,6 +35,8 @@ case "$OPTION" in
 	p) PEDANTIC=1;;
 	s) SQLITE='--with-sqlite';;
 	S) SQLITE='--without-sqlite';;
+	b) BZLIB='--with-bzip2';;
+	B) BZLIB='--without-bzip2';;
 	c) SAFEFLAGS=1;;
 	*) Usage 1;;
 esac
@@ -68,7 +73,7 @@ if ! [[ -e Makefile ]]; then
 		eval ./autogen.sh $QUIET || die "autogen failed"
 	fi
 	echo "Running configure..."
-	eval ./configure $SQLITE $QUIET || die "configure failed"
+	eval ./configure $SQLITE $BZLIB $QUIET || die "configure failed"
 fi
 [[ "$EARLYSTOP" ]] && exec make config.h
 echo "Making $@..."
