Fix std::unique() and minor compatibility issues.
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@371 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mksvnclean b/mksvnclean
--- a/mksvnclean
+++ b/mksvnclean
@@ -4,11 +4,12 @@ die() {
 	exit ${2:-1}
 }
 
-if [[ -e configure ]]; then
-	[[ -e Makefile.in ]] || ./autogen.sh || die "./autogen.sh failed"
-	[[ -e Makefile ]] || ./configure || die "./configure failed"
+if ! [ -e Makefile ]; then
+	[ -e Makefile.in ] && [ -e configure ] \
+		|| ./autogen.sh || die "./autogen.sh failed"
+	./configure || die "./configure failed"
 fi
-if [[ -e Makefile ]]; then
+if [ -e Makefile ]; then
 	make maintainer-clean || die "make maintainer-clean failed"
 fi
 rm -vrf build config
