Introduce cache methods parse{,*}|ebuild{,*} and make it default for overlays. Rename none{,*} to parse{,*} Remove broken portage-2.1* cache method (unless ./configure'd otherwise) Introduce ./configure --enable-as-needed Make basicversion.cc use std namespace Fix pedantic compiler warnings
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@590 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mktarball b/mktarball
--- a/mktarball
+++ b/mktarball
@@ -16,10 +16,10 @@ test -d build || die "cannot create directory build"
 
 unset LDFLAGS CFLAGS CXXFLAGS
 if command -v fakeroot >/dev/null 2>&1; then
-	./mkmake -eqn || die "mkmake -qn failed"
-	fakeroot ./mkmake -q dist || die "mkmake dist failed"
+	./mkmake -0eqn || die "mkmake -qn failed"
+	fakeroot ./mkmake -0q dist || die "mkmake dist failed"
 else
-	./mkmake -eq dist || die "mkmake dist failed"
+	./mkmake -0eq dist || die "mkmake dist failed"
 fi
 
 for i in *.tar*; do
