Describe slotted version format in manpage. Fix logic in expressions: No toggling of tests, and let -i/-I not cancel further tests like -O. mktarball now uses fakeroot if available.
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@210 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mktarball b/mktarball
--- a/mktarball
+++ b/mktarball
@@ -13,7 +13,11 @@ mkdir build &>/dev/null
 pushd build/ &>/dev/null || die "pushd build failed"
 popd &>/dev/null || die "popd failed"
 
-./mkmake -q dist || die "mkmake dist failed"
+if FAKEROOT="$(type -P fakeroot)"; then
+	"$FAKEROOT" ./mkmake -q dist || die "mkmake dist failed"
+else
+	./mkmake -q dist || die "mkmake dist failed"
+fi
 
 for i in *.tar*; do
 	md5sum "$i" >"$i.md5"
