Fix echo -> printf. Cleanup scripts. Release lzma
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@757 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/mktarball b/mktarball
--- a/mktarball
+++ b/mktarball
@@ -2,31 +2,51 @@
 
 export LC_ALL=C
 
-usage() {
-	echo "Usage: mktarball"
+Usage() {
+	printf "%s\n" "Usage: ${0##*/} [all|bzip2]"
+	exit ${1}
 }
 
-die() {
-	echo "$1"
+Die() {
+	printf "%s: %s\n" "${0##*/}" "${1}"
 	exit ${2:-1}
 }
 
+MAKEARCH="dist-lzma"
+[ $# -ne 0 ] && [ -n "${1}" ] && case "${1}" in
+	h*|H*|*\?*|-*) Usage;;
+	b*|B*) MAKEARCH="dist-bzip2";;
+	l*|L*|'') :;;
+	*) MAKEARCH="${MAKEARCH} dist";;
+esac
+
 test -e Makefile || test -e configure || test -e Makefile.in && ./mksvnclean
-test -d build || mkdir build >/dev/null
-test -d build || die "cannot create directory build"
 
 unset LDFLAGS CFLAGS CXXFLAGS
 if command -v fakeroot >/dev/null 2>&1; then
-	./mkmake -0eqn || die "mkmake -qn failed"
-	fakeroot ./mkmake -0q dist || die "mkmake dist failed"
+	./mkmake -0eqn || Die "./mkmake -qn failed"
+	DOCMD='fakeroot ./mkmake -0q'
+	DOMSK='fakeroot ./mkmake'
 else
-	./mkmake -0eq dist || die "mkmake dist failed"
+	DOCMD='./mkmake -0eq'
+	DOMSG='./mkmake'
 fi
-
-for i in *.tar*; do
-	md5sum "$i" >"$i.md5"
-	mv "$i" "$i.md5" build
+for i in ${MAKEARCH}
+do
+	${DOCMD} ${i} || Die "${DOMSG} ${i} failed" ${?}
 done
 
-echo "Tarball is at build/"
-echo "Note that to tag the release in svn you should run mkrelease"
+found=false
+for j in tar.lzma tar.bz2 tar.gz zip tar.Z shar.gz shar
+do
+	for i in "${PWD}"/eix-*.${j}
+	do
+		test -f "${i}" || continue
+		$found || echo "Available tarballs:"
+		found=true
+		printf "\t%s\n" "${i}"
+	done
+done
+$found || Die "For some reason no tarball was created"
+echo "The tarballs will be removed with ./mksvnclean
+Note that to tag the release in svn you should run mkrelease"
diff --git a/src/eix-test-obsolete.in b/src/eix-test-obsolete.in
--- a/src/eix-test-obsolete.in
+++ b/src/eix-test-obsolete.in
@@ -8,21 +8,23 @@
 # This script gives a structured output of eix -tTc (@PACKAGE_STRING@).
 
 DETAILS=false
+Die () {
+	printf "%s: %s\n" "${0##*/}" "${1}" >&2
+	exit ${2:-1}
+}
+
 Eix () {
 	if [ -z "`eix '-*Tc' | head -n1`" ]; then
-		[ -z "${1}" ] || echo "${1} (or test switched off)."
+		[ -z "${1}" ] || printf "%s\n" "${1} (or test switched off)."
 		return
 	fi
 	if [ ${#} -le 2 ] || ! ${DETAILS}; then
-		echo "
-${2}:
-"
+		printf "\n%s:\n" "${2}"
 		eix -Tc
-		echo
+		printf "\n"
 		return
 	fi
-	echo "
-${2}..."
+	printf "\n%s\n" "${2}..."
 	shift 2
 	local I
 	for I; do
@@ -84,13 +86,10 @@ Repository () {
 	else
 		I='without'
 	fi
-	echo "The following package versions are installed ${I} repository information:"
-	if ! cd -- "`eix --print EPREFIX_INSTALLED`"/var/db/pkg >/dev/null 2>&1
-	then
-		echo "${0##*/}: cannot locate your database of installed packages" >&2
-		exit 1
-	fi
-	echo
+	cd -- "`eix --print EPREFIX_INSTALLED`"/var/db/pkg >/dev/null 2>&1 \
+		|| Die "cannot locate your database of installed packages"
+	printf "%s\n\n" \
+	"The following package versions are installed ${I} repository information:"
 	C=0
 	( eval '[ "$(( ${C} + 1 ))" = 1 ]' ) >/dev/null 2>&1 \
 		&& A='$(( ${C} + 1 ))' || A='`expr "${C}" + 1`'
@@ -101,15 +100,14 @@ Repository () {
 			else
 				${1} && continue
 			fi
-			echo "${J}"
+			printf "%s\n" "${J}"
 			eval "C=${A}"
 		done
 	done
 	if test ${C} -eq 0; then
-		echo "none"
+		printf "%s\n" "none"
 	elif test ${C} -ne 1; then
-		echo "
-(total number of versions listed above: ${C})"
+		printf "\n%s\n" "(total number of versions listed above: ${C})"
 	fi
 	exit 0
 }
diff --git a/src/functions-eix.sh.in b/src/functions-eix.sh.in
--- a/src/functions-eix.sh.in
+++ b/src/functions-eix.sh.in
@@ -22,7 +22,7 @@ read_functions () {
 		. "${I}"
 		return
 	done
-	echo "${0##*/}: Cannot read functions.sh" >&2
+	printf "%s: %s" "${0##*/}" "cannot read functions.sh" >&2
 	exit 2
 }
 
@@ -200,7 +200,7 @@ NormalizeNames () {
 		esac
 		if ${HAVE_READLINK}; then
 			# Append A to avoid loss of trailing \n in `...`
-			NormB_=`readlink -f -- "${NormA_}" && echo A` && \
+			NormB_=`readlink -f -- "${NormA_}" ; printf A` && \
 				NormB_="${NormB_%A}" && Chomp NormB_ && \
 				[ -n "${NormB_}" ] && \
 					NormA_="${NormB_}"
