Compatibility and formatting tweaks in scripts
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@511 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/src/eix-sync.in b/src/eix-sync.in
--- a/src/eix-sync.in
+++ b/src/eix-sync.in
@@ -42,7 +42,7 @@ PMOD="${LOCAL_PORTAGE_CONFIGROOT}/etc/portage/modules"
 MODULENAME='cache.metadata_overlay.database'
 
 Usage () {
-  echo "${0##*/} [options]
+	echo "${0##*/} [options]
 Call layman/emerge --sync/--metadata and/or show updates. (@PACKAGE_STRING@)
 
 Unless the -v option is used, the output of most commands is redirected to
@@ -90,59 +90,59 @@ The following options are available:
 -R   Do not really recreate the dep-cache.
 -e   Skip heuristic tests whether you must be root.
 -h   Show this text and exit."
-  EXITCODE=${1}
-  exit ${1}
+	EXITCODE=${1}
+	exit ${1}
 }
 
 DiffOnly() {
-  test -e "${EIXPREVIOUS}" || die "No previous database ${EIXPREVIOUS} exists"
-  exec diff-eix -- "${EIXPREVIOUS}"
-  die "Could not execute diff-eix"
+	test -e "${EIXPREVIOUS}" || die "No previous database ${EIXPREVIOUS} exists"
+	exec diff-eix -- "${EIXPREVIOUS}"
+	die "Could not execute diff-eix"
 }
 
 if test -r "${LAYMANCONF}"; then
-  HAVECONF=true
+	HAVECONF=true
 else
-  HAVECONF=false
+	HAVECONF=false
 fi
 declare -a AFTER_SYNC AFTER_UPDATE BEFORE_RSYNC
 ExecuteConfig () {
-  local I J MYCMD
-  AFTER_SYNC=()
-  AFTER_UPDATE=()
-  BEFORE_RSYNC=()
-  CONFIG_OPTS=''
-  ${HAVECONF} || return 0
-  while read I; do
-    J="${I%%#*}"
-    while test "${J% }" != "${J}"; do J="${J%?}"; done
-    while test "${J:0:1}" = " "; do J="${J#?}"; done
-    test -n "${J}" || continue
-    case "${J}" in
-      !*)  J="${J#?}"; MYCMD='!';;
-      @@*) J="${J#??}"; MYCMD='@@';;
-      @*)  J="${J#?}"; MYCMD='@';;
-      \~*) J="${J#?}"; MYCMD='~';;
-      -*)  CONFIG_OPTS="${CONFIG_OPTS} ${J}"; continue;;
-      *)   MYCMD="layman";;
-    esac
-    test "${1}" = 'opts' && continue
-    case "${MYCMD}" in
-      @@) Push AFTER_UPDATE "${J}"; continue;;
-      @)  Push AFTER_SYNC "${J}"; continue;;
-      \~) Push BEFORE_RSYNC "${J}"; continue;;
-      !)  ${NOLAYMAN} || DoExecute "${J}"; continue;;
-    esac
-    ${NOLAYMAN} && continue
-    RootTest
-    if test "${J}" = '*'; then
-      MyRunCommand "Syncing all portage overlays"
-        "${MYCMD}" -S || die "${MYCMD} -S failed"
-      continue;
-    fi
-    MyRunCommand "Syncing portage overlay '${J}'"
-      "${MYCMD}" -s "${J}" || die "${MYCMD} -s ${J} failed"
-  done <"${LAYMANCONF}"
+	local I J MYCMD
+	AFTER_SYNC=()
+	AFTER_UPDATE=()
+	BEFORE_RSYNC=()
+	CONFIG_OPTS=''
+	${HAVECONF} || return 0
+	while read I; do
+		J="${I%%#*}"
+		while [ "${J% }" != "${J}" ]; do J="${J%?}"; done
+		while [ "${J# }" != "${J}" ]; do J="${J#?}"; done
+		[ -n "${J}" ] || continue
+		case "${J}" in
+			!*)  J="${J#?}"; MYCMD='!';;
+			@@*) J="${J#??}"; MYCMD='@@';;
+			@*)  J="${J#?}"; MYCMD='@';;
+			\~*) J="${J#?}"; MYCMD='~';;
+			-*)  CONFIG_OPTS="${CONFIG_OPTS} ${J}"; continue;;
+			*)   MYCMD="layman";;
+		esac
+		[ "${1}" = 'opts' ] && continue
+		case "${MYCMD}" in
+			@@) Push AFTER_UPDATE "${J}"; continue;;
+			@)  Push AFTER_SYNC "${J}"; continue;;
+			\~) Push BEFORE_RSYNC "${J}"; continue;;
+			!)  ${NOLAYMAN} || DoExecute "${J}"; continue;;
+		esac
+		${NOLAYMAN} && continue
+		RootTest
+		if [ "${J}" = '*' ]; then
+			MyRunCommand "Syncing all portage overlays"
+				"${MYCMD}" -S || die "${MYCMD} -S failed"
+			continue;
+		fi
+		MyRunCommand "Syncing portage overlay '${J}'"
+			"${MYCMD}" -s "${J}" || die "${MYCMD} -s ${J} failed"
+	done <"${LAYMANCONF}"
 }
 
 
@@ -150,323 +150,326 @@ ExecuteConfig () {
 declare -a EMERGECMD
 
 DefaultOpts () {
-  EMERGECMD=('emerge' '--sync')
-  CLEARCACHE=true
-  NOLAYMAN=false
-  NOHOOKS=false
-  VERBOSE=false
-  QUIET=false
-  USETEMP=false
-  METADATA=false
-  SKIP_SYNC=false
-  SERVER=''
-  CLIENT=''
-  DOUPDATE=true
-  SYNCHOOKS=true
-  TEST_FOR_ROOT=true
+	EMERGECMD=('emerge' '--sync')
+	CLEARCACHE=true
+	NOLAYMAN=false
+	NOHOOKS=false
+	VERBOSE=false
+	QUIET=false
+	USETEMP=false
+	METADATA=false
+	SKIP_SYNC=false
+	SERVER=''
+	CLIENT=''
+	DOUPDATE=true
+	SYNCHOOKS=true
+	TEST_FOR_ROOT=true
 }
 
 DefaultOpts
 ExecuteConfig 'opts'
 
 while getopts "ids:2:Uul@SmMtvVqwWc:C:rRe?hH" OPTION \
-  ${CONFIG_OPTS} ${EIX_SYNC_OPTS} "${@}"; do
-  case "${OPTION}" in
-    i) DefaultOpts;;
-    d) DiffOnly;;
-    s) SERVER="${OPTARG}";;
-    2) CLIENT="${OPTARG}";;
-    U) DOUPDATE=false;;
-    u) NOLAYMAN=true; NOHOOKS=true; SKIP_SYNC=true; SERVER='';;
-    l) NOLAYMAN=true;;
-    @) NOHOOKS=true;;
-    S) SYNCHOOKS=false;;
-    m) SKIP_SYNC=true;;
-    M) METADATA=true;;
-    t) USETEMP=true;;
-    v) VERBOSE=true;;
-    V) VERBOSE=false;;
-    q) QUIET=true;;
-    w) EMERGECMD=("emerge-webrsync");;
-    W) EMERGECMD=("emerge-delta-webrsync");;
-    c) EMERGECMD=(); EMERGECMD[0]="${OPTARG}";;
-    C) Push EMERGECMD "${OPTARG}";;
-    r) CLEARCACHE=true;;
-    R) CLEARCACHE=false;;
-    e) TEST_FOR_ROOT=false;;
-    *) Usage 1;;
-  esac
+	${CONFIG_OPTS} ${EIX_SYNC_OPTS} "${@}"; do
+	case "${OPTION}" in
+		i) DefaultOpts;;
+		d) DiffOnly;;
+		s) SERVER="${OPTARG}";;
+		2) CLIENT="${OPTARG}";;
+		U) DOUPDATE=false;;
+		u) NOLAYMAN=true; NOHOOKS=true; SKIP_SYNC=true; SERVER='';;
+		l) NOLAYMAN=true;;
+		@) NOHOOKS=true;;
+		S) SYNCHOOKS=false;;
+		m) SKIP_SYNC=true;;
+		M) METADATA=true;;
+		t) USETEMP=true;;
+		v) VERBOSE=true;;
+		V) VERBOSE=false;;
+		q) QUIET=true;;
+		w) EMERGECMD=("emerge-webrsync");;
+		W) EMERGECMD=("emerge-delta-webrsync");;
+		c) EMERGECMD=(); EMERGECMD[0]="${OPTARG}";;
+		C) Push EMERGECMD "${OPTARG}";;
+		r) CLEARCACHE=true;;
+		R) CLEARCACHE=false;;
+		e) TEST_FOR_ROOT=false;;
+		*) Usage 1;;
+	esac
 done
 ${DOUPDATE} || CLEARCACHE=false
-test -n "${SERVER}" && SKIP_SYNC=true
+[ -z "${SERVER}" ] || SKIP_SYNC=true
 ${SKIP_SYNC} && METADATA=true
 
 # We need a special function to treat the reserved word "time" like a command.
 # (Of course "eval" would do a similar thing, but would also apply to args).
 MyRun () {
-  if test "${1}" != 'time'; then
-    "${@}"
-    return
-  fi
-  shift
-  time "${@}"
-  return
+	if [ "${1}" != 'time' ]; then
+		"${@}"
+		return
+	fi
+	shift
+	time "${@}"
+	return
 }
 
 # Run command
 # if VERBOSE is true, redirect 1,2 to logfile|/dev/null and use ebegin/eend
 # (instead of einfo)
 MyRunCommand () {
-  local RET
-  ${EMULATEMODE} && return 0
-  if ${VERBOSE}; then
-    einfo "${1}"
-    shift
-    MyRun "${@}"
-    return "${?}"
-  fi
-  ebegin "${1}"
-  shift
-  MyRun "${@}" >>"${REDIRECT}" 2>&1
-  RET=${?}
-  eend "${RET}" "Problems running ${@}"
-  return ${RET}
+	local RET
+	${EMULATEMODE} && return 0
+	if ${VERBOSE}; then
+		einfo "${1}"
+		shift
+		MyRun "${@}"
+		return "${?}"
+	fi
+	ebegin "${1}"
+	shift
+	MyRun "${@}" >>"${REDIRECT}" 2>&1
+	RET=${?}
+	eend "${RET}" "Problems running ${@}"
+	return ${RET}
 }
 
 DoExecute () {
-  ${EMULATEMODE} && return 0
-  (
-    for CURRENT_COMMAND; do
-      MyRunCommand "Executing ${CURRENT_COMMAND}" \
-        eval "${CURRENT_COMMAND}" ||
-          die "Something went wrong with ${CURRENT_COMMAND}"
-    done
-  ) || die
+	${EMULATEMODE} && return 0
+	(
+		for CURRENT_COMMAND; do
+			MyRunCommand "Executing ${CURRENT_COMMAND}" \
+			eval "${CURRENT_COMMAND}" ||
+			die "Something went wrong with ${CURRENT_COMMAND}"
+		done
+	) || die
 }
 
 DoHook () {
-  ${NOHOOKS} && return 0
-  DoExecute "${@}"
+	${NOHOOKS} && return 0
+	DoExecute "${@}"
 }
 
 RootTest () {
-  ${EMULATEMODE} || return 0
-  eerror ""
-  eerror "Nothing was executed, because a heuristic shows that"
-  eerror "root permissions are required to execute everything successfully."
-  einfo  ""
-  einfo  "However, the heuristic might be wrong, e.g. if you use EPREFIX."
-  einfo  "If you want to skip this test temporarily, use option -e."
-  einfo  "If you want to skip this test permanently, put option -e"
-  einfo  "into the file ${LAYMANCONF}."
-  die    ""
+	${EMULATEMODE} || return 0
+	eerror ""
+	eerror "Nothing was executed, because a heuristic shows that"
+	eerror "root permissions are required to execute everything successfully."
+	einfo  ""
+	einfo  "However, the heuristic might be wrong, e.g. if you use EPREFIX."
+	einfo  "If you want to skip this test temporarily, use option -e."
+	einfo  "If you want to skip this test permanently, put option -e"
+	einfo  "into the file ${LAYMANCONF}."
+	die    ""
 }
 
 SED1='s!^[[:space:]]*'
 SED2="[[:space:]]*=[[:space:]]*\([^[:space:]]*\)[[:space:]]*\$!\1!p"
 SedFor () {
-  local A=''
-  test -e "${2}" && \
-    A="$(sed -n -e "${SED1}${1}${SED2}" -- "${2}" | tail -n 1)"
-  A="${A%\"}"
-  A="${A#\"}"
-  A="${A%'}"
-  A="${A#'}"
-  echo "${A}"
+	local A=''
+	test -e "${2}" && \
+		A="$(sed -n -e "${SED1}${1}${SED2}" -- "${2}" | tail -n 1)"
+	A="${A%\"}"
+	A="${A#\"}"
+	A="${A%'}"
+	A="${A#'}"
+	echo "${A}"
 }
 
 TMPFILE=''
 EXITCODE=0
 DelTemp () {
-  test -z "${TMPFILE}" || rm -f -- "${TMPFILE}"
-  trap '' 0 1 2 15
-  exit ${EXITCODE}
+	[ -z "${TMPFILE}" ] || rm -f -- "${TMPFILE}"
+	TMPFILE=''
+	trap - EXIT HUP INT TERM
+	exit ${EXITCODE}
 }
 MakeTempFile () {
-  local COUNT
-  if type mktemp >/dev/null 2>&1; then
-    TMPFILE="$(mktemp /tmp/${0##*/}.XXXXXX)" || \
-      die "cannot create temporary file"
-  else
-    COUNT=0
-    while true; do
-       test ${COUNT} -eq 9999 && \
-         die "found no free tempname after 10000 attempts"
-       COUNT=$(( ${COUNT} + 1 ))
-      TMPFILE="/tmp/${0##*/}.$$.${RANDOM}.${RANDOM}.${RANDOM}"
-      test -e "${TMPFILE}" && continue
-      >"${TMPFILE}" || die "cannot create temporary file ${TMPFILE}"
-      break
-    done
-  fi
-  trap DelTemp 0 1 2 15
+	local COUNT
+	if type mktemp >/dev/null 2>&1; then
+		TMPFILE="$(mktemp /tmp/${0##*/}.XXXXXX)" || \
+			die "cannot create temporary file"
+	else
+		COUNT=0
+		while true; do
+			[ ${COUNT} -eq 9999 ] && \
+				die "found no free tempname after 10000 attempts"
+			COUNT=$(( ${COUNT} + 1 ))
+			TMPFILE="/tmp/${0##*/}.$$.${RANDOM}.${RANDOM}.${RANDOM}"
+			test -e "${TMPFILE}" && continue
+			: >"${TMPFILE}" || die "cannot create temporary file ${TMPFILE}"
+			break
+		done
+	fi
+	trap DelTemp EXIT HUP INT TERM
 }
 
 PREPRSYNC=false
 PrepRsync () {
-  local CURRENT_COMMAND PORTAGE_RSYNC_OPTS PORTAGE_RSYNC_EXTRA_OPTS
-  GetPortdir
-  HOSTDIR="${1#*:}"
-  if test -n "${HOSTDIR}" && test "${HOSTDIR}" != "${1}"; then
-    HOSTDIR="${1}"
-  else
-    HOSTDIR="${1%%:*}:${LOCAL_PORTDIR}"
-  fi
-  HOSTDIR="${HOSTDIR%/}/"
-  ${PREPRSYNC} && return
-  PORTAGE_RSYNC_OPTS="$(portageq envvar PORTAGE_RSYNC_OPTS)"
-  PORTAGE_RSYNC_EXTRA_OPTS="$(portageq envvar PORTAGE_RSYNC_EXTRA_OPTS)"
-  for CURRENT_COMMAND in "${BEFORE_RSYNC[@]}"; do
-    eval "$(eval "${CURRENT_COMMAND}")" || die "${CURRENT_COMMAND} failed"
-  done
-  RSYNC_OPTS="${PORTAGE_RSYNC_OPTS} ${PORTAGE_RSYNC_EXTRA_OPTS}"
-  PREPRSYNC=true
+	local CURRENT_COMMAND PORTAGE_RSYNC_OPTS PORTAGE_RSYNC_EXTRA_OPTS
+	GetPortdir
+	HOSTDIR="${1#*:}"
+	if [ -n "${HOSTDIR}" ] && [ "${HOSTDIR}" != "${1}" ]; then
+		HOSTDIR="${1}"
+	else
+		HOSTDIR="${1%%:*}:${LOCAL_PORTDIR}"
+	fi
+	HOSTDIR="${HOSTDIR%/}/"
+	${PREPRSYNC} && return
+	PORTAGE_RSYNC_OPTS="$(portageq envvar PORTAGE_RSYNC_OPTS)"
+	PORTAGE_RSYNC_EXTRA_OPTS="$(portageq envvar PORTAGE_RSYNC_EXTRA_OPTS)"
+	for CURRENT_COMMAND in "${BEFORE_RSYNC[@]}"; do
+		eval "$(eval "${CURRENT_COMMAND}")" || die "${CURRENT_COMMAND} failed"
+	done
+	RSYNC_OPTS="${PORTAGE_RSYNC_OPTS} ${PORTAGE_RSYNC_EXTRA_OPTS}"
+	PREPRSYNC=true
 }
 
 ClearCache () {
-  ${CLEARCACHE} || return 0
-  # Cleaning old cache
-  # portage 2.1_pre1 doesn't do this anymore, so *we* need to do it.
-  RootTest
-  MyRunCommand "Removing old portage-cache in ${LOCAL_VARCACHE}/var/cache/edb/dep" \
-    rm -rf -- "${LOCAL_VARCACHE}"/var/cache/edb/dep/* || \
-      die "rm -rf ${LOCAL_VARCACHE}/var/cache/edb/dep/* failed"
+	${CLEARCACHE} || return 0
+	# Cleaning old cache
+	# portage 2.1_pre1 doesn't do this anymore, so *we* need to do it.
+	RootTest
+	MyRunCommand "Removing old portage-cache in ${LOCAL_VARCACHE}/var/cache/edb/dep" \
+		rm -rf -- "${LOCAL_VARCACHE}"/var/cache/edb/dep/* || \
+			die "rm -rf ${LOCAL_VARCACHE}/var/cache/edb/dep/* failed"
 }
 
 CallEmergeSync () {
-  if test -n "${SERVER}"; then
-    ${EMULATEMODE} && return
-    PrepRsync "${SERVER}"
-    MyRunCommand "rsyncing from ${HOSTDIR}" \
-      rsync $RSYNC_OPTS "${HOSTDIR}" "${LOCAL_PORTDIR}" || \
-        die "Could not rsync from ${HOSTDIR}"
-    return
-  fi
-  ${SKIP_SYNC} && return
-  RootTest
-  MyRunCommand "Running ${EMERGECMD[*]}" \
-    time "${EMERGECMD[@]}" || die "${EMERGECMD[*]} failed"
+	if [ -n "${SERVER}" ]; then
+		${EMULATEMODE} && return
+		PrepRsync "${SERVER}"
+		MyRunCommand "rsyncing from ${HOSTDIR}" \
+			rsync $RSYNC_OPTS "${HOSTDIR}" "${LOCAL_PORTDIR}" || \
+				die "Could not rsync from ${HOSTDIR}"
+		return
+	fi
+	${SKIP_SYNC} && return
+	RootTest
+	MyRunCommand "Running ${EMERGECMD[*]}" \
+		time "${EMERGECMD[@]}" || die "${EMERGECMD[*]} failed"
 }
 
 CallSyncClient () {
-  ${EMULATEMODE} && return
-  test -z "${CLIENT}" && return
-  PrepRsync "${CLIENT}"
-  MyRunCommand "rsyncing to ${HOSTDIR}" \
-    rsync ${RSYNC_OPTS} "${LOCAL_PORTDIR}" "${HOSTDIR}" || \
-      die "Could not rsync to ${HOSTDIR}"
+	${EMULATEMODE} && return
+	[ -z "${CLIENT}" ] && return
+	PrepRsync "${CLIENT}"
+	MyRunCommand "rsyncing to ${HOSTDIR}" \
+		rsync ${RSYNC_OPTS} "${LOCAL_PORTDIR}" "${HOSTDIR}" || \
+			die "Could not rsync to ${HOSTDIR}"
 }
 
 TESTRESULT=''
 CallEmergeMetadata () {
-  ${DOUPDATE} && ${METADATA} || return 0
-  if test -z "${TESTRESULT}"; then
-    if test "$(SedFor 'portdbapi.auxdbmodule' "${PMOD}")" = "${MODULENAME}"
-    then
-      TESTRESULT='false'
-    else
-      TESTRESULT='true'
-    fi
-  fi
-  if test "${TESTRESULT}" = 'false'; then
-    ${EMULATEMODE} || \
-      einfo "emerge --metadata is skipped due to settings in ${PMOD}"
-    return
-  fi
-  RootTest
-  MyRunCommand "Running emerge --metadata" \
-    emerge --metadata || die "emerge --metadata failed"
+	${DOUPDATE} && ${METADATA} || return 0
+	if [ -z "${TESTRESULT}" ]; then
+		if test "$(SedFor 'portdbapi.auxdbmodule' "${PMOD}")" = "${MODULENAME}"
+		then
+			TESTRESULT='false'
+		else
+			TESTRESULT='true'
+		fi
+	fi
+	if [ "${TESTRESULT}" = 'false' ]; then
+		${EMULATEMODE} || \
+			einfo "emerge --metadata is skipped due to settings in ${PMOD}"
+		return
+	fi
+	RootTest
+	MyRunCommand "Running emerge --metadata" \
+		emerge --metadata || die "emerge --metadata failed"
 }
 
 CondUpdate () {
-  if ! test -f "${EIXCACHE}"; then
-    RootTest
-    MyRunCommand "eix-cache doesn't exist. Running update-eix!" \
-        update-eix || die "update-eix failed"
-    return
-  fi
-  ${EMULATEMODE} && return
-  if ! eix --is-current; then
-    MyRunCommand "eix-cache format has changed. Running update-eix!" \
-        update-eix || die "update-eix failed"
-  fi
+	if ! test -f "${EIXCACHE}"; then
+		RootTest
+		MyRunCommand "eix-cache doesn't exist. Running update-eix!" \
+				update-eix || die "update-eix failed"
+		return
+	fi
+	${EMULATEMODE} && return
+	if ! eix --is-current; then
+		MyRunCommand "eix-cache format has changed. Running update-eix!" \
+				update-eix || die "update-eix failed"
+	fi
 }
 
 CopyPrevious () {
-  ${DOUPDATE} || return 0
-  ${EMULATEMODE} && return
-  MakeTempFile
-  ( umask 002 ; cp -- "${EIXCACHE}" "${TMPFILE}" ) ||
-    die "Could not copy database to temporary file ${TMPFILE}"
+	${DOUPDATE} || return 0
+	${EMULATEMODE} && return
+	MakeTempFile
+	( umask 002 ; cp -- "${EIXCACHE}" "${TMPFILE}" ) ||
+		die "Could not copy database to temporary file ${TMPFILE}"
 }
 
 MovePrevious () {
-  ${USETEMP} && return
-  ( umask 002
-    MyRunCommand "Copying old ${EIXCACHE} cache to ${EIXPREVIOUS}" \
-      mv -f -- "${TMPFILE}" "${EIXPREVIOUS}" ) ||
-      die "Could not move ${TMPFILE} to ${EIXPREVIOUS}"
-  test "${UID}" -eq 0 && chown -- portage:portage "${EIXPREVIOUS}" >/dev/null 2>&1
-  chmod -- 664 "${EIXPREVIOUS}" >/dev/null 2>&1
+	${USETEMP} && return
+	(
+		umask 002
+		MyRunCommand "Copying old ${EIXCACHE} cache to ${EIXPREVIOUS}" \
+		mv -f -- "${TMPFILE}" "${EIXPREVIOUS}"
+	) || die "Could not move ${TMPFILE} to ${EIXPREVIOUS}"
+	[ "${UID}" -eq 0 ] && \
+		chown -- portage:portage "${EIXPREVIOUS}" >/dev/null 2>&1
+	chmod -- 664 "${EIXPREVIOUS}" >/dev/null 2>&1
 }
 
 UpdateDiff () {
-  local D
-  ${DOUPDATE} || return 0
-  if ${USETEMP}; then
-    ${EMULATEMODE} && return
-    D="${TMPFILE}"
-  else
-    D="${EIXPREVIOUS}"
-    test -e "${D}" || RootTest
-    ${EMULATEMODE} && return
-  fi
-  if test "${EIXCACHE}" -nt "${TMPFILE}"; then
-    MovePrevious
-    einfo "update-eix was apparently already called in a hook"
-  else
-    MovePrevious
-    MyRunCommand "Running update-eix" "update-eix" || \
-      die "Failure while running update-eix"
-  fi
-  DoHook "${AFTER_UPDATE[@]}"
-  diff-eix -- "${D}" || die "Failed to diff against current cache"
+	local D
+	${DOUPDATE} || return 0
+	if ${USETEMP}; then
+		${EMULATEMODE} && return
+		D="${TMPFILE}"
+	else
+		D="${EIXPREVIOUS}"
+		test -e "${D}" || RootTest
+		${EMULATEMODE} && return
+	fi
+	if test "${EIXCACHE}" -nt "${TMPFILE}"; then
+		MovePrevious
+		einfo "update-eix was apparently already called in a hook"
+	else
+		MovePrevious
+		MyRunCommand "Running update-eix" "update-eix" || \
+			die "Failure while running update-eix"
+	fi
+	DoHook "${AFTER_UPDATE[@]}"
+	diff-eix -- "${D}" || die "Failed to diff against current cache"
 }
 
 MainSync () {
-  CondUpdate
-  ClearCache
-  CopyPrevious
-  ExecuteConfig 'sync'
-  CallEmergeSync
-  ${SYNCHOOKS} && DoHook "${AFTER_SYNC[@]}"
-  CallSyncClient
-  CallEmergeMetadata
-  UpdateDiff
+	CondUpdate
+	ClearCache
+	CopyPrevious
+	ExecuteConfig 'sync'
+	CallEmergeSync
+	${SYNCHOOKS} && DoHook "${AFTER_SYNC[@]}"
+	CallSyncClient
+	CallEmergeMetadata
+	UpdateDiff
 }
 
-if ${TEST_FOR_ROOT} && test "${UID}" -ne 0; then
+if ${TEST_FOR_ROOT} && [ "${UID}" -ne 0 ]; then
 # Emulate everything to check whether we have to be root:
-  EMULATEMODE=true
-  MainSync
+	EMULATEMODE=true
+	MainSync
 fi
 EMULATEMODE=false
 
 # Clean out logfile and redirect
 if (
-     umask 002
-     if ${QUIET} || ! ${VERBOSE}; then
-       >"${LOGFILE}" || exit 1
-       test "${UID}" -eq 0 && \
-         chown -- portage:portage "${LOGFILE}" >/dev/null 2>&1
-     fi
-     exit 0
-   ) >/dev/null 2>&1
+	umask 002
+	if ${QUIET} || ! ${VERBOSE}; then
+		: >"${LOGFILE}" || exit 1
+		[ "${UID}" -eq 0 ] && \
+		chown -- portage:portage "${LOGFILE}" >/dev/null 2>&1
+	fi
+	exit 0
+	) >/dev/null 2>&1
 then
-  REDIRECT="${LOGFILE}"
+	REDIRECT="${LOGFILE}"
 else
-  REDIRECT=/dev/null
-  eerror "Redirection to ${LOGFILE} failed. Using ${REDIRECT} instead"
+	REDIRECT=/dev/null
+	eerror "Redirection to ${LOGFILE} failed. Using ${REDIRECT} instead"
 fi
 ${QUIET} && exec >>"${REDIRECT}"
 
diff --git a/src/update-eix-remote.in b/src/update-eix-remote.in
--- a/src/update-eix-remote.in
+++ b/src/update-eix-remote.in
@@ -27,13 +27,13 @@
 
 . update-eix-functions.sh.in
 
-test -z "${OVERLAYPARENT}" && OVERLAYPARENT="/usr/portage/local"
+[ -n "${OVERLAYPARENT}" ] || OVERLAYPARENT="/usr/portage/local"
 EIXCACHESNAME="eix-caches.tbz2"
 
 Sanitize () {
 	READLINK='' NormalizeNames OVERLAYPARENT \
 		|| die '$OVERLAYPARENT must not be empty'
-	test -n "${RELATIVE}" && die '$OVERLAYPARENT must start with /'
+	[ -z "${RELATIVE}" ] || die '$OVERLAYPARENT must start with /'
 }
 Sanitize
 
@@ -98,51 +98,53 @@ declare -a SUCMD
 NEED_ARG=false
 FILENAME=''
 GetFilename () {
-	test ${#} -gt 1 && Usage 1
-	if test ${#} -lt 1; then
+	[ ${#} -gt 1 ] && Usage 1
+	if [ ${#} -lt 1 ]; then
 		${NEED_ARG} && die "Filename argument is mandatory"
 		return
 	fi
 	FILENAME="${1}"
-	test -n "${FILENAME}" || die "Filename argument must be nonempty"
-	test "${FILENAME:0:1}" = '/' || test "${FILENAME:0:1}" = '~' || \
-		FILENAME="$(pwd)/${FILENAME}"
+	[ -n "${FILENAME}" ] || die "Filename argument must be nonempty"
+	case "${FILENAME}" in
+		/*|'~'*) :;;
+		*) FILENAME="$(pwd)/${FILENAME}";;
+	esac
 }
 
 CalcSuCmd () {
 	local MY_CMD
 	MY_CMD="$(command -v "${1}")" || die "${1} cannot be found in $PATH"
 	SUCMD=("${MY_CMD}")
-	test -n "${FETCHUSER}" || test "${UID}" -ne 0 || FETCHUSER="nobody"
-	test -n "${FETCHUSER}" && \
+	[ -n "${FETCHUSER}" ] || [ "${UID}" -ne 0 ] || FETCHUSER="nobody"
+	[ -n "${FETCHUSER}" ] && \
 		SUCMD=('/bin/su' '-s' "${MY_CMD}" "${FETCHUSER}")
 }
 
 CdDir () {
-	cd "${1}" >/dev/null || die "cannot cd to ${TMPDIR}"
+	cd -- "${1}" >/dev/null || die "cannot cd to ${1}"
 }
 
 TMPDIR=''
 EXITCODE=0
 Cleanup () {
-	cd / >/dev/null;
-	if test -n "${TMPDIR}"; then
+	cd / >/dev/null
+	if [ -n "${TMPDIR}" ]; then
 		test -d "${TMPDIR}" && rm -rf -- "${TMPDIR}"
 	fi
 	TMPDIR=''
-	trap '' 0 1 2 15
+	trap - EXIT HUP INT TERM
 	exit "${EXITCODE}"
 }
 MakeTempDir () {
 	local COUNT
-	test -n "${TMPDIR}" && return
+	[ -n "${TMPDIR}" ] && return
 	if command -v mktemp >/dev/null 2>&1; then
 		TMPDIR="$(mktemp -d /tmp/${0##*/}.XXXXXX)" || \
 			die "cannot create temporary directory"
 	else
 		COUNT=0
 		while true; do
-			test ${COUNT} -eq 9999 && \
+			[ ${COUNT} -eq 9999 ] && \
 				die "found no free temp after 10000 attempts"
 			COUNT=$(( ${COUNT} + 1 ))
 			TMPDIR="/tmp/${0##*/}.$$.${RANDOM}.${RANDOM}.${RANDOM}"
@@ -151,19 +153,19 @@ MakeTempDir () {
 			break
 		done
 	fi
-	trap Cleanup 0 1 2 15
-	chmod 755 "${TMPDIR}"
-	test -n "${1}" && CdDir "${TMPDIR}"
+	trap Cleanup EXIT HUP INT TERM
+	chmod -- 755 "${TMPDIR}"
+	[ -z "${1}" ] || CdDir "${TMPDIR}"
 }
 
 TMPSUB=''
 MakeTempSub () {
-	if test -z "${TMPSUB}"; then
+	if [ -z "${TMPSUB}" ]; then
 		MakeTempDir
 		TMPSUB="${TMPDIR}/1"
-		( umask 000; mkdir "${TMPSUB}" )
+		( umask 000; mkdir -- "${TMPSUB}" )
 	fi
-	test -n "${1}" && CdDir "${TMPSUB}"
+	[ -z "${1}" ] || CdDir "${TMPSUB}"
 }
 
 TMPFILE=''
@@ -172,7 +174,7 @@ FetchTemp () {
 	SOURCE="${SOURCE}/${EIXCACHESNAME}"
 	MakeTempDir cd
 	TMPFILE="${TMPDIR}/${EIXCACHESNAME}"
-	( umask 000; >"${TMPFILE}" )
+	( umask 000; : >"${TMPFILE}" )
 	CalcSuCmd wget
 	RunCommand "Fetching ${EIXCACHESNAME}" \
 		"${SUCMD[@]}" -c "${SOURCE}" || die "could not fetch ${SOURCE}"
@@ -186,9 +188,9 @@ AddArchive () {
 	for I in *
 	do
 		NAME="${I//:/_}"
-		test "${NAME}" = "${I}" || mv -- "${I}" "${NAME}"
+		[ "${NAME}" = "${I}" ] || mv -- "${I}" "${NAME}"
 	done
-	if test -n "${OVERLAYNR}"; then
+	if [ -n "${OVERLAYNR}" ]; then
 		OVERLAYARG=":${OVERLAYNR}"
 	else
 		OVERLAYARG=''
@@ -210,12 +212,12 @@ AddArchive () {
 FetchCopy () {
 	GetFilename "${@}"
 	FetchTemp
-	test -z "${FILENAME}" && return
+	[ -z "${FILENAME}" ] && return
 	(
-		test "${UID}" -eq 0 && umask 002
+		[ "${UID}" -eq 0 ] && umask 002
 		cp --preserve=timestamps -- "${TMPFILE}" "${FILENAME}"
 	)
-	test "${UID}" -eq 0 && chown -- portage:portage "${FILENAME}"
+	[ "${UID}" -eq 0 ] && chown -- portage:portage "${FILENAME}"
 }
 
 Fetch () {
