Restore bracing in eval_gettext

diff --git a/src/eix-installed-after.in b/src/eix-installed-after.in
--- a/src/eix-installed-after.in
+++ b/src/eix-installed-after.in
@@ -24,8 +24,8 @@ eval "set -- $EIX_INSTALLED_AFTER \"\$@\""
 Usage() {
 	n=${0##*/}
 	p='@PACKAGE_STRING@'
-	eval_gettext 'Usage: $n [options] category/package[:slot]
-This is a well-commented demo script for eix ($p).
+	eval_gettext 'Usage: ${n} [options] category/package[:slot]
+This is a well-commented demo script for eix (${p}).
 It lists packages installed after (or before) the last (or first) install
 of the given package/version in an output format which is convenient
 as an argument for "emerge -1".
@@ -141,12 +141,12 @@ fi
 # With options -l or -L, we also have to parse the logfile:
 
 if [ -n "${logfile:++}" ]
-then	test -r "$logfile" || die "`eval_gettext 'cannot read $logfile'`"
+then	test -r "$logfile" || die "`eval_gettext 'cannot read ${logfile}'`"
 	epoch=`unset LC_ALL
 LC_COLLATE=C
 sed -ne "\\: Merging ($match\\:\\:.*):{s/^\([0-9]*\).*/\\1/p
 q}" "$logfile"` && [ -n "${epoch:++}" ] || die "`eval_gettext \
-		'cannot find merge of $match in $logfile'`"
+		'cannot find merge of ${match} in ${logfile}'`"
 fi
 
 # We will let eix output for each installed package (and then sort by time):
diff --git a/src/eix-remote.in b/src/eix-remote.in
--- a/src/eix-remote.in
+++ b/src/eix-remote.in
@@ -32,7 +32,7 @@ if $drop_permissions
 then	prg=./eix-drop-permissions
 	me=./eix-remote.in
 	exec "$prg" -- "$me" -K "$@"
-	die "`eval_gettext 'failed to execute $prg'`"
+	die "`eval_gettext 'failed to execute ${prg}'`"
 fi
 
 addr1='@DEFAULT_REMOTE_PATH1@'
@@ -47,14 +47,14 @@ Usage() {
 	f1=$archive1
 	f2=$archive2
 	[ -n "${f:+}" ] || f=`gettext 'temporary file'`
-	eval_gettext 'Usage: $n [options] command
-Get data from a remote database for $p.
+	eval_gettext 'Usage: ${n} [options] command
+Get data from a remote database for ${p}.
 The following commands are provided:
 
 update1 (=update) or update2:
         Fetch the eix-caches of some layman overlays, store them locally in
-        EIX_REMOTEARCHIVE1 ($f1) or
-        EIX_REMOTEARCHIVE2 ($f2),
+        EIX_REMOTEARCHIVE1 (${f1}) or
+        EIX_REMOTEARCHIVE2 (${f2}),
         respectively and add them to the eix database.
         If EIX_REMOTE1 or EIX_REMOTE2, respectively, is nonempty the output
         goes to that separate database.
@@ -95,8 +95,8 @@ The following options are available:
         Set LOCAL_LAYMAN or use option -l to override the heuristics.
 -l PATH Use PATH as LOCAL_LAYMAN
 -a ADDR Use ADDR as remote database address instead of:
-        $addr1
-        $addr2
+        ${addr1}
+        ${addr2}
 -i      Ignore all previous options (e.g. ignore EIX_REMOTE_OPTS).
 -v      Verbose (default)
 -H      Suppress status line update
@@ -190,7 +190,7 @@ fi
 CdDir() {
 	cd "$1" >/dev/null && return
 	a=$1
-	die "`eval_gettext 'cannot cd to $a'`"
+	die "`eval_gettext 'cannot cd to ${a}'`"
 }
 
 tmpdir=
@@ -243,7 +243,7 @@ The default should have been set with ./configure --remote-file'`"
 
 BugReport() {
 	printf '\n\n'
-	eval_gettext \
+	gettext \
 'Probably your eix cachefile was *not* updated successfully.
 Unless the above messages suggest another cause or you specified a
 wrong filename, the most likely cause of this is that the server uses
@@ -266,7 +266,7 @@ AddArchive() {
 	a=$1
 	CdDir "$2"
 	RunCommand "`gettext 'Unpacking data'`" tar xjf "$a" || {
-		msg=`eval_gettext 'cannot unpack $a'`
+		msg=`eval_gettext 'cannot unpack ${a}'`
 		msg=$msg`BugReport`
 		die "$msg"
 	}
@@ -299,7 +299,7 @@ AddArchive() {
 		[ -n "$l$name" ] || {
 			p=${i##*/}
 			p=${p%:*}
-			ewarn "`eval_gettext 'file $p of $a contains no overlay'`"
+			ewarn "`eval_gettext 'file ${p} of ${a} contains no overlay'`"
 			failcount=`Expr $failcount + 1`
 			continue
 		}
@@ -316,13 +316,13 @@ AddArchive() {
 	done
 	msg=
 	if [ $exitcode -ne 0 ]
-	then	msg=`eval_gettext 'could not read all eix cachefiles of $a'`
+	then	msg=`eval_gettext 'could not read all eix cachefiles of ${a}'`
 	elif ! $success
-	then	msg=`eval_gettext 'no file in $a contains an overlay'`
+	then	msg=`eval_gettext 'no file in ${a} contains an overlay'`
 	elif [ $failcount -gt 1 ]
-	then	ewarn "`eval_gettext '$failcount files in $a contain no overlay'`"
+	then	ewarn "`eval_gettext '${failcount} files in ${a} contain no overlay'`"
 	elif [ $failcount -gt 0 ]
-	then	ewarn "`eval_gettext 'A file in $a contains no overlay'`"
+	then	ewarn "`eval_gettext 'A file in ${a} contains no overlay'`"
 	fi
 	die_on_update_failure=false
 	ReadVar $eix_remote_var $eix_remote_var
@@ -330,7 +330,7 @@ AddArchive() {
 	(
 		if [ -n "${eix_remote:++}" ]
 		then	einfo "`eval_gettext \
-				'Output to remote database $eix_remote'`"
+				'Output to remote database ${eix_remote}'`"
 			AddUpdateArgs '-o' "$eix_remote"
 			umask 002
 		fi
@@ -360,7 +360,7 @@ FetchFile() {
 		return
 	fi
 	cp -p -- "$tmpfile" "$file" || die "`eval_gettext \
-		'cannot copy temporary file to $file'`"
+		'cannot copy temporary file to ${file}'`"
 }
 
 
@@ -372,7 +372,7 @@ Fetch() {
 Add() {
 	CheckTemp
 	test -r "$archive" || \
-		die "`eval_gettext 'cannot read $archive'`"
+		die "`eval_gettext 'cannot read ${archive}'`"
 	MakeTempDir
 	AddArchive "$archive" "$tmpdir"
 }
@@ -391,7 +391,7 @@ Update() {
 		tmpsup=$tmpdir
 	else	tmpsub=$tmpdir/1
 		mkdir -m 700 -- "$tmpsub" \
-			|| die "`eval_gettext 'mkdir $tmpsub failed'`"
+			|| die "`eval_gettext 'mkdir ${tmpsub} failed'`"
 	fi
 	AddArchive "$file" "$tmpsub"
 }
diff --git a/src/eix-sync.in b/src/eix-sync.in
--- a/src/eix-sync.in
+++ b/src/eix-sync.in
@@ -23,13 +23,13 @@ eixsyncconf=$local_portage_configroot/etc/eix-sync.conf
 Usage() {
 	n=${0##*/}
 	p='@PACKAGE_STRING@'
-	eval_gettext 'Usage: $n [options]
-Call layman/emerge --sync/--metadata and show updates. ($p)
+	eval_gettext 'Usage: ${n} [options]
+Call layman/emerge --sync/--metadata and show updates. (${p})
 
 Unless the -t option is used, the old database will be saved to
-    $eixprevious.
+    ${eixprevious}.
 
-The file $eixsyncconf and the eix (environment) variable EIX_SYNC_CONF
+The file ${eixsyncconf} and the eix (environment) variable EIX_SYNC_CONF
 (which defaults to delayed substitution of EIX_SYNC_OPTS) determine for
 which overlays layman is called, which default options are used, and they
 can contain various hooks - "man eix" for details.
@@ -40,7 +40,7 @@ Moreover, "--" in the default options will forbid command line options.
 The following options are available:
 
 -i   Ignore all previous options except -n
-     (useful to ignore $eixsyncconf options).
+     (useful to ignore ${eixsyncconf} options).
 -a   Always assume that some tree/overlay changes
      (set have_changed=: in a !-hook to force this)
 -s [USER@]SERVER[:DIR] Sync via rsync from SERVER.
@@ -55,11 +55,11 @@ The following options are available:
 -u   Update database only and show differences. This is equivalent to -0l@As ""
 -F   Make layman or failed hooks (! !! ~ @ @@ entries) fatal. This can be
      forced/overridden in hooks by (un)setting FATAL_HOOKS or calling die.
--l   Do not call layman (and the !commands in $eixsyncconf).
+-l   Do not call layman (and the !commands in ${eixsyncconf}).
      However, the !! lines and postponed hooks (@ and @@ entries)
      will be executed anyway.
 -A   Do not call eix-remote add1/add2
--@   Do not execute the hooks (@ and @@ entries) of $eixsyncconf.
+-@   Do not execute the hooks (@ and @@ entries) of ${eixsyncconf}.
 -S   Do not execute the hooks after emerge --sync (@ entries).
 -M   Run emerge --metadata.  You might need this when you use the cache method
      "sqlite", "sqlite*", or "flat" for PORTDIR or in a synced overlay.
@@ -80,7 +80,7 @@ The following options are available:
 -r   Clear /var/cache/edb/dep/* before syncing. This is only useful when you
      use e.g. PORTDIR_CACHE_METHOD=flat and FEATURES=metadata-transfer
      is active. (This option is not default anymore).
--R   Cancel previous -r (e.g. if it was used in $eixsyncconf).
+-R   Cancel previous -r (e.g. if it was used in ${eixsyncconf}).
 -v   Verbose: output of executed commands.
 -n   Dry run. You might want to combine this with -v. This implies -aHT
 -H   Suppress status line update.
@@ -104,7 +104,7 @@ DoExecute() {
 	do	set +f
 		! $printcmd || PrintCmd "$curr_cmd"
 		$dryrun || eval "$curr_cmd" || WarnOrDie "`eval_gettext \
-			'Something went wrong with $curr_cmd'`"
+			'Something went wrong with ${curr_cmd}'`"
 	done
 }
 
@@ -213,12 +213,12 @@ ParseConfigLine() {
 	if [ "$j" = '*' ]
 	then	MyRunCommand "`gettext 'Syncing all portage overlays'`" \
 			"$mycmd" -S "$@" \
-			|| WarnOrDie "`eval_gettext '$mycmd -S failed'`"
+			|| WarnOrDie "`eval_gettext '${mycmd} -S failed'`"
 		return
 	fi
-	MyRunCommand "`eval_gettext 'Syncing portage overlay $j'`" \
+	MyRunCommand "`eval_gettext 'Syncing portage overlay ${j}'`" \
 		"$mycmd" -s "$j" "$@" \
-		|| WarnOrDie "`eval_gettext '$mycmd -s $j failed'`"
+		|| WarnOrDie "`eval_gettext '${mycmd} -s ${j} failed'`"
 }
 
 test -r "$eixsyncconf" && haveconf=: || haveconf=false
@@ -409,9 +409,9 @@ MyVarCommand() {
 		set +f;;
 	esac
 	myvarcmd=$*
-	MyRunCommand "`eval_gettext 'Running $myvarcmd'`" \
+	MyRunCommand "`eval_gettext 'Running ${myvarcmd}'`" \
 		$myvarcmdargs "$@" \
-		|| die "`eval_gettext '$myvarcmd failed'`"
+		|| die "`eval_gettext '${myvarcmd} failed'`"
 }
 
 time_iupdate=
@@ -483,8 +483,8 @@ PrepRsync() {
 		$dryrun && continue
 		if c=`eval "$curr_cmd"`
 		then	eval "$c" || WarnOrDie "`eval_gettext \
-				'$c (output of $curr_cmd) failed'`"
-		else	WarnOrDie "`eval_gettext '$curr_cmd failed'`"
+				'${c} (output of ${curr_cmd}) failed'`"
+		else	WarnOrDie "`eval_gettext '${curr_cmd} failed'`"
 		fi
 	done
 	rsync_opts="$portage_rsync_opts $portage_rsync_extra_opts --exclude=/.unionfs"
@@ -504,9 +504,9 @@ ClearCache() {
 		set -- "$local_varcache"/var/cache/edb/dep/*;;
 	esac
 	MyRunCommand "`eval_gettext \
-	'Removing old portage-cache in $local_varcache/var/cache/edb/dep'`" \
+	'Removing old portage-cache in ${local_varcache}/var/cache/edb/dep'`" \
 		rm -rf -- "$@" || WarnOrDie "`eval_gettext \
-		'rm -rf $local_varcache/var/cache/edb/dep/* failed'`"
+		'rm -rf ${local_varcache}/var/cache/edb/dep/* failed'`"
 }
 
 CallEmergeSync() {
@@ -514,7 +514,7 @@ CallEmergeSync() {
 	then	PrepRsync "$server"
 		MyRunCommand "rsyncing from $hostdir" -t sync \
 		rsync $rsync_opts -- "$hostdir" "$local_portdir" || \
-			die "`eval_gettext 'Could not rsync from $hostdir'`"
+			die "`eval_gettext 'Could not rsync from ${hostdir}'`"
 		return
 	fi
 	$skip_sync && return
@@ -524,9 +524,9 @@ CallEmergeSync() {
 CallSyncClient() {
 	[ -z "${client:++}" ] && return
 	PrepRsync "$client"
-	MyRunCommand "`eval_gettext 'rsyncing to $hostdir'`" -t client \
+	MyRunCommand "`eval_gettext 'rsyncing to ${hostdir}'`" -t client \
 		rsync $rsync_opts -- "$local_portdir" "$hostdir" || \
-			die "`eval_gettext 'Could not rsync to $hostdir'`"
+			die "`eval_gettext 'Could not rsync to ${hostdir}'`"
 }
 
 CallEmergeMetadata() {
@@ -545,17 +545,17 @@ CondUpdate() {
 
 CopyToTemp() {
 	StatusInfo "`eval_gettext \
-		'Copying old $eixcache cache to temporary file'`"
+		'Copying old ${eixcache} cache to temporary file'`"
 	MakeTempFile
 	chmod a+r -- "$tmpfile"
 	MyRun cp -p -- "$eixcache" "$tmpfile" || die "`eval_gettext \
-		'Could not copy database to temporary file $tmpfile'`"
+		'Could not copy database to temporary file ${tmpfile}'`"
 }
 
 CopyToPrevious() {
-	StatusInfo "`eval_gettext 'Copying old database to $eixprevious'`"
+	StatusInfo "`eval_gettext 'Copying old database to ${eixprevious}'`"
 	MyRun cp -p -- "$eixcache" "$eixprevious" || die "`eval_gettext \
-		'Could not copy database to $eixprevious'`"
+		'Could not copy database to ${eixprevious}'`"
 }
 
 CopyPrevious() {
@@ -584,7 +584,7 @@ RemoteAdd() {
 		} >/dev/null 2>&1 && continue
 		StatusInfo eix-remote add$remote_num
 		MyRun eix-remote add$remote_num || WarnOrDie "`eval_gettext \
-			'eix-remote add$remote_num failed'`"
+			'eix-remote add${remote_num} failed'`"
 	done
 	return 0
 }
