Some more security care and documentation for the scripts.
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@342 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/src/eix-sync.in b/src/eix-sync.in
--- a/src/eix-sync.in
+++ b/src/eix-sync.in
@@ -38,7 +38,6 @@ GENSYNCCONF="${EPREFIX}${PORTAGE_CONFIGROOT}/etc/eix-sync.conf"
 LOGFILE="${EPREFIX}/var/log/eix-sync.log"
 PMOD="${EPREFIX}${PORTAGE_CONFIGROOT}/etc/portage/modules"
 MODULENAME='cache.metadata_overlay.database'
-PORTAGECACHE="${EPREFIX}/var/cache/edb/dep"
 
 Usage () {
   echo "${0##*/} [options]
@@ -84,16 +83,21 @@ The following options are available:
 -W   Run emerge-delta-webrsync instead of emerge --sync.
 -c CMD Run CMD instead of emerge --sync.
 -C OPT Add OPT to the emerge --sync command (or whatever is used instead).
--r   Really recreate the dep-cache (rm -rf ${PORTAGECACHE}/*) (default).
+-r   Really recreate the dep-cache (rm -rf /var/cache/edb/dep/*) (default).
 -R   Do not really recreate the dep-cache.
 -h   Show this text and exit."
+  [[ "${EPREFIX}" ]] && echo "
+Currently EPREFIX=${EPREFIX} is active which means:
+1. ${EPREFIX} is used as a prefix for all paths
+   (except \$PORTDIR for -s and -2)
+2. It is assumed that you need not be root to execute anything"
   EXITCODE="${1}"
   exit ${1}
 }
 
 DiffOnly() {
   [[ -e "${EIXPREVIOUS}" ]] || die "No previous database ${EIXPREVIOUS} exists"
-  exec diff-eix "${EIXPREVIOUS}"
+  exec diff-eix -- "${EIXPREVIOUS}"
   die "Could not execute diff-eix"
 }
 
@@ -252,7 +256,7 @@ SED2="[[:space:]]*=[[:space:]]*\([^[:space:]]*\)[[:space:]]*\$!\1!p"
 SedFor () {
   local A=''
   [[ -e "${2}" ]] && \
-    A="$(sed -n -e "${SED1}${1}${SED2}" "${2}" | tail -n 1)"
+    A="$(sed -n -e "${SED1}${1}${SED2}" -- "${2}" | tail -n 1)"
   A="${A%\"}"
   A="${A#\"}"
   A="${A%'}"
@@ -312,8 +316,9 @@ ClearCache () {
   # Cleaning old cache
   # portage 2.1_pre1 doesn't do this anymore, so *we* need to do it.
   RootTest
-  MyRunCommand "Removing old portage-cache in ${PORTAGECACHE}/*" \
-    rm -rf -- "${PORTAGECACHE}"/* || die "rm -rf ${PORTAGECACHE}/* failed"
+  MyRunCommand "Removing old portage-cache in ${EPREFIX}/var/cache/edb/dep" \
+    rm -rf -- "${EPREFIX}"/var/cache/edb/dep/* || \
+      die "rm -rf ${EPREFIX}/var/cache/edb/dep/* failed"
 }
 
 CallEmergeSync () {
@@ -336,7 +341,7 @@ CallSyncClient () {
   [[ "${CLIENT}" ]] || return
   PrepRsync "${CLIENT}"
   MyRunCommand "rsyncing to ${HOSTDIR}" \
-    rsync $RSYNC_OPTS "${PORTDIR}" "${HOSTDIR}" || \
+    rsync ${RSYNC_OPTS} "${PORTDIR}" "${HOSTDIR}" || \
       die "Could not rsync to ${HOSTDIR}"
 }
 
@@ -379,7 +384,7 @@ CopyPrevious () {
   [[ "${DOUPDATE}" ]] || return
   [[ "${EMULATEMODE}" ]] && return
   MakeTempFile
-  ( umask 002 ; cp "${EIXCACHE}" "${TMPFILE}" ) ||
+  ( umask 002 ; cp -- "${EIXCACHE}" "${TMPFILE}" ) ||
     die "Could not copy database to temporary file ${TMPFILE}"
 }
 
@@ -387,7 +392,7 @@ MovePrevious () {
   [[ "${USETEMP}" ]] && return
   ( umask 002
     MyRunCommand "Copying old ${EIXCACHE} cache to ${EIXPREVIOUS}" \
-      mv -f "${TMPFILE}" "${EIXPREVIOUS}" ) ||
+      mv -f -- "${TMPFILE}" "${EIXPREVIOUS}" ) ||
       die "Could not move ${TMPFILE} to ${EIXPREVIOUS}"
   [[ "${UID}" -eq 0 ]] && chown -- "portage:portage" "${EIXPREVIOUS}" &>/dev/null
   chmod -- 664 "${EIXPREVIOUS}" &>/dev/null
@@ -413,7 +418,7 @@ UpdateDiff () {
       die "Failure while running update-eix"
   fi
   DoHook "${AFTER_UPDATE[@]}"
-  diff-eix "${D}" || die "Failed to diff against current cache"
+  diff-eix -- "${D}" || die "Failed to diff against current cache"
 }
 
 MainSync () {
@@ -440,7 +445,8 @@ if (
      umask 002
      if [[ "${QUIET}" || -z "${VERBOSE}" ]]; then
        >"${LOGFILE}" || exit 1
-       [[ "${UID}" -eq 0 ]] && chown -- "portage:portage" "${LOGFILE}" &>/dev/null
+       [[ "${UID}" -eq 0 ]] && \
+         chown -- "portage:portage" "${LOGFILE}" &>/dev/null
      fi
      exit 0
    ) &>/dev/null
