eix-sync: Much more customization. update-eix-remote: Minor bugfixes and cleanups.
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@235 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/src/eix-sync.in b/src/eix-sync.in
--- a/src/eix-sync.in
+++ b/src/eix-sync.in
@@ -1,5 +1,6 @@
 #!/bin/bash
-# Author: Emil Beinroth <emilbeinroth@gmx.net>
+# Authors: Emil Beinroth <emilbeinroth@gmx.net>
+#          Martin Väth <vaeth@mathematik.uni-wuerzburg.de>
 
 ###########################################################################
 #   eix is a small utility for searching ebuilds in the                   #
@@ -31,106 +32,355 @@
 
 source /sbin/functions.sh
 
+EIXCACHE="@EIX_CACHEFILE@"
+EIXPREVIOUS="${EIXCACHE%/*}/eix.previous"
+GENSYNCCONF="/etc/eix-sync.conf"
+LOGFILE="/var/log/eix-sync.log"
+PMOD='/etc/portage/modules'
+MODULENAME='cache.metadata_overlay.database'
+PORTDIR="$(portageq portdir)" || PORTDIR="/usr/portage"
+
 # print message and die a horrible death
-function die() {
-  eerror "$@"
-  exit 1
+die () {
+  eerror "${*}"; EXITCODE=2; exit "${EXITCODE}"
 }
 
-# Run command -- if be_verbose=false, redirect 1,2 to /dev/null and use ebegin/eend (instead of einfo)
-function run_command() {
-  if ${be_verbose}; then
-    einfo "${1}"
-    shift 1
-    eval "${@}"
-    return "${?}"
-  else
-    ebegin "${1}"
-    shift 1
-    eval "${@}" 2>&1 >> /var/log/eix-sync.log
-    ret=${?}
-    eend ${ret} "Problems running ${@}"
-    return "${ret}"
-  fi
+Usage () {
+  echo "${0##*/} [options]
+Call gensync/emerge --sync/--metadata and/or show updates. (@PACKAGE_STRING@)
+
+Unless the -v option is used, the output of most commands is redirected to
+    ${LOGFILE}.
+Unless the -t option is used, the old database will be saved to
+    ${EIXPREVIOUS}.
+
+The file ${GENSYNCCONF} determines for which overlays gensync is called.
+You can also add certain hooks in that file - \"man eix\" for details.
+
+The following options are available:
+
+-d   Only show differences to the previously saved database and exit.
+     This is equivalent to diff-eix ${EIXPREVIOUS}.
+-s [user@]SERVER Sync via rsync from SERVER. This option implies -m.
+-2 [user@]CLIENT Sync via rsync *to* CLIENT after successfull syncing;
+     you should later call eix-sync -u locally on CLIENT.
+     If you already have synced you might want to combine this option with -uU.
+-U   Do not touch the database and omit the hooks after update-eix (@ entries)
+     and do not show differences. This option implies -R
+-u   Update database only and show differences. This is equivalent to -g@m.
+-g   Do not call gensync (and the !commands in ${GENSYNCCONF}).
+     However, the postponed hooks (@ and @@ entries) will be executed anyway.
+-@   Do not execute the hooks (@ and @@ entries) of ${GENSYNCCONF}.
+-S   Do not execute the hooks after emerge --sync (@@ entries).
+-m   Run emerge --metadata instead of emerge --sync.
+     emerge --metadata is skipped if you use portage's metadata overlay module
+     or if option -U is used.
+-t   Use temporary file to save the current database (-d will not be possible).
+-v   Don't suppress output of update-eix and emerge.
+-q   Be quiet (close stdout).
+-w   Run emerge-webrsync instead of emerge --sync.
+-r   Really recreate the dep-cache (rm -rf /var/cache/edb/dep/*) (default).
+-R   Do not really recreate the dep-cache."
+  EXITCODE="${1}"
+  exit ${1}
 }
 
-function print_version() {
-  cat<<END
-$(basename "${0}") [options] - Call 'emerge --sync/--metadata' and show updates. (@PACKAGE_STRING@)
--h   Show this extremely useful text
--v   Don't suppress output of update-eix and emerge
--q   Be quiet (close stdout)
--m   Run emerge --metadata instead of emerge --sync
--r   Really recreate the dep-cache (rm -fr /var/cache/edb/dep/*)
--w   Run emerge-webrsync instead of emerge --sync
-END
+DiffOnly() {
+  [[ -e "${EIXPREVIOUS}" ]] || die "No previous database ${EIXPREVIOUS} exists"
+  exec diff-eix "${EIXPREVIOUS}"
+  die "Could not execute diff-eix"
 }
 
 # Get options from cli
-recreate_cache=false
-be_verbose=false
-emerge_cmd="emerge --sync"
-while getopts "hvqmrw" option; do
-  case "${option}" in
-    h ) print_version
-        exit 0
-    ;;
-    v ) be_verbose=true
-    ;;
-    q ) exec >> /var/log/eix-sync.log
-    ;;
-    m ) emerge_cmd="emerge --metadata"
-    ;;
-    r ) recreate_cache=true
-    ;;
-    w ) emerge_cmd="emerge-webrsync"
-    ;;
-    * ) print_version
-        exit 1
-    ;;
+declare -a EMERGECMD
+EMERGECMD=("emerge" "--sync")
+CLEARCACHE=1
+NOGENSYNC=''
+NOHOOKS=''
+VERBOSE=''
+QUIET=''
+USETEMP=''
+METADATA=''
+SERVER=''
+CLIENT=''
+DOUPDATE='1'
+SYNCHOOKS='1'
+while getopts "ds:2:Uug@SmtvqwrR?hH" OPTION; do
+  case "${OPTION}" in
+    d) DiffOnly;;
+    s) SERVER="${OPTARG}";;
+    2) CLIENT="${OPTARG}";;
+    U) DOUPDATE='';;
+    u) NOGENSYNC=1; NOHOOKS=1; METADATA=1;;
+    g) NOGENSYNC=1;;
+    @) NOHOOKS=1;;
+    S) SYNCHOOKS='';;
+    m) METADATA=1;;
+    t) USETEMP=1;;
+    v) VERBOSE=1;;
+    q) QUIET=1;;
+    w) EMERGECMD=("emerge-webrsync");;
+    r) CLEARCACHE=1;;
+    R) CLEARCACHE='';;
+    *) Usage 1;;
   esac
 done
+[[ "${DOUPDATE}" ]] && CLEARCACHE=''
+[[ "${SERVER}" ]] && METADATA=1
 
-# Check rootness
-[ "$UID" -eq 0 ] || die "You need to be root."
+# Run command
+# if VERBOSE is empty, redirect 1,2 to /dev/null and use ebegin/eend
+# (instead of einfo)
+RunCommand () {
+  local RET
+  [[ "${EMULATEMODE}" ]] && return 0
+  if [[ "${VERBOSE}" ]]; then
+    einfo "${1}"
+    shift
+    "${@}"
+    return "${?}"
+  fi
+  ebegin "${1}"
+  shift
+  "${@}" &>"${REDIRECT}"
+  RET="${?}"
+  eend "${RET}" "Problems running ${@}"
+  return "${RET}"
+}
 
-# If the cache-file doesn't exists, or uses an obsolete format, we create it.
-if [ ! -f "/var/cache/eix" ] || ! eix --is-current; then
-  run_command "eix-cache doesn't exist or uses obsolete format. Running update-eix!"  "update-eix" || exit 1 
+DoExecute () {
+  [[ "${EMULATEMODE}" ]] && return 0
+  (
+    for CURRENT_COMMAND; do
+      RunCommand "Executing ${CURRENT_COMMAND}" \
+        eval "${CURRENT_COMMAND}" ||
+          die "Something went wrong with ${CURRENT_COMMAND}"
+    done
+  ) || die
+}
+
+DoHook () {
+  [[ "${NOHOOKS}" ]] && return 0
+  DoExecute "${@}"
+}
+
+RootTest () {
+  [[ "${UID}" -eq 0 ]] || die "You need to be root."
+}
+
+RootCommand () {
+  RootTest
+  RunCommand "${@}"
+}
+
+SED1='s!^[[:space:]]*'
+SED2="[[:space:]]*=[[:space:]]*\([^[:space:]]*\)[[:space:]]*\$!\1!p"
+SedFor () {
+  local A=''
+  [[ -e "${2}" ]] && \
+    A="$(sed -n -e "${SED1}${1}${SED2}" "${2}" | tail -n 1)"
+  A="${A%\"}"
+  A="${A#\"}"
+  A="${A%'}"
+  A="${A#'}"
+  echo "${A}"
+}
+
+TMPFILE=''
+EXITCODE=0
+DelTemp () {
+  [[ "${TMPFILE}" ]] && rm -f "${TMPFILE}"
+  trap '' 0 1 2 15
+  exit ${EXITCODE}
+}
+MakeTempFile () {
+  if type mktemp &>/dev/null; then
+    TMPFILE="$(mktemp /tmp/${0##*/}.XXXXXX)" ||
+      die "cannot create temporary file"
+  else
+    TMPFILE="/tmp/${0##*/}.$$"
+    [[ -e "${TMPFILE}" ]] && \
+      die "temporary name ${TMPFILE} already exists"
+    mkdir "${TMPFILE}" || die "cannot create ${TMPFILE}"
+  fi
+  trap DelTemp 0 1 2 15
+}
+
+declare -a AFTER_SYNC AFTER_UPDATE BEFORE_RSYNC
+AFTER_SYNC=()
+AFTER_UPDATE=()
+BEFORE_RSYNC=()
+if [[ -r "${GENSYNCCONF}" ]]; then
+  HAVECONF=1
+else
+  HAVECONF=''
 fi
+CallGensync () {
+  local I J MYCMD
+  [[ "${HAVECONF}" ]] || return
+  while read I; do
+    J="${I%%#*}"
+    while [[ "${J% }" != "${J}" ]]; do J="${J%?}"; done
+    while [[ "${J:0:1}" = " " ]]; do J="${J#?}"; done
+    [[ "${J}" ]] || continue
+    case "${J}" in
+      !*)  J="${J#?}"; MYCMD='!';;
+      @@*) J="${J#??}"; MYCMD='@@';;
+      @*)  J="${J#?}"; MYCMD='@';;
+      \~*)  J="${J#?}"; MYCMD='~';;
+      *)   MYCMD="gensync";;
+    esac
+    [[ "${EMULATEMODE}" ]] && continue
+    case "${MYCMD}" in
+      @@) AFTER_UPDATE[${#AFTER_UPDATE[@]}]="${J}"; continue;;
+      @)  AFTER_SYNC[${#AFTER_SYNC[@]}]="${J}"; continue;;
+      \~)  BEFORE_RSYNC[${#BEFORE_RSYNC[@]}]="${J}"; continue;;
+      !)  [[ "${NOGENSYNC}" ]] || DoExecute "${J}"; continue;;
+    esac
+    [[ "${NOGENSYNC}" ]] && continue
+    if [[ "${J}" = "*" ]]; then
+      RootCommand "Syncing all portage overlays"
+        "${MYCMD}" -a || die "${MYCMD} -a failed"
+      continue;
+    fi
+    RootCommand "Syncing portage overlay '${J}'"
+      "${MYCMD}" "${J}" || die "${MYCMD} ${J} failed"
+  done <"${GENSYNCCONF}"
+}
 
-# Clean out eix-sync.log:
-echo > /var/log/eix-sync.log
+PREPRSYNC=''
+PrepRsync () {
+  local CURRENT_COMMAND PORTAGE_RSYNC_OPTS PORTAGE_RSYNC_EXTRA_OPTS
+  [[ "${PREPRSYNC}" ]] && return
+  PORTDIR="$(portageq portdir)" || PORTDIR="/usr/portage"
+  PORTDIR_CLIENT="${PORTDIR}"
+  PORTDIR_SERVER="${PORTDIR}"
+  PORTAGE_RSYNC_OPTS="$(portageq envvar PORTAGE_RSYNC_OPTS)"
+  PORTAGE_RSYNC_EXTRA_OPTS="$(portageq envvar PORTAGE_RSYNC_EXTRA_OPTS)"
+  for CURRENT_COMMAND in "${BEFORE_RSYNC[@]}"; do
+    eval "$(eval "${CURRENT_COMMAND}")" || die "${CURRENT_COMMAND} failed"
+  done
+  RSYNC_OPTS="${PORTAGE_RSYNC_OPTS} ${PORTAGE_RSYNC_EXTRA_OPTS}"
+  PREPRSYNC=1
+}
 
-if ${recreate_cache}; then
+ClearCache () {
+  [[ "${CLEARCACHE}" ]] || return
   # Cleaning old cache
   # portage 2.1_pre1 doesn't do this anymore, so *we* need to do it.
-  run_command "Removing old portage-cache in /var/cache/edb/dep/*" "rm -fr /var/cache/edb/dep/*" || exit 1
-fi
+  RootCommand "Removing old portage-cache in /var/cache/edb/dep/*" \
+    rm -rf /var/cache/edb/dep/* || die "rm -rf /var/cache/edb/dep/* failed"
+}
 
-# Update tree and overlays
-run_command "Running ${emerge_cmd}" "${emerge_cmd}" || exit 1
+CallEmergeSync () {
+  [[ "${EMULATEMODE}" ]] && return
+  if [[ "${SERVER}" ]]; then
+    PrepRsync
+    RunCommand "rsyncing from ${SERVER}" \
+      rsync $RSYNC_OPTS "${SERVER}:${PORTDIR_SERVER}/" "${PORTDIR}" || \
+        die "Could not rsync from ${SERVER}:${PORTDIR_SERVER}"
+  fi
+  [[ "${METADATA}" ]] && return
+  RootCommand "Running ${EMERGECMD[*]}" \
+    "${EMERGECMD[@]}" || die "${EMERGECMD[*]} failed"
+}
 
-if [ -e "/etc/eix-sync-overlays" ]; then
-  while read i; do
-    i=${i%%#*}
-    if [ "$i" ]; then
-      if [ "$i" = "*" ]; then
-        run_command "Syncing all portage overlays" gensync -a   || exit 1
-      else
-        run_command "Syncing portage overlay '$i'" gensync "$i" || exit 1
-      fi
+CallSyncClient () {
+  [[ "${EMULATEMODE}" ]] && return
+  [[ "${CLIENT}" ]] || return
+  PrepRsync
+  RunCommand "rsyncing to ${CLIENT}" \
+    rsync $RSYNC_OPTS "${PORTDIR}" "${CLIENT}:${PORTDIR_CLIENT}/" || \
+      die "Could not rsync to ${CLIENT}:${PORTDIR_CLIENT}"
+}
+
+TESTRESULT=''
+CallEmergeMetadata () {
+  [[ "${DOUPDATE}" && "${METADATA}" ]] || return
+  if [[ -z "${TESTRESULT}" ]]; then
+    if [[ "$(SedFor 'portdbapi.auxdbmodule' "${PMOD}")" = "${MODULENAME}" ]]
+    then
+      TESTRESULT=0
+    else
+      TESTRESULT=1
     fi
-  done < /etc/eix-sync-overlays
+  fi
+  if [[ "${TESTRESULT}" -eq 0 ]]; then
+    [[ "${EMULATEMODE}" ]] || \
+      einfo "emerge --metadata is skipped due to settings in ${PMOD}"
+    return
+  fi
+  RootCommand "Running emerge --metadata" \
+    emerge --metadata || die "emerge --metadata failed"
+}
+
+CondUpdate () {
+  if [[ ! -f "/var/cache/eix" ]]; then
+    RootCommand "eix-cache doesn't exist. Running update-eix!" \
+        update-eix || die "update-eix failed"
+    return
+  fi
+  [[ "${EMULATEMODE}" ]] && return
+  if ! eix --is-current; then
+    RunCommand "eix-cache uses obsolete format. Running update-eix!" \
+        update-eix || die "update-eix failed"
+  fi
+}
+
+CopyDiff () {
+  local D
+  [[ "${DOUPDATE}" ]] || return
+  if [[ "${USETEMP}" ]]; then
+    [[ "${EMULATEMODE}" ]] && return
+    MakeTempFile
+    D="${TMPFILE}"
+  else
+    D="${EIXPREVIOUS}"
+    [[ -e "${D}" ]] || RootTest
+    [[ "${EMULATEMODE}" ]] && return
+  fi
+  ( umask 002 ; cp "${EIXCACHE}" "${D}" ) ||
+    die "Could not copy database to ${D}"
+  RunCommand "Running update-eix" "update-eix" || \
+    die "Failure while running update-eix"
+  DoHook "${AFTER_UPDATE[@]}"
+  diff-eix "${D}" || die "Failed to diff against current cache"
+}
+
+MainSync () {
+  CondUpdate
+  ClearCache
+  CallGensync
+  CallEmergeSync
+  [[ "${SYNCHOOKS}" ]] && DoHook "${AFTER_SYNC[@]}"
+  CallSyncClient
+  CallEmergeMetadata
+  CopyDiff
+}
+
+if [[ "${UID}" -ne 0 ]]; then
+# Emulate everything to check whether we have to be root:
+  EMULATEMODE=1
+  MainSync
 fi
+EMULATEMODE=''
 
-# Copy cache, create new cache and diff
-tmpfile=$(mktemp /tmp/eix.XXXXXX)
-cp "/var/cache/eix" ${tmpfile} || die "Failed to create temporary cache file"
-run_command "Running update-eix" "update-eix" || exit 1 
-diff-eix ${tmpfile} || die "Failed to diff against current cache"
-rm -f ${tmpfile} || die "Failed to remove ${tmpfile}"
+# Clean out logfile and redirect
+if (
+     umask 002
+     if [[ "${QUIET}" || -z "${VERBOSE}" ]]; then
+       >"${LOGFILE}"
+     fi
+   ) &>/dev/null
+then
+  [[ "${UID}" -eq 0 ]] && chown portage:portage "${LOGFILE}"
+  REDIRECT="${LOGFILE}"
+else
+  REDIRECT=/dev/null
+  eerror "Redirection to ${LOGFILE} failed. Using ${REDIRECT} instead"
+fi
+[[ "${QUIET}" ]] && exec >>"${REDIRECT}"
 
-exit 0 # Goodbye
+MainSync
 
-# vim:set expandtab sw=2 ts=4:
+exit 0
diff --git a/src/update-eix-remote.in b/src/update-eix-remote.in
--- a/src/update-eix-remote.in
+++ b/src/update-eix-remote.in
@@ -26,20 +26,26 @@
 ###########################################################################
 
 source /sbin/functions.sh
-die () { eerror "${*}"; exit 2; }
+
+die () {
+	eerror "${*}"
+	EXITCODE=2
+	exit "${EXITCODE}"
+}
+
 type portageq &>/dev/null || die 'portageq is required for this script'
 
 [[ "${OVERLAYPARENT}" ]] || OVERLAYPARENT="/usr/portage/local"
 EIXCACHESNAME="eix-caches.tbz2"
 
 Sanitize () {
-	[[ "${OVERLAYPARENT}" != "${OVERLAYPARENT#/}" ]] || \
+	[[ "${OVERLAYPARENT:0:1}" = '/' ]] || \
 		die '$OVERLAYPARENT must start with /'
+	while [[ "${OVERLAYPARENT:0:1}" = '/' ]]; do
+		OVERLAYPARENT="${OVERLAYPARENT%/}"
+	done
 	while [[ "${OVERLAYPARENT}" != "${OVERLAYPARENT#/}" ]]; do
 		OVERLAYPARENT="${OVERLAYPARENT#/}"
-	done
-	while [[ "${OVERLAYPARENT}" != "${OVERLAYPARENT%/}" ]]; do
-		OVERLAYPARENT="${OVERLAYPARENT%/}"
 	done
 	OVERLAYPARENT="/${OVERLAYPARENT}"
 }
@@ -75,7 +81,8 @@ Options:
 	-o PATH	Use PATH as \$OVERLAYPARENT
 	-v	Verbose (default)
 	-q	Quiet"
-	exit ${1}
+	EXITCODE="${1}"
+	exit "${EXITCODE}"
 }
 
 VERBOSE=1
@@ -127,8 +134,8 @@ RunCommand() {
 	shift
 	"${@}" &>/dev/null
 	RET=${?}
-	eend ${ret} "Problems running ${@}"
-	return "${ret}"
+	eend ${RET} "Problems running ${@}"
+	return "${RET}"
 }
 
 CdDir () {
@@ -136,22 +143,23 @@ CdDir () {
 }
 
 TMPDIR=''
+EXITCODE=0
 Cleanup () {
-	local RET="${?}"
 	cd / >/dev/null;
 	if [[ "${TMPDIR}" ]]; then
 		[[ -d "${TMPDIR}" ]] && rm -rf "${TMPDIR}"
 	fi
 	TMPDIR=''
 	trap '' 0 1 2 15
-	exit "${RET}"
+	exit "${EXITCODE}"
 }
 MakeTempDir () {
 	[[ "${TMPDIR}" ]] && return
 	if type mktemp &>/dev/null; then
-		TMPDIR="$(mktemp -d /tmp/eix.XXXXXX)"
+		TMPDIR="$(mktemp -d /tmp/${0##*/}.XXXXXX)" || \
+			die "cannot create temporary directory"
 	else
-		TMPDIR="/tmp/eix.$$"
+		TMPDIR="/tmp/${0##*/}.$$"
 		[[ -e "${TMPDIR}" ]] && \
 			die "temporary name ${TMPDIR} already exists"
 		mkdir "${TMPDIR}" || die "cannot create "${TMPDIR}
@@ -296,3 +304,4 @@ case "${MAIN_COMMAND}" in
 	*)               Usage 1;;
 esac
 
+exit 0
