Remove redundant sh quoting

diff --git a/src/eix-functions.sh.in b/src/eix-functions.sh.in
--- a/src/eix-functions.sh.in
+++ b/src/eix-functions.sh.in
@@ -20,14 +20,14 @@ ReadFunctions() {
 
 : ${read_var_prg:=eix-update}
 ReadVar() {
-	eval "[ -n \"\${${2}++}\" ] && ${1}=\${${2}}" && return
-	eixf_read=`PRINT_APPEND=X "${3:-${read_var_prg}}" --print "${2}"` || \
+	eval "[ -n \"\${$2++}\" ] && $1=\$$2" && return
+	eixf_read=`PRINT_APPEND=X "${3:-$read_var_prg}" --print "$2"` || \
 		return
-	eval ${1}=\${eixf_read%X}
+	eval $1=\${eixf_read%X}
 }
 
 ReadBoolean() {
-	case `PRINT_APPEND=n "${2:-${read_var_prg}}" --print "${1}"` in
+	case `PRINT_APPEND=n "${2:-$read_var_prg}" --print "$1"` in
 	[nNfF]*|[oO][fF]*)	return 1;;
 	esac
 	return 0
@@ -35,7 +35,7 @@ ReadBoolean() {
 
 eixf_know_colors=false
 SetColors() {
-	${eixf_know_colors} && return
+	$eixf_know_colors && return
 	eixf_know_colors=:
 	ReadBoolean NOCOLORS && return
 	! test -t 1 && ! ReadBoolean FORCE_USECOLORS && return
@@ -46,10 +46,10 @@ SetColors() {
 }
 
 StartInList() (
-	ReadVar startlist ${2} || return
-	for start in ${startlist}
-	do	case ${1} in
-		"${start}"*)	return 0;;
+	ReadVar startlist $2 || return
+	for start in $startlist
+	do	case $1 in
+		"$start"*)	return 0;;
 		esac
 	done
 	return 1
@@ -63,107 +63,107 @@ EixfStatusmode() {
 	if [ -z "${statusline:++}" ]
 	then	! ReadBoolean NOSTATUSLINE && {
 			test -t 1 && ReadVar TERM TERM && \
-				StartInList "${TERM}" TERM_STATUSLINE \
+				StartInList "$TERM" TERM_STATUSLINE \
 			|| ReadBoolean FORCE_STATUSLINE
 		}
-	else	${statusline}
+	else	$statusline
 	fi && eixf_statusline=: \
 	&& if ReadVar TERM TERM && \
-		StartInList "${TERM}" TERM_SOFTSTATUSLINE
+		StartInList "$TERM" TERM_SOFTSTATUSLINE
 	then	eixf_softstatus=:
 	else	eixf_softstatus=false
 	fi
-	eixf_statusmode=${eixf_statusline}
-	${eixf_statusmode}
+	eixf_statusmode=$eixf_statusline
+	$eixf_statusmode
 }
 
 StatuslinePlain() {
-	${eixf_statusmode} || return 0
-	! ${eixf_softstatus} || printf '\033k%s\033\\' "${*}"
-	printf '\033]0;%s\007' "${*}"
+	$eixf_statusmode || return 0
+	! $eixf_softstatus || printf '\033k%s\033\\' "$*"
+	printf '\033]0;%s\007' "$*"
 }
 
 Statusline() {
-	StatuslinePlain "${0##*/}: ${*}"
+	StatuslinePlain "${0##*/}: $*"
 }
 
 verbose=:
 StatusInfo() {
-	Statusline "${*}"
-	! ${verbose} || einfo "${*}"
+	Statusline "$*"
+	! $verbose || einfo "$*"
 }
 
 Exit() {
-	eixf_exit=${1:-${?}}
-	${eixf_statusline} || exit ${eixf_exit}
+	eixf_exit=${1:-$?}
+	$eixf_statusline || exit $eixf_exit
 	ReadVar EXIT_STATUSLINE EXIT_STATUSLINE
 	if [ -n "${EXIT_STATUSLINE:++}" ]
 	then	StatuslinePlain "${EXIT_STATUSLINE# }"
-	elif [ ${eixf_exit} -eq 0 ]
+	elif [ $eixf_exit -eq 0 ]
 	then	Statusline "`gettext 'Finished'`"
 	else	Statusline "`gettext 'Failure'`"
 	fi
-	exit ${eixf_exit}
+	exit $eixf_exit
 }
 
 Echo() {
-	printf '%s\n' "${@}"
+	printf '%s\n' "$@"
 }
 
 eerror() {
-	eixf_eerror=${?}
+	eixf_eerror=$?
 	SetColors
-	printf " ${eixf_bad}%s${eixf_normal} %s\n" '*' "${*}" >&2
-	return ${eixf_eerror}
+	printf " $eixf_bad%s$eixf_normal %s\n" '*' "$*" >&2
+	return $eixf_eerror
 }
 
 einfo() {
 	SetColors
-	printf " ${eixf_good}%s${eixf_normal} %s\n" '*' "${*}"
+	printf " $eixf_good%s$eixf_normal %s\n" '*' "$*"
 }
 
 ewarn() {
 	SetColors
-	printf " ${eixf_warn}%s${eixf_normal} %s\n" '*' "${*}" >&2
+	printf " $eixf_warn%s$eixf_normal %s\n" '*' "$*" >&2
 }
 
 ebegin() {
 	SetColors
-	printf " ${eixf_good}%s${eixf_normal} %s%s\n" '*' "${*}" '...'
+	printf " $eixf_good%s$eixf_normal %s%s\n" '*' "$*" '...'
 }
 
 eend() {
-	[ ${1} -eq 0 ] && return
-	eixf_eerror=${1}
+	[ $1 -eq 0 ] && return
+	eixf_eerror=$1
 	shift
 	SetColors
-	printf " ${eixf_bad}%s${eixf_normal} %s\n" '*' "${*}" >&2
-	return ${eixf_eerror}
+	printf " $eixf_bad%s$eixf_normal %s\n" '*' "$*" >&2
+	return $eixf_eerror
 }
 
 die() {
-	[ ${#} -eq 0 ] || eerror "${*}"
+	[ $# -eq 0 ] || eerror "$*"
 	exitcode=2
-	Exit ${exitcode}
+	Exit $exitcode
 }
 
 PerLine() {
 	while IFS='
 ' read -r eixf_line
-	do	"${@}" "${eixf_line}"
+	do	"$@" "$eixf_line"
 	done
 }
 
 PerLineArg() {
-	eixf_perline=${1}
+	eixf_perline=$1
 	shift
-	eixf_ifs=${IFS}
+	eixf_ifs=$IFS
 	IFS='
 '
-	for eixf_line in ${eixf_perline}
-	do	"${@}" "${eixf_line}"
+	for eixf_line in $eixf_perline
+	do	"$@" "$eixf_line"
 	done
-	IFS=${eixf_ifs}
+	IFS=$eixf_ifs
 }
 
 unset local_portdir
@@ -173,28 +173,28 @@ GetPortdir() {
 
 verbose=:
 RunCommand() {
-	Statusline "${1}"
-	if ${verbose}
-	then	einfo "${1}"
+	Statusline "$1"
+	if $verbose
+	then	einfo "$1"
 		shift
-		"${@}"
-		return ${?}
+		"$@"
+		return $?
 	fi
-	ebegin "${1}"
+	ebegin "$1"
 	shift
-	"${@}" >/dev/null
-	eixf_ret=${?}
-	eixf_cmd=${*}
-	eend ${eixf_ret} "`eval_gettext 'Problems running ${eixf_cmd}'`"
-	return ${eixf_ret}
+	"$@" >/dev/null
+	eixf_ret=$?
+	eixf_cmd=$*
+	eend $eixf_ret "`eval_gettext 'Problems running $eixf_cmd'`"
+	return $eixf_ret
 }
 
 if ( eval '[ "$(( 0 + 1 ))" = 1 ]' ) >/dev/null 2>&1
 then	eval 'Expr() {
-	printf "%s" "$(( ${1} ${2} ${3} ))"
+	printf "%s" "$(( $1 $2 $3 ))"
 }'
 else	Expr() {
-	expr "${@}"
+	expr "$@"
 }
 fi
 
@@ -206,99 +206,99 @@ fi
 Replace() {
 	eixf_repla=
 	eixf_replc='break'
-	case ${1} in
+	case $1 in
 	-*)	eixf_replc=
 		shift;;
 	esac
 	replace_count=
-	eval replace_tail=\${${1}}
+	eval replace_tail=\$$1
 	while {
-		eixf_replb=${replace_tail%%"${2}"*}
-		[ "${eixf_replb}" != "${replace_tail}" ]
+		eixf_replb=${replace_tail%%"$2"*}
+		[ "$eixf_replb" != "$replace_tail" ]
 	}
-	do	eixf_repla=${eixf_repla}${eixf_replb}${3}
-		replace_tail=${replace_tail#*"${2}"}
+	do	eixf_repla=$eixf_repla$eixf_replb$3
+		replace_tail=${replace_tail#*"$2"}
 		replace_count=${replace_count}x
-		${eixf_replc}
+		$eixf_replc
 	done
-	eval ${1}=\${eixf_repla}\${replace_tail}
+	eval $1=\$eixf_repla\$replace_tail
 	[ -n "${replace_count:++}" ]
 }
 
 Push() {
 # Rely on the existence of push.sh from https://github.com/vaeth/push/
 	. push.sh
-	Push "${@}"
+	Push "$@"
 }
 
 # PushEscaped [-c] VAR Arg [name of IFS type variable]
 # Similarly as Push, but splits Arg before at *unescaped* symbols of $IFS.
 # The name IFS can be changed if a third (resp. fourth) argument is given.
 PushEscaped() {
-	case ${1} in
+	case $1 in
 	-*)	shift
-		eval ${1}=;;
+		eval $1=;;
 	esac
-	if [ ${#} -lt 3 ] || [ -z "${3:++}" ]
+	if [ $# -lt 3 ] || [ -z "${3:++}" ]
 	then	eixf_pes='IFS'
-	else	eixf_pes=${3}
+	else	eixf_pes=$3
 	fi
-	eixf_pea=${2}
+	eixf_pea=$2
 	eixf_pew=
 	while [ -n "${eixf_pea:++}" ]
-	do	eval "eixf_pex=\${eixf_pea%%[\${${eixf_pes}}]*}"
-		if [ "${eixf_pex}" != "${eixf_pea}" ]
-		then	eixf_pec=${eixf_pea#"${eixf_pex}"}
+	do	eval "eixf_pex=\${eixf_pea%%[\$$eixf_pes]*}"
+		if [ "$eixf_pex" != "$eixf_pea" ]
+		then	eixf_pec=${eixf_pea#"$eixf_pex"}
 			eixf_pea=${eixf_pec#?}
-			eixf_pec=${eixf_pec%"${eixf_pea}"}
+			eixf_pec=${eixf_pec%"$eixf_pea"}
 		else	eixf_pea=
 			eixf_pec='\'
 		fi
 		Replace -g eixf_pex '\\' '\'
-		[ -n "${replace_tail:++}" ] && case ${eixf_pex} in
-		*\\)	eixf_pew=${eixf_pew}${eixf_pex%?}${eixf_pec}
+		[ -n "${replace_tail:++}" ] && case $eixf_pex in
+		*\\)	eixf_pew=$eixf_pew${eixf_pex%?}$eixf_pec
 			continue;;
 		esac
-		eixf_pew=${eixf_pew}${eixf_pex}
-		[ -n "${eixf_pew:++}" ] && Push ${1} "${eixf_pew}"
+		eixf_pew=$eixf_pew$eixf_pex
+		[ -n "${eixf_pew:++}" ] && Push $1 "$eixf_pew"
 		eixf_pew=
 	done
-	[ -n "${eixf_pew:++}" ] && Push ${1} "${eixf_pew}"
+	[ -n "${eixf_pew:++}" ] && Push $1 "$eixf_pew"
 }
 
 AddUpdateArgs() {
-	Push update_args "${@}"
+	Push update_args "$@"
 }
 
 AddUpdateQuoting() {
-	eixf_aq=${1}
+	eixf_aq=$1
 	shift
 	Replace -g eixf_aq '\' '\\'
 	Replace -g eixf_aq '?' '\?'
 	Replace -g eixf_aq '*' '\*'
 	Replace -g eixf_aq '[' '\['
-	AddUpdateArgs "${eixf_aq}" "${@}"
+	AddUpdateArgs "$eixf_aq" "$@"
 }
 
 AddMethod() {
 	AddUpdateArgs '-m'
-	AddUpdateQuoting "${1}" "${2}"
+	AddUpdateQuoting "$1" "$2"
 }
 
 AddRepoName() {
-	AddUpdateArgs '-r' "${1}" "${2}"
+	AddUpdateArgs '-r' "$1" "$2"
 }
 
 AddOverlays() {
 	for eixf_ao
-	do	AddUpdateArgs '-a' "${eixf_ao}"
+	do	AddUpdateArgs '-a' "$eixf_ao"
 	done
 }
 
 AddExcludes() {
 	for eixf_ax
 	do	AddUpdateArgs '-x'
-		AddUpdateQuoting "${eixf_ax}"
+		AddUpdateQuoting "$eixf_ax"
 	done
 }
 
@@ -308,16 +308,16 @@ ClearUpdateArgs() {
 
 : ${die_on_update_failure=:}
 CallUpdate() {
-	case ${-} in
+	case $- in
 	*f*)
-		eval "set -- ${update_args}";;
+		eval "set -- $update_args";;
 	*)
 		set -f
-		eval "set -- ${update_args}"
+		eval "set -- $update_args"
 		set +f;;
 	esac
-	RunCommand "`gettext 'Calling eix-update'`" eix-update "${@}" && return
-	${die_on_update_failure} && die "`gettext 'eix-update failed'`"
+	RunCommand "`gettext 'Calling eix-update'`" eix-update "$@" && return
+	$die_on_update_failure && die "`gettext 'eix-update failed'`"
 }
 
 InitPortdirOverlay() {
@@ -326,22 +326,22 @@ InitPortdirOverlay() {
 
 AddLocalMethods() {
 	GetPortdir
-	AddMethod "${local_portdir}" "eix"
+	AddMethod "$local_portdir" "eix"
 	InitPortdirOverlay
-	PushEscaped -c eixf_alm "${PORTDIR_OVERLAY}"
+	PushEscaped -c eixf_alm "$PORTDIR_OVERLAY"
 	ReadVar eixf_al ADD_OVERLAY
-	PushEscaped eixf_alm "${eixf_al}"
-	case ${-} in
-	*f*)	eval "set -- ${eixf_alm}";;
+	PushEscaped eixf_alm "$eixf_al"
+	case $- in
+	*f*)	eval "set -- $eixf_alm";;
 	*)	set -f
-		eval "set -- ${eixf_alm}"
+		eval "set -- $eixf_alm"
 		set +f;;
 	esac
 	for eixf_alm
-	do	eixf_al=${eixf_alm}
+	do	eixf_al=$eixf_alm
 		Replace -g eixf_al '\' '\\'
 		Replace -g eixf_al ':' '\:'
-		AddMethod "${eixf_alm}" "eix::${eixf_al}"
+		AddMethod "$eixf_alm" "eix::$eixf_al"
 	done
 }
 
@@ -349,12 +349,12 @@ AddLocalMethods() {
 # This is necessary as some shells won't take ${Var%"[newline]"}
 Chomp() {
 	for eixf_chompa
-	do	eval eixf_chompb=\${${eixf_chompa}}
-		case ${eixf_chompb} in
+	do	eval eixf_chompb=\$$eixf_chompa
+		case $eixf_chompb in
 		*'
 ')
 			eixf_chompb=${eixf_chompb%?}
-			eval ${eixf_chompa}=\${eixf_chompb};;
+			eval $eixf_chompa=\$eixf_chompb;;
 		esac
 	done
 }
@@ -364,21 +364,21 @@ Chomp() {
 
 Pathify() {
 	for eixf_pathc
-	do	eval eixf_patha=\${${eixf_pathc}}
-		eixf_pathb=`command -v "${eixf_patha}"; printf A` && \
+	do	eval eixf_patha=\$$eixf_pathc
+		eixf_pathb=`command -v "$eixf_patha"; printf A` && \
 			eixf_pathb=${eixf_pathb%A} && Chomp eixf_pathb && \
-			[ -n "${eixf_pathb:++}" ] && test -x "${eixf_pathb}" \
+			[ -n "${eixf_pathb:++}" ] && test -x "$eixf_pathb" \
 			|| die "`eval_gettext \
-				'${eixf_patha} cannot be found in PATH'`"
-		eval ${eixf_pathc}=\${eixf_pathb}
+				'$eixf_patha cannot be found in PATH'`"
+		eval $eixf_pathc=\$eixf_pathb
 	done
 }
 
 CheckReadlink() {
-	[ -n "${readlink_stat:++}" ] && return ${readlink_stat}
+	[ -n "${readlink_stat:++}" ] && return $readlink_stat
 	readlink -f / >/dev/null 2>&1
-	readlink_stat=${?}
-	return ${readlink_stat}
+	readlink_stat=$?
+	return $readlink_stat
 }
 
 # Consider variables (arguments) as paths and normalize them.
@@ -393,37 +393,37 @@ NormalizeNames() {
 	eixf_normd=0
 	relative=
 	for eixf_normc
-	do	eval eixf_norma=\${${eixf_normc}}
+	do	eval eixf_norma=\$$eixf_normc
 		if [ -z "${eixf_norma:++}" ]
 		then	eixf_normd=1
 			continue
 		fi
-		case ${eixf_norma} in
+		case $eixf_norma in
 		/*)	:;;
-		*)	relative="${relative} ${eixf_normc}";;
+		*)	relative="$relative $eixf_normc";;
 		esac
-		${normalize_resolve} && if CheckReadlink
+		$normalize_resolve && if CheckReadlink
 		then	# Append A to avoid loss of trailing space in `...`
-			eixf_normb=`readlink -f -- "${eixf_norma}"; printf A` \
+			eixf_normb=`readlink -f -- "$eixf_norma"; printf A` \
 				&& eixf_normb=${eixf_normb%A} \
 				&& Chomp eixf_normb
-		elif test -d "${eixf_norma}"
-		then	eixf_normb=`case ${eixf_norma} in
-				/*)	cd -P "${eixf_norma}";;
-				*)	cd -P "./${eixf_norma}";;
+		elif test -d "$eixf_norma"
+		then	eixf_normb=`case $eixf_norma in
+				/*)	cd -P "$eixf_norma";;
+				*)	cd -P "./$eixf_norma";;
 				esac >/dev/null 2>&1 \
-				&& printf '%sA' "${PWD}"` \
+				&& printf '%sA' "$PWD"` \
 				&& eixf_normb=${eixf_normb%A}
 		else	false
-		fi && [ -n "${eixf_normb:++}" ] && eixf_norma=${eixf_normb}
-		eval ${eixf_normc}=\${eixf_norma}
-		while Replace -g "${eixf_normc}" '//' '/'
+		fi && [ -n "${eixf_normb:++}" ] && eixf_norma=$eixf_normb
+		eval $eixf_normc=\$eixf_norma
+		while Replace -g "$eixf_normc" '//' '/'
 		do	:
 		done
-		eval "[ \"\${${eixf_normc}}\" = '/' ] || \
-			${eixf_normc}=\${${eixf_normc}%/}"
+		eval "[ \"\$$eixf_normc\" = '/' ] || \
+			$eixf_normc=\${$eixf_normc%/}"
 	done
-	return ${eixf_normd}
+	return $eixf_normd
 }
 
 ReadGettext() {
@@ -440,34 +440,34 @@ ReadGettext() {
 		return 0
 	}
 gettext() {
-	printf '%s' "${*}"
+	printf '%s' "$*"
 }
 eixf_varopen='${'
 eixf_varclose='}'
 eval_gettext() {
-	eixf_gettexta=${*}
+	eixf_gettexta=$*
 	eixf_gettextb=
-	while eixf_gettextc=${eixf_gettexta%%"${eixf_varopen}"*}
-	do	eixf_gettextb=${eixf_gettextb}${eixf_gettextc}
-		[ "${eixf_gettextc}" = "${eixf_gettexta}" ] && break
-		eixf_gettexta=${eixf_gettexta#*"${eixf_varopen}"}
-		eixf_gettextc=${eixf_gettexta%%"${eixf_varclose}"*}
-		case ${eixf_gettextc} in
-		"${eixf_gettexta}"|*[!a-zA-Z0-9_]*)
-			eixf_gettextb=${eixf_gettextb}${eixf_varopen}
+	while eixf_gettextc=${eixf_gettexta%%"$eixf_varopen"*}
+	do	eixf_gettextb=$eixf_gettextb$eixf_gettextc
+		[ "$eixf_gettextc" = "$eixf_gettexta" ] && break
+		eixf_gettexta=${eixf_gettexta#*"$eixf_varopen"}
+		eixf_gettextc=${eixf_gettexta%%"$eixf_varclose"*}
+		case $eixf_gettextc in
+		"$eixf_gettexta"|*[!a-zA-Z0-9_]*)
+			eixf_gettextb=$eixf_gettextb$eixf_varopen
 			continue;;
 		esac
-		eval eixf_gettextb=\${eixf_gettextb}\${${eixf_gettextc}}
-		eixf_gettexta=${eixf_gettexta#*"${eixf_varclose}"}
+		eval eixf_gettextb=\$eixf_gettextb\$$eixf_gettextc
+		eixf_gettexta=${eixf_gettexta#*"$eixf_varclose"}
 	done
-	printf '%s' "${eixf_gettextb}"
+	printf '%s' "$eixf_gettextb"
 	unset eixf_gettexta eixf_gettextb eixf_gettextc
 }
 ngettext() {
-	gettext "${1}"
+	gettext "$1"
 }
 eval_ngettext() {
-	eval_gettext "${1}"
+	eval_gettext "$1"
 }
 ReadGettext() {
 	return 1
@@ -478,56 +478,56 @@ ReadGettext() {
 unset have_random
 AssignTempEmulate() {
 	if [ -z "${have_random++}" ]
-	then	eixf_assb=${RANDOM}
-		if [ "${eixf_assb}" = "${RANDOM}" ] && \
-			[ "${eixf_assb}" = "${RANDOM}" ]
+	then	eixf_assb=$RANDOM
+		if [ "$eixf_assb" = "$RANDOM" ] && \
+			[ "$eixf_assb" = "$RANDOM" ]
 		then	have_random=false
 			eixf_assb=`od -d -N2 /dev/random 2>/dev/null` \
 				|| eixf_assb=
-			eixf_assb=`printf '%s' ${eixf_assb}`
+			eixf_assb=`printf '%s' $eixf_assb`
 			if [ -z "${eixf_assb:++}" ]
 			then	eixf_assb=1
-			else	eixf_assb=`Expr "${eixf_assb} % 32768"`
-				[ "${eixf_assb}" -eq 0 ] && eixf_assb=1
+			else	eixf_assb=`Expr "$eixf_assb % 32768"`
+				[ "$eixf_assb" -eq 0 ] && eixf_assb=1
 			fi
 		else	have_random=:
 		fi
 		eixf_assc=
 	fi
 	eixf_assa=0
-	while [ ${eixf_assa} -le 9999 ]
+	while [ $eixf_assa -le 9999 ]
 	do	if [ -n "${eixf_assc:++}" ]
-		then	if ${have_random}
-			then	eixf_assb=${RANDOM}
-			else	eixf_assb=`Expr "${eixf_assb}" '*' '13821'`
-				eixf_assb=`Expr "${eixf_assb}" '%' '32768'`
+		then	if $have_random
+			then	eixf_assb=$RANDOM
+			else	eixf_assb=`Expr "$eixf_assb" '*' '13821'`
+				eixf_assb=`Expr "$eixf_assb" '%' '32768'`
 			fi
 		fi
-		eixf_assc="/tmp/${0##*/}.${$}${eixf_assa}${eixf_assb}"
-		if [ "${2}" = '-d' ]
-		then	mkdir -m 700 -- "${eixf_assc}"
+		eixf_assc=/tmp/${0##*/}.$$$eixf_assa$eixf_assb
+		if [ "$2" = '-d' ]
+		then	mkdir -m 700 -- "$eixf_assc"
 		else	(
 			set -C
-			: >"${eixf_assc}"
+			: >"$eixf_assc"
 		)
-		fi && eval ${1}=\${eixf_assc} && return
-		eixf_assa=`Expr "${eixf_assa}" + 1`
+		fi && eval $1=\$eixf_assc && return
+		eixf_assa=`Expr "$eixf_assa" + 1`
 	done
 	die "`gettext 'found no free temporary name after 10000 attempts'`"
 }
 
 unset have_mktemp
 AssignTemp() {
-	eval ${1}=
+	eval $1=
 	if [ -z "${have_mktemp++}" ]
 	then	command -v mktemp >/dev/null 2>&1 \
 			&& have_mktemp=: || have_mktemp=false
 	fi
-	if ${have_mktemp}
-	then	eval ${1}'=`mktemp ${2} "/tmp/${0##*/}.XXXXXXXX"`'
-	else	AssignTempEmulate "${@}"
+	if $have_mktemp
+	then	eval $1'=`mktemp $2 "/tmp/${0##*/}.XXXXXXXX"`'
+	else	AssignTempEmulate "$@"
 	fi && return
-	[ "${2}" = '-d' ] && \
+	[ "$2" = '-d' ] && \
 		die "`gettext 'cannot create temporary directory'`"
 	die "`gettext 'cannot create temporary file'`"
 }
diff --git a/src/eix-installed-after.in b/src/eix-installed-after.in
--- a/src/eix-installed-after.in
+++ b/src/eix-installed-after.in
@@ -17,15 +17,15 @@ ReadFunctions
 # Prepend content of eix variable EIX_INSTALLED_AFTER to the arguments
 
 ReadVar EIX_INSTALLED_AFTER EIX_INSTALLED_AFTER
-eval "set -- ${EIX_INSTALLED_AFTER} \"\${@}\""
+eval "set -- $EIX_INSTALLED_AFTER \"\$@\""
 
 # The following function outputs the usage of the script and then dies.
 
 Usage() {
 	n=${0##*/}
 	p='@PACKAGE_STRING@'
-	eval_gettext 'Usage: ${n} [options] category/package[:slot]
-This is a well-commented demo script for eix (${p}).
+	eval_gettext 'Usage: $n [options] category/package[:slot]
+This is a well-commented demo script for eix ($p).
 It lists packages installed after (or before) the last (or first) install
 of the given package/version in an output format which is convenient
 as an argument for "emerge -1".
@@ -73,7 +73,7 @@ The following options are available:
 -T   Never use build time'
 	echo
 	exitcode=${1:-1}
-	Exit ${exitcode}
+	Exit $exitcode
 }
 
 
@@ -95,14 +95,14 @@ DefaultOpts() {
 DefaultOpts
 OPTIND=1
 while getopts 'fF:lL:e:a:A:bdsv=SViItTh?' opt
-do	case ${opt} in
+do	case $opt in
 	f)	full=:;;
-	F)	timefile=${OPTARG};;
+	F)	timefile=$OPTARG;;
 	l)	logfile='/var/log/emerge.log';;
-	L)	logfile=${OPTARG};;
-	e)	epoch=${OPTARG};;
-	a)	addtime=${OPTARG};;
-	A)	subtime=${OPTARG};;
+	L)	logfile=$OPTARG;;
+	e)	epoch=$OPTARG;;
+	a)	addtime=$OPTARG;;
+	A)	subtime=$OPTARG;;
 	b)	before=:;;
 	d)	date_output='\t<date:DATE_OUTPUT>';;
 	s)	output='NAMEASLOT';;
@@ -117,36 +117,36 @@ do	case ${opt} in
 	*)	Usage 0;;
 	esac
 done
-[ ${OPTIND} -le 1 ] || shift `Expr ${OPTIND} - 1`
+[ $OPTIND -le 1 ] || shift `Expr $OPTIND - 1`
 
-# After the options there should be exactly one argument: ${match}
+# After the options there should be exactly one argument: $match
 
 if [ -n "${timefile:++}" ]
-then	epoch=`stat -c '%Y' -- "${timefile}" 2>/dev/null` || epoch=
+then	epoch=`stat -c '%Y' -- "$timefile" 2>/dev/null` || epoch=
 fi
 
 # "found" is our flag in the loop whether we already found our package.
 found=false
-if ${full}
+if $full
 then	logfile=
 	before=false
 	epoch=
 	found=:
 elif [ -z "${epoch:++}" ]
-then	[ ${#} -eq 1 ] || Usage
-	match=${1}
+then	[ $# -eq 1 ] || Usage
+	match=$1
 fi
 
 
 # With options -l or -L, we also have to parse the logfile:
 
 if [ -n "${logfile:++}" ]
-then	test -r "${logfile}" || die "`eval_gettext 'cannot read ${logfile}'`"
+then	test -r "$logfile" || die "`eval_gettext 'cannot read $logfile'`"
 	epoch=`unset LC_ALL
 LC_COLLATE=C
-sed -ne "\\: Merging (${match}\\:\\:.*):{s/^\([0-9]*\).*/\\1/p
-q}" "${logfile}"` && [ -n "${epoch:++}" ] || die "`eval_gettext \
-		'cannot find merge of ${match} in ${logfile}'`"
+sed -ne "\\: Merging ($match\\:\\:.*):{s/^\([0-9]*\).*/\\1/p
+q}" "$logfile"` && [ -n "${epoch:++}" ] || die "`eval_gettext \
+		'cannot find merge of $match in $logfile'`"
 fi
 
 # We will let eix output for each installed package (and then sort by time):
@@ -155,34 +155,34 @@ fi
 #	package (in the output format) [TAB date (in the format "%x %X")]
 #	newline
 # (the [...] part occurs only with option -d).
-# The functions Check resp. Output are called with each ${line} as argument
+# The functions Check resp. Output are called with each $line as argument
 # (which thus undergoes the usual splitting at spaces or tabs).
-# Check  returns 0 if the package matches ${match} (or is known to be younger).
+# Check  returns 0 if the package matches $match (or is known to be younger).
 # Output outputs the package (and date).
 # Both functions ignore empty lines.
 
 if [ -z "${epoch:++}" ]
 then
 Check() {
-	[ ${#} -ge 2 ] && case "${2}:" in
-	${match}:*)
+	[ $# -ge 2 ] && case "$2:" in
+	$match:*)
 		return 0;;
 	esac
 	return 1
 }
-else	[ -z "${addtime:++}" ] || epoch=`Expr "${epoch}" + "${addtime}"`
-	[ -z "${subtime:++}" ] || epoch=`Expr "${epoch}" - "${subtime}"`
+else	[ -z "${addtime:++}" ] || epoch=`Expr "$epoch" + "$addtime"`
+	[ -z "${subtime:++}" ] || epoch=`Expr "$epoch" - "$subtime"`
 # With options -f, -e, -l, -L, we need a different Check function:
 Check() {
-	[ ${#} -ne 0 ] && [ "${1}" -ge "${epoch}" ]
+	[ $# -ne 0 ] && [ "$1" -ge "$epoch" ]
 }
 fi
 
 Output() {
-	if [ ${#} -eq 3 ]
-	then	Echo "${3}"
-	elif [ ${#} -gt 3 ]
-	then	printf '%-43s %-11s %s\n' "${3}" "${4}" "${5}"
+	if [ $# -eq 3 ]
+	then	Echo "$3"
+	elif [ $# -gt 3 ]
+	then	printf '%-43s %-11s %s\n' "$3" "$4" "$5"
 	fi
 }
 
@@ -231,19 +231,19 @@ VERSION_NEWLINE= \
 DATE_FORMAT='%s' \
 DATE_OUTPUT='%x %X' \
 NAME='<category>/<package>' \
-LINE='<date:DATE_FORMAT>\t%{'${input}'}\t%{'${output}'}'${date_output}'\n' \
+LINE='<date:DATE_FORMAT>\t%{'$input'}\t%{'$output'}'$date_output'\n' \
 eix --format '<installedversions:LINE>' '-I*' \
 | sort -n \
 | {
 	while read -r line
-	do	if ${found}
-		then	${before} || Output ${line}
-		elif Check ${line}
+	do	if $found
+		then	$before || Output $line
+		elif Check $line
 		then	found=:
-			${including} && Output ${line}
-		else	${before} && Output ${line}
+			$including && Output $line
+		else	$before && Output $line
 		fi
 	done
-	${found}
+	$found
 }
 Exit
diff --git a/src/eix-remote.in b/src/eix-remote.in
--- a/src/eix-remote.in
+++ b/src/eix-remote.in
@@ -14,13 +14,13 @@ my_getopts='KvqxXLl:a:kiHh?'
 
 set -f
 eval "Push -c opt `eix-update --print EIX_REMOTE_OPTS`"
-Push opt "${@}"
-eval "set -- ${opt}"
+Push opt "$@"
+eval "set -- $opt"
 
 drop_permissions=:
 OPTIND=1
-while getopts "${my_getopts}" opt
-do	case ${opt} in
+while getopts "$my_getopts" opt
+do	case $opt in
 	K)	drop_permissions=false
 		break;;
 	k)	drop_permissions=false;;
@@ -28,11 +28,11 @@ do	case ${opt} in
 	*)	:;;
 	esac
 done
-if ${drop_permissions}
+if $drop_permissions
 then	prg=./eix-drop-permissions
 	me=./eix-remote.in
-	exec "${prg}" -- "${me}" -K "${@}"
-	die "`eval_gettext 'failed to execute ${prg}'`"
+	exec "$prg" -- "$me" -K "$@"
+	die "`eval_gettext 'failed to execute $prg'`"
 fi
 
 addr1='@DEFAULT_REMOTE_PATH1@'
@@ -44,17 +44,17 @@ ReadVar local_layman LOCAL_LAYMAN
 Usage() {
 	n=${0##*/}
 	p='@PACKAGE_STRING@'
-	f1=${archive1}
-	f2=${archive2}
+	f1=$archive1
+	f2=$archive2
 	[ -n "${f:+}" ] || f=`gettext 'temporary file'`
-	eval_gettext 'Usage: ${n} [options] command
-Get data from a remote database for ${p}.
+	eval_gettext 'Usage: $n [options] command
+Get data from a remote database for $p.
 The following commands are provided:
 
 update1 (=update) or update2:
         Fetch the eix-caches of some layman overlays, store them locally in
-        EIX_REMOTEARCHIVE1 (${f1}) or
-        EIX_REMOTEARCHIVE2 (${f2}),
+        EIX_REMOTEARCHIVE1 ($f1) or
+        EIX_REMOTEARCHIVE2 ($f2),
         respectively and add them to the eix database.
         If EIX_REMOTE1 or EIX_REMOTE2, respectively, is nonempty the output
         goes to that separate database.
@@ -95,15 +95,15 @@ The following options are available:
         Set LOCAL_LAYMAN or use option -l to override the heuristics.
 -l PATH Use PATH as LOCAL_LAYMAN
 -a ADDR Use ADDR as remote database address instead of:
-        ${addr1}
-        ${addr2}
+        $addr1
+        $addr2
 -i      Ignore all previous options (e.g. ignore EIX_REMOTE_OPTS).
 -v      Verbose (default)
 -H      Suppress status line update
 -q      Quiet'
 	echo
 	exitcode=${1:-1}
-	Exit ${exitcode}
+	Exit $exitcode
 }
 
 DefaultOpts() {
@@ -118,8 +118,8 @@ DefaultOpts() {
 
 DefaultOpts
 OPTIND=1
-while getopts "${my_getopts}" opt
-do	case ${opt} in
+while getopts "$my_getopts" opt
+do	case $opt in
 	i)	DefaultOpts;;
 	[kK])	:;;
 	v)	verbose=:;;
@@ -127,14 +127,14 @@ do	case ${opt} in
 	x)	excludelocal=:;;
 	X)	excluderemote=:;;
 	L)	excludedebug=:;;
-	l)	local_layman=${OPTARG};;
-	a)	addr=${OPTARG};;
+	l)	local_layman=$OPTARG;;
+	a)	addr=$OPTARG;;
 	H)	statusline=false;;
 	*)	Usage 0;;
 	esac
 done
-[ ${OPTIND} -le 1 ] || shift `Expr ${OPTIND} - 1`
-${statusline} || export NOSTATUSLINE=true
+[ $OPTIND -le 1 ] || shift `Expr $OPTIND - 1`
+$statusline || export NOSTATUSLINE=true
 
 SanitizeLocalLayman() {
 	normalize_resolve=false NormalizeNames local_layman \
@@ -146,12 +146,12 @@ SanitizeLocalLayman() {
 PrintLaymanStorage() {
 	printf '%s\n%s\n' 'from layman.config import BareConfig' \
 	"print(BareConfig(read_configfile=True)['storage'])" \
-		| python -- "${@}" 2>/dev/null
+		| python -- "$@" 2>/dev/null
 }
 
 PrintLaymanStorageOld() {
 	printf '%s\n%s\n' 'from layman.config import Config' \
-	"print(Config()['storage'])" | python -- "${@}" 2>/dev/null
+	"print(Config()['storage'])" | python -- "$@" 2>/dev/null
 }
 
 InitLocalLayman() {
@@ -161,36 +161,36 @@ InitLocalLayman() {
 	then	local_layman=`PrintLaymanStorageOld` || local_layman=
 	fi
 	for i in \
-		"${local_layman}" \
+		"$local_layman" \
 		'/usr/local/portage/layman' \
 		"${local_portdir:-/}local/layman/make.conf" \
 		"${local_portdir%/*/}/layman/make.conf" \
 		'/var/lib/layman'
-	do	[ -n "${i:++}" ] && test -d "${i}" && local_layman=${i} \
+	do	[ -n "${i:++}" ] && test -d "$i" && local_layman=$i \
 			&& return
 	done
 	return 1
 }
-if ${excluderemote} || ${excludelocal} || ${excludedebug}
+if $excluderemote || $excludelocal || $excludedebug
 then	InitLocalLayman && SanitizeLocalLayman || {
 		ewarn "`gettext 'cannot determine useful $LOCAL_LAYMAN'`"
-		if ${excludedebug}
-		then	[ -n "${local_layman:++}" ] && Echo "${local_layman}"
+		if $excludedebug
+		then	[ -n "${local_layman:++}" ] && Echo "$local_layman"
 			Exit 1
 		fi
 		excludelocal=false
 		excluderemote=false
 	}
-	if ${excludedebug}
-	then	Echo "${local_layman}"
+	if $excludedebug
+	then	Echo "$local_layman"
 		Exit
 	fi
 fi
 
 CdDir() {
-	cd "${1}" >/dev/null && return
-	a=${1}
-	die "`eval_gettext 'cannot cd to ${a}'`"
+	cd "$1" >/dev/null && return
+	a=$1
+	die "`eval_gettext 'cannot cd to $a'`"
 }
 
 tmpdir=
@@ -198,16 +198,16 @@ exitcode=0
 Cleanup() {
 	trap : EXIT HUP INT TERM
 	if [ -n "${tmpdir:++}" ]
-	then	test -d "${tmpdir}" && rm -rf -- "${tmpdir}"
+	then	test -d "$tmpdir" && rm -rf -- "$tmpdir"
 	fi
 	tmpdir=
 	trap - EXIT HUP INT TERM
-	Exit ${exitcode}
+	Exit $exitcode
 }
 MakeTempDir() {
 	trap Cleanup EXIT HUP INT TERM
 	AssignTemp tmpdir -d
-	chmod -- a+rx "${tmpdir}"
+	chmod -- a+rx "$tmpdir"
 }
 
 tmpfile=
@@ -218,26 +218,26 @@ FetchTemp() {
 Please specify a valid remote file with option -a.
 The default should have been set with ./configure --remote-file'`"
 	MakeTempDir
-	tmpfile="${tmpdir}/${eixcachesname}"
-	[ -n "${archive:++}" ] && test -e "${archive}" \
-		&& cp -p -- "${archive}" "${tmpfile}" >/dev/null 2>&1
+	tmpfile=$tmpdir/$eixcachesname
+	[ -n "${archive:++}" ] && test -e "$archive" \
+		&& cp -p -- "$archive" "$tmpfile" >/dev/null 2>&1
 	Statusline "`gettext 'Downloading remote data'`"
 	(
-		CdDir "${tmpdir}" || die "`gettext 'cannot cd to tempdir'`"
+		CdDir "$tmpdir" || die "`gettext 'cannot cd to tempdir'`"
 		umask 002
 		set -- wget -N
-		${verbose} || set -- "${@}" --no-verbose
-		set -- "${@}" -- "${addr}"
-		if ${verbose}
-		then	"${@}"
-		else	a=`"${@}" 2>&1` || {
-				Echo "${a}" >&2
+		$verbose || set -- "$@" --no-verbose
+		set -- "$@" -- "$addr"
+		if $verbose
+		then	"$@"
+		else	a=`"$@" 2>&1` || {
+				Echo "$a" >&2
 				false
 			}
-		fi || die "`gettext 'failed: '` ${*}"
+		fi || die "`gettext 'failed: '` $*"
 	) || {
-		exitcode=${?}
-		exit ${exitcode}
+		exitcode=$?
+		exit $exitcode
 	}
 }
 
@@ -263,12 +263,12 @@ to use eix-remote: This inconvenience cannot be avoided and is not a bug!'
 }
 
 AddArchive() {
-	a=${1}
-	CdDir "${2}"
-	RunCommand "`gettext 'Unpacking data'`" tar xjf "${a}" || {
-		msg=`eval_gettext 'cannot unpack ${a}'`
-		msg=${msg}`BugReport`
-		die "${msg}"
+	a=$1
+	CdDir "$2"
+	RunCommand "`gettext 'Unpacking data'`" tar xjf "$a" || {
+		msg=`eval_gettext 'cannot unpack $a'`
+		msg=$msg`BugReport`
+		die "$msg"
 	}
 	ClearUpdateArgs
 	AddLocalMethods
@@ -278,73 +278,73 @@ AddArchive() {
 	set +f
 	chmod a+r *
 	for i in *
-	do	p="${2}/${i}"
+	do	p=$2/$i
 		Replace -g p '\' '\\'
 		Replace -g p ':' '\:'
-		Push eixoverlay "-f${p}" "-o" ''
-		Push method "eix*:${p}:0"
+		Push eixoverlay "-f$p" "-o" ''
+		Push method "eix*:$p:0"
 	done
 	set -f
 	sep=mAgIcsEp
-	eval "set -- ${eixoverlay}"
-	eixoverlay=`eix-header -s"${sep}" "${@}"` || exitcode=1
+	eval "set -- $eixoverlay"
+	eixoverlay=`eix-header -s"$sep" "$@"` || exitcode=1
 	failcount=0
 	success=false
-	eval "set -- ${method}"
+	eval "set -- $method"
 	for i
-	do	l=${eixoverlay%%${sep}*}
-		eixoverlay=${eixoverlay#*${sep}}
-		name=${eixoverlay%%${sep}*}
-		eixoverlay=${eixoverlay#*${sep}}
-		[ -n "${l}${name}" ] || {
+	do	l=${eixoverlay%%$sep*}
+		eixoverlay=${eixoverlay#*$sep}
+		name=${eixoverlay%%$sep*}
+		eixoverlay=${eixoverlay#*$sep}
+		[ -n "$l$name" ] || {
 			p=${i##*/}
 			p=${p%:*}
-			ewarn "`eval_gettext 'file ${p} of ${a} contains no overlay'`"
-			failcount=`Expr ${failcount} + 1`
+			ewarn "`eval_gettext 'file $p of $a contains no overlay'`"
+			failcount=`Expr $failcount + 1`
 			continue
 		}
 		success=:
 		name=${name##*/}
-		${excludelocal} && AddExcludes "${local_layman}/${name}"
-		${excluderemote} && \
-			test -r "${local_layman}/${name}" && continue
-		virtual="layman/${name}"
-		printf '%s -> %s\n' "${virtual}" "${l:-no repo-name}"
-		AddMethod "${virtual}" "${i}"
-		AddOverlays "${virtual}"
-		[ -n "${l:++}" ] && AddRepoName "${virtual}" "${l}"
+		$excludelocal && AddExcludes "$local_layman/$name"
+		$excluderemote && \
+			test -r "$local_layman/$name" && continue
+		virtual=layman/$name
+		printf '%s -> %s\n' "$virtual" "${l:-no repo-name}"
+		AddMethod "$virtual" "$i"
+		AddOverlays "$virtual"
+		[ -n "${l:++}" ] && AddRepoName "$virtual" "$l"
 	done
 	msg=
-	if [ ${exitcode} -ne 0 ]
-	then	msg=`eval_gettext 'could not read all eix cachefiles of ${a}'`
-	elif ! ${success}
-	then	msg=`eval_gettext 'no file in ${a} contains an overlay'`
-	elif [ ${failcount} -gt 1 ]
-	then	ewarn "`eval_gettext '${failcount} files in ${a} contain no overlay'`"
-	elif [ ${failcount} -gt 0 ]
-	then	ewarn "`eval_gettext 'A file in ${a} contains no overlay'`"
+	if [ $exitcode -ne 0 ]
+	then	msg=`eval_gettext 'could not read all eix cachefiles of $a'`
+	elif ! $success
+	then	msg=`eval_gettext 'no file in $a contains an overlay'`
+	elif [ $failcount -gt 1 ]
+	then	ewarn "`eval_gettext '$failcount files in $a contain no overlay'`"
+	elif [ $failcount -gt 0 ]
+	then	ewarn "`eval_gettext 'A file in $a contains no overlay'`"
 	fi
 	die_on_update_failure=false
-	ReadVar ${eix_remote_var} ${eix_remote_var}
-	eval eix_remote=\${${eix_remote_var}}
+	ReadVar $eix_remote_var $eix_remote_var
+	eval eix_remote=\$$eix_remote_var
 	(
 		if [ -n "${eix_remote:++}" ]
 		then	einfo "`eval_gettext \
-				'Output to remote database ${eix_remote}'`"
-			AddUpdateArgs '-o' "${eix_remote}"
+				'Output to remote database $eix_remote'`"
+			AddUpdateArgs '-o' "$eix_remote"
 			umask 002
 		fi
 		KEEP_VIRTUALS=true
 		export KEEP_VIRTUALS
 		CallUpdate
 	) || {
-		exitcode=${?}
+		exitcode=$?
 		msg=`gettext 'eix-update failed'; \
-			[ -n "${msg:++}" ] && printf '\n%s' "${msg}"`
+			[ -n "${msg:++}" ] && printf '\n%s' "$msg"`
 	}
 	[ -z "${msg:++}" ] && return
-	msg=${msg}`BugReport`
-	die "${msg}"
+	msg=$msg`BugReport`
+	die "$msg"
 }
 
 CheckTemp() {
@@ -354,13 +354,13 @@ CheckTemp() {
 
 FetchFile() {
 	FetchTemp
-	file=${archive}
+	file=$archive
 	if [ -z "${file:++}" ]
-	then	file=${tmpfile}
+	then	file=$tmpfile
 		return
 	fi
-	cp -p -- "${tmpfile}" "${file}" || die "`eval_gettext \
-		'cannot copy temporary file to ${file}'`"
+	cp -p -- "$tmpfile" "$file" || die "`eval_gettext \
+		'cannot copy temporary file to $file'`"
 }
 
 
@@ -371,10 +371,10 @@ Fetch() {
 
 Add() {
 	CheckTemp
-	test -r "${archive}" || \
-		die "`eval_gettext 'cannot read ${archive}'`"
+	test -r "$archive" || \
+		die "`eval_gettext 'cannot read $archive'`"
 	MakeTempDir
-	AddArchive "${archive}" "${tmpdir}"
+	AddArchive "$archive" "$tmpdir"
 }
 
 Remove() {
@@ -388,22 +388,22 @@ Update() {
 	FetchFile
 	if [ -z "${tmpdir:++}" ]
 	then	MakeTempDir
-		tmpsup=${tmpdir}
-	else	tmpsub="${tmpdir}/1"
-		mkdir -m 700 -- "${tmpsub}" \
-			|| die "`eval_gettext 'mkdir ${tmpsub} failed'`"
+		tmpsup=$tmpdir
+	else	tmpsub=$tmpdir/1
+		mkdir -m 700 -- "$tmpsub" \
+			|| die "`eval_gettext 'mkdir $tmpsub failed'`"
 	fi
-	AddArchive "${file}" "${tmpsub}"
+	AddArchive "$file" "$tmpsub"
 }
 
 number=1
-case ${1} in
+case $1 in
 *2)
 	number=2;;
 esac
-[ -n "${addr:++}" ] || eval addr=\${addr${number}}
-eval archive=\${archive${number}}
-eix_remote_var=EIX_REMOTE${number}
+[ -n "${addr:++}" ] || eval addr=\${addr$number}
+eval archive=\${archive$number}
+eix_remote_var=EIX_REMOTE$number
 
 case ${1-} in
 update|update[12])
