fix http://bugs.gentoo.org/show_bug.cgi?id=112061
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@32 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/src/eix-sync.in b/src/eix-sync.in
--- a/src/eix-sync.in
+++ b/src/eix-sync.in
@@ -111,10 +111,11 @@ if [ -e "/etc/eix-sync-overlays" ]; then
 fi
 
 # Copy cache, create new cache and diff
-cp "/var/cache/eix" "/tmp/eix.$$" || die "Error while copying cache-file to a save location."
+tmpfile=$(mktemp)
+cp "/var/cache/eix" ${tmpfile} || die "Failed to create temporary cache file"
 run_command "Running update-eix" "update-eix" || exit 1 
-diff-eix "/tmp/eix.$$" || die "Error while diffing."
-rm "/tmp/eix.$$" || die "Can't remove tempfile /tmp/eix.$$"
+diff-eix ${tmpfile} || die "Failed to diff against current cache"
+rm -f ${tmpfile} || die "Failed to remove ${tmpfile}"
 
 exit 0 # Goodbye
 
