eix-remote: add option -x/-X. Cosmetical Changes. Let /etc/eixrc be a folder

diff --git a/src/eix-remote.in b/src/eix-remote.in
--- a/src/eix-remote.in
+++ b/src/eix-remote.in
@@ -10,7 +10,7 @@
 
 . ./eix-functions.sh.in
 ReadFunctions
-my_getopts='Kvql:a:kiHh?'
+my_getopts='KvqxXLl:a:kiHh?'
 
 set -f
 eval "Push -c opt `eix-update --print EIX_REMOTE_OPTS`"
@@ -39,6 +39,7 @@ addr1='@DEFAULT_REMOTE_PATH1@'
 addr2='@DEFAULT_REMOTE_PATH2@'
 ReadVar archive1 EIX_REMOTEARCHIVE1
 ReadVar archive2 EIX_REMOTEARCHIVE2
+ReadVar local_layman LOCAL_LAYMAN
 
 Usage() {
 	n=${0##*/}
@@ -84,26 +85,19 @@ remove: Remove all temporarily added virtual overlays from the eix database.
         	KEEP_VIRTUALS=false eix-update
         but faster (using previous cachefile where possible).
 
-The script will try to change its permissions to that of user EIX_USER
-before doing anything else (unless option -k or an empty user is specified),
-using sudo or su (see options -s and -S).
-
-For "update?" and "add?" all corresponding local layman overlay paths are
-excluded from the update of the current database to avoid confusion.
-These local paths are determined by prefixing the path
-	${LOCAL_LAYMAN}
-You can modify this value with the -l option or by setting the environment
-variable LOCAL_LAYMAN. If you do not want this feature (i.e. if you want
-to see your local layman overlays and the remote layman overlays),
-use here some path not containing any overlays (usually "/" will do).
-
 Options can be specified in the eix (or environment) variable EIX_REMOTE_OPTS.
 This data is evalued, so be aware of security risks.
 Moreover, "--" in this variable will exclude further command line options.
 The following options are available:
 
--k      Keep permissions: Without this option, eix-drop-permissions is used.
+-k      Keep permissions: Without this option, eix-drop-permissions is used to
+        drop permissions immediately to that of EIX_USER
 -K      As -k, but cannot be reset with -i
+-X      Exclude remote overlays which are also locally layman. See -L/-l
+-x      Exclude local layman overlays which are available remotely. See -L/-l
+-L      For -x/-X the "storage" path of layman is found heuristically.
+        With -L the path actually used is printed (and eix-remote exits).
+        Set LOCAL_LAYMAN or use option -l to override the heuristics.
 -l PATH Use PATH as LOCAL_LAYMAN
 -a ADDR Use ADDR as remote database address instead of:
         ${addr1}
@@ -117,8 +111,36 @@ The following options are available:
 	Exit ${exitcode}
 }
 
+DefaultOpts() {
+	addr=
+	verbose=:
+	statusline=:
+	keep=false
+	exclude=
+}
+
+DefaultOpts
+OPTIND=1
+while getopts "${my_getopts}" opt
+do	case ${opt} in
+	i)	DefaultOpts;;
+	[kK])	:;;
+	v)	verbose=:;;
+	q)	verbose=false;;
+	x)	exclude=local;;
+	X)	exclude=remote;;
+	L)	exclude=debug;;
+	l)	local_layman=${OPTARG};;
+	a)	addr=${OPTARG};;
+	H)	statusline=false
+		export NOSTATUSLINE=true;;
+	*)	Usage 0;;
+	esac
+done
+[ ${OPTIND} -le 1 ] || shift `Expr ${OPTIND} - 1`
+
 SanitizeLocalLayman() {
-	normalize_resolve=false NormalizeNames LOCAL_LAYMAN \
+	normalize_resolve=false NormalizeNames local_layman \
 		|| die "`gettext '$LOCAL_LAYMAN must not be empty'`"
 	[ -z "${relative:++}" ] || \
 		die "`gettext '$LOCAL_LAYMAN must start with /'`"
@@ -135,53 +157,37 @@ PrintLaymanStorageOld() {
 	"print(Config()['storage'])" | python -- "${@}" 2>/dev/null
 }
 
-SetLocalLayman() {
-	for i
-	do	[ -n "${i:++}" ] && test -d "${i}" && LOCAL_LAYMAN=${i} \
-			&& return
-	done
-	return 1
-}
-
 InitLocalLayman() {
-	[ -n "${LOCAL_LAYMAN:++}" ] && return
-	LOCAL_LAYMAN=`PrintLaymanStorage` || LOCAL_LAYMAN=
-	if [ -z "${LOCAL_LAYMAN:++}" ]
-	then	LOCAL_LAYMAN=`PrintLaymanStorageOld` || LOCAL_LAYMAN=
+	[ -n "${local_layman:++}" ] && return
+	local_layman=`PrintLaymanStorage` || local_layman=
+	if [ -z "${local_layman:++}" ]
+	then	local_layman=`PrintLaymanStorageOld` || local_layman=
 	fi
-	SetLocalLayman "${LOCAL_LAYMAN}" \
+	for i in \
+		"${local_layman}" \
 		'/usr/local/portage/layman' \
 		"${local_portdir:-/}local/layman/make.conf" \
 		"${local_portdir%/*/}/layman/make.conf" \
 		'/var/lib/layman'
+	do	[ -n "${i:++}" ] && test -d "${i}" && local_layman=${i} \
+			&& return
+	done
+	return 1
 }
-
-DefaultOpts() {
-	addr=
-	verbose=:
-	statusline=:
-	keep=false
-}
-
-InitLocalLayman
-SanitizeLocalLayman
-DefaultOpts
-OPTIND=1
-while getopts "${my_getopts}" opt
-do	case ${opt} in
-	i)	DefaultOpts;;
-	[kK])	:;;
-	v)	verbose=:;;
-	q)	verbose=false;;
-	l)	LOCAL_LAYMAN=${OPTARG}
-		SanitizeLocalLayman;;
-	a)	addr=${OPTARG};;
-	H)	statusline=false
-		export NOSTATUSLINE=true;;
-	*)	Usage 0;;
-	esac
-done
-[ ${OPTIND} -le 1 ] || shift `Expr ${OPTIND} - 1`
+if [ -n "${exclude}" ]
+then	InitLocalLayman && SanitizeLocalLayman || {
+		ewarn "`gettext 'cannot determine useful $LOCAL_LAYMAN'`"
+		if [ "${exclude}" = 'debug' ]
+		then	[ -n "${local_layman}" ] && Echo "${local_layman}"
+			Exit 1
+		fi
+		exclude=
+	}
+	if [ "${exclude}" = 'debug' ]
+	then	Echo "${local_layman}"
+		Exit
+	fi
+fi
 
 CdDir() {
 	cd "${1}" >/dev/null && return
@@ -296,8 +302,10 @@ AddArchive() {
 		}
 		l=${l%${PRINT_APPEND}}
 		name=${l#*${PRINT_APPEND}}
-		l=${l%%${PRINT_APPEND}*}
 		name=${name##*/}
+		[ "${exclude}" = 'remote' ] && \
+			test -r "${local_layman}/${name}" && continue
+		l=${l%%${PRINT_APPEND}*}
 		virtual="layman/${name}"
 		printf '%s -> %s\n' "${virtual}" "${l:-no repo-name}"
 		Replace -g p '\' '\\'
@@ -305,7 +313,8 @@ AddArchive() {
 		AddMethod "${virtual}" "eix*:${p}:${n}"
 		AddOverlays "${virtual}"
 		[ -n "${l:++}" ] && AddRepoName "${virtual}" "${l}"
-		AddExcludes "${LOCAL_LAYMAN}/${name}"
+		[ "${exclude}" = 'local' ] && \
+			AddExcludes "${local_layman}/${name}"
 	done
 	unset PRINT_APPEND
 	msg=
