Use gettext also for scripts. Use non-capital names for non-environment variables in scripts. Various minor bugfixes (also of the scripts).
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@849 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/src/functions-eix.sh.in b/src/functions-eix.sh.in
--- a/src/functions-eix.sh.in
+++ b/src/functions-eix.sh.in
@@ -10,39 +10,78 @@
 # It contains helper functions for update-eix-remote, update-eix-layman,
 # and perhaps similar local scripts. (@PACKAGE_STRING@).
 
-LOCAL_EPREFIX_PORTAGE_EXEC="`update-eix --print EPREFIX_PORTAGE_EXEC`"
+local_eprefix_portage_exec="`update-eix --print EPREFIX_PORTAGE_EXEC`"
+
+read_gettext () {
+	local i
+	[ -n "${read_gettext_status}" ] && return ${read_gettext_status}
+	read_gettext_status=0
+	export TEXTDOMAIN='@TEXTDOMAIN@'
+	{
+		. gettext.sh && return
+		i="`command -v gettext.sh 2>/dev/null`" && \
+			[ -n "${i}" ] && . "${i}" && return
+		. /usr/bin/gettext.sh && return
+	} >/dev/null 2>&1
+	eval '
+	gettext() {
+		printf "%s" "${*}"
+	}
+	eval_gettext() {
+		eval "printf \"%s\" \"${*}\""
+	}
+	ngettext() {
+		gettext "${@}"
+	}
+	eval_ngettext() {
+		eval_gettext "${@}"
+	}
+	'
+	read_gettext_status=1
+	return 1
+}
 
 # This must happen in a function to enforce an empty argument list.
 read_functions () {
-	local I
-	for I in "${LOCAL_EPREFIX_PORTAGE_EXEC}/etc/init.d/functions.sh" \
-		"${LOCAL_EPREFIX_PORTAGE_EXEC}/sbin/functions.sh"
+	local i
+	read_gettext
+	for i in "${local_eprefix_portage_exec}/etc/init.d/functions.sh" \
+		"${local_eprefix_portage_exec}/sbin/functions.sh"
 	do
-		test -r "${I}" || continue
-		. "${I}"
+		test -r "${i}" || continue
+		. "${i}"
 		return
 	done
-	printf "%s: %s" "${0##*/}" "cannot read functions.sh" >&2
+	printf '%s: %s' "${0##*/}" "`gettext 'cannot read functions.sh'`" >&2
 	exit 2
 }
 
 die () {
 	eerror "${*}"
-	EXITCODE=2
-	exit "${EXITCODE}"
+	exitcode=2
+	exit "${exitcode}"
 }
 
-LOCAL_PORTDIR=''
+per_line () {
+	local i
+	while IFS='
+' read i
+	do
+		"${@}" "${i}"
+	done
+}
+
+local_portdir=''
 GetPortdir () {
-	[ -n "${LOCAL_PORTDIR}" ] && return
-	LOCAL_PORTDIR="`update-eix --print PORTDIR`"
+	[ -n "${local_portdir}" ] && return
+	local_portdir="`update-eix --print PORTDIR`"
 }
 
-VERBOSE=true
+verbose=true
 
 RunCommand () {
-	local RET
-	if ${VERBOSE}
+	local ret c
+	if ${verbose}
 	then
 		einfo "${1}"
 		shift
@@ -52,9 +91,10 @@ RunCommand () {
 	ebegin "${1}"
 	shift
 	"${@}" >/dev/null
-	RET=${?}
-	eend ${RET} "Problems running ${@}"
-	return ${RET}
+	ret=${?}
+	c="${*}"
+	eend ${ret} "`eval_gettext 'Problems running ${c}'`"
+	return ${ret}
 }
 
 ( eval '[ "$(( 0 + 1 ))" = 1 ]' ) >/dev/null 2>&1 && eval '
@@ -113,17 +153,17 @@ Push () {
 }
 
 AddUpdateArgs () {
-	Push UPDATE_EIX_ARGS "${@}"
+	Push update_eix_args "${@}"
 }
 
 AddUpdateQuoting () {
-	local K
-	K="${1}"
+	local k
+	k="${1}"
 	shift
-	Replace -g K '?' '\?'
-	Replace -g K '*' '\*'
-	Replace -g K '[' '\['
-	AddUpdateArgs "${K}" "${@}"
+	Replace -g k '?' '\?'
+	Replace -g k '*' '\*'
+	Replace -g k '[' '\['
+	AddUpdateArgs "${k}" "${@}"
 }
 
 AddMethod () {
@@ -132,48 +172,48 @@ AddMethod () {
 }
 
 AddOverlays () {
-	local J
-	for J
+	local j
+	for j
 	do
-		AddUpdateArgs '-a' "${J}"
+		AddUpdateArgs '-a' "${j}"
 	done
 }
 
 AddExcludes () {
-	local J
-	for J
+	local j
+	for j
 	do
 		AddUpdateArgs '-x'
-		AddUpdateQuoting "${J}"
+		AddUpdateQuoting "${j}"
 	done
 }
 
 ClearUpdateEixArgs () {
-	UPDATE_EIX_ARGS=''
+	update_eix_args=''
 }
 
 CallUpdateEix () {
-	eval "set -- ${UPDATE_EIX_ARGS}"
-	RunCommand "Calling update-eix" update-eix "${@}" || \
-		die "update-eix failed"
+	eval "set -- ${update_eix_args}"
+	RunCommand "`gettext 'Calling update-eix'`" update-eix "${@}" || \
+		die "`gettext 'update-eix failed'`"
 }
 
 AddLocalMethods () {
-	local I L
+	local i l
 	GetPortdir
-	AddMethod "${LOCAL_PORTDIR}" "eix"
-	for I in `portageq portdir_overlay` ${ADD_OVERLAY}
+	AddMethod "${local_portdir}" "eix"
+	for i in `portageq portdir_overlay` ${ADD_OVERLAY}
 	do
-		L="${I}"
-		Replace -g L '\' '\\'
-		Replace -g L ':' '\:'
-		AddMethod "${I}" "eix::${L}"
+		l="${i}"
+		Replace -g l '\' '\\'
+		Replace -g l ':' '\:'
+		AddMethod "${i}" "eix::${l}"
 	done
 }
 
 # Remove optional trailing newline from all variables (arguments).
 # This is necessary as some shells won't take ${Var%"[newline]"}
-NEWLINE_STRING='
+newline_string='
 '
 Chomp () {
 	local ChompA_ ChompB_ ChompC_
@@ -181,26 +221,27 @@ Chomp () {
 	do
 		eval "ChompB_=\"\${${ChompA_}}\""
 		ChompC_="${ChompB_%?}"
-		[ "${ChompC_}${NEWLINE_STRING}" = "${ChompB_}" ] &&
+		[ "${ChompC_}${newline_string}" = "${ChompB_}" ] &&
 			eval "${ChompA_}=\"\${ChompC_}\""
 	done
 	true
 }
 
 # Consider variables (arguments) as paths and normalize them.
-# If HAVE_READLINK=true (if possible), use readlink to resolve to "true"
+# If have_readlink=true (if possible), use readlink to resolve to "true"
 # pathnames.
 # Return with 1 if at least one variable is empty.
-# Set RELATIVE to a list of all variables which are relative paths
-# (the first token in RELATIVE will be a space if the list is not empty).
+# Set relative to a list of all variables which are relative paths
+# (the first token in relative will be a space if the list is not empty).
 
-HAVE_READLINK=false
-command -v readlink >/dev/null 2>&1 && HAVE_READLINK=true
+have_readlink=false
+command -v readlink >/dev/null 2>&1 && have_readlink=true
 NormalizeNames () {
 	local NormA_ NormB_ NormC_ NormD_
 	NormD_=0
-	RELATIVE=''
-	for NormC_; do
+	relative=''
+	for NormC_
+	do
 		eval "NormA_=\"\${${NormC_}}\""
 		if [ -z "${NormA_}" ]; then
 			NormD_=1
@@ -208,9 +249,9 @@ NormalizeNames () {
 		fi
 		case "${NormA_}" in
 			/*) :;;
-			*) RELATIVE="${RELATIVE} ${NormC_}";;
+			*) relative="${relative} ${NormC_}";;
 		esac
-		if ${HAVE_READLINK}; then
+		if ${have_readlink}; then
 			# Append A to avoid loss of trailing \n in `...`
 			NormB_=`readlink -f -- "${NormA_}" ; printf A` && \
 				NormB_="${NormB_%A}" && Chomp NormB_ && \
diff --git a/src/update-eix-remote.in b/src/update-eix-remote.in
--- a/src/update-eix-remote.in
+++ b/src/update-eix-remote.in
@@ -11,19 +11,23 @@
 . ./functions-eix.sh.in
 read_functions
 
-[ -n "${OVERLAYPARENT}" ] || OVERLAYPARENT="/usr/portage/local"
-EIXCACHESNAME="eix-caches.tbz2"
+: ${OVERLAYPARENT:=/usr/portage/local}
+eixcachesname='eix-caches.tbz2'
 
 Sanitize () {
-	READLINK='' NormalizeNames OVERLAYPARENT \
-		|| die '$OVERLAYPARENT must not be empty'
-	[ -z "${RELATIVE}" ] || die '$OVERLAYPARENT must start with /'
+	have_readlink=false NormalizeNames OVERLAYPARENT \
+		|| die "`gettext '$OVERLAYPARENT must not be empty'`"
+	[ -z "${relative}" ] || \
+		die "`gettext '$OVERLAYPARENT must start with /'`"
 }
 Sanitize
 
 Usage () {
-	printf "%s\n" "Usage: ${0##*/} [options] command [FILE]
-Handle some remote updates for @PACKAGE_STRING@
+	local n p
+	n="${0##*/}"
+	p='@PACKAGE_STRING@'
+	eval_gettext 'Usage: ${n} [options] command [FILE]
+Handle some remote updates for ${p}
 The following commands are provided:
 
 update: Fetch the eix-caches of some layman overlays into a temporary file
@@ -38,181 +42,192 @@ remove: Remove all temporarily added virtual overlays from the eix database;
         but faster (without actual updating where possible).
 
 It is strongly recommended to use the update/fetch commands with very limited
-permissions. Permissions are dropped when run as root or with the \"-u nobody\"
-option. Don't use \"-u root\".
+permissions. Permissions are dropped when run as root or with the "-u nobody"
+option. Do not use "-u root".
 
-For \"update\" and \"add\" all corresponding local overlay paths are excluded
+For "update" and "add" all corresponding local overlay paths are excluded
 from the current database to avoid confusion. The local paths are determined
 by prefixing the path
 	${OVERLAYPARENT}
-You can modify this value by setting the environment variable \$OVERLAYPARENT
-or with the -o option. If you do not want this feature, set \$OVERLAYPARENT
+You can modify this value by setting the environment variable OVERLAYPARENT
+or with the -o option. If you do not want this feature, set OVERLAYPARENT
 to some path not containing any overlays.
 
 Options:
 	-O x    Extract from the cache files within FILE only overlay Nr. x,
 	        i.e. use cache method eix*:...:x for reading these cache files.
 	        Default for x is * (which means all overlays in each files)
-	        See \"man eix\" for details on cache method eix*.
-	-u USER Call wget as USER. Defaults to \"nobody\" if called as root.
-	-o PATH Use PATH as \$OVERLAYPARENT
+	        See "man eix" for details on cache method eix*.
+	-u USER Call wget as USER. Defaults to "nobody" if called as root.
+	-o PATH Use PATH as OVERLAYPARENT
 	-v      Verbose (default)
-	-q      Quiet"
-	EXITCODE=${1:-1}
-	exit ${EXITCODE}
+	-q      Quiet'
+	echo
+	exitcode=${1:-1}
+	exit ${exitcode}
 }
 
-OVERLAYNR='*'
-VERBOSE=true
-FETCHUSER=''
+overlaynr='*'
+verbose=true
+fetchuser=''
 OPTIND=1
-while getopts 'O:vqu:o:?hH' OPTION
+while getopts 'O:vqu:o:?hH' opt
 do
-	case "${OPTION}" in
-		O) OVERLAYNR="${OPTARG}";;
-		v) VERBOSE=true;;
-		q) VERBOSE=false;;
-		u) FETCHUSER="${OPTARG}";;
+	case "${opt}" in
+		O) overlaynr="${OPTARG}";;
+		v) verbose=true;;
+		q) verbose=false;;
+		u) fetchuser="${OPTARG}";;
 		o) OVERLAYPARENT="${OPTARG}"; Sanitize;;
 		*) Usage 0;;
 	esac
 done
 [ ${OPTIND} -gt 1 ] && shift "`expr ${OPTIND} - 1`"
 
-NEED_ARG=false
-FILENAME=''
+need_arg=false
+filename=''
 GetFilename () {
 	[ ${#} -gt 1 ] && Usage
 	if [ ${#} -lt 1 ]
 	then
-		${NEED_ARG} && die "Filename argument is mandatory"
+		${need_arg} && \
+			die "`gettext 'Filename argument is mandatory'`"
 		return
 	fi
-	FILENAME="${1}"
-	[ -n "${FILENAME}" ] || die "Filename argument must be nonempty"
-	case "${FILENAME}" in
+	filename="${1}"
+	[ -n "${filename}" ] || \
+		die "`gettext 'Filename argument must be nonempty'`"
+	case "${filename}" in
 		/*|'~'*) :;;
-		*) FILENAME="`pwd`/${FILENAME}";;
+		*) filename="`pwd`/${filename}";;
 	esac
 }
 
 CalcSuCmd () {
-	local SHEXEC
-	if [ -z "${FETCHUSER}" ]
+	local shexec a
+	if [ -z "${fetchuser}" ]
 	then
 		[ -n "${UID}" ] || UID="`id -u`"
 		if [ "${UID}" -ne 0 ]; then
-			Push -c SUCMD "${@}"
+			Push -c sucmd "${@}"
 			return
 		fi
-		FETCHUSER=nobody
+		fetchuser=nobody
 	fi
-	SHEXEC="${SHELL}"
-	if [ -z "${SHEXEC}" ] || ! test -x "${SHELL}"
+	shexec="${SHELL}"
+	if [ -z "${shexec}" ] || ! test -x "${SHELL}"
 	then
-		SHEXEC="`command -v sh`" && test -x "${SHEXEC}" || \
-			SHEXEC='/bin/sh'
+		shexec="`command -v sh`" && test -x "${shexec}" || \
+			shexec='/bin/sh'
 	fi
-	SUCMD=`command -v "${1}"` && test -x "${SUCMD}" || \
-		die "${1} cannot be found in $PATH"
-	Push -c SUCMD "${SUCMD}"
+	a="${1}"
+	sucmd=`command -v "${a}"` && test -x "${sucmd}" || \
+		die "`eval_gettext '${a} cannot be found in PATH'`"
+	Push -c sucmd "${sucmd}"
 	shift
-	Push SUCMD "${@}"
-	Push -c SUCMD '/bin/su' '-s' "${SHEXEC}" '-c' \
-		"eval exec ${SUCMD}" "${FETCHUSER}"
+	Push sucmd "${@}"
+	Push -c sucmd '/bin/su' '-s' "${shexec}" '-c' \
+		"eval exec ${sucmd}" "${fetchuser}"
 }
 
 CdDir () {
-	cd -- "${1}" >/dev/null || die "cannot cd to ${1}"
+	local a
+	cd -- "${1}" >/dev/null && return
+	a="${1}"
+	die "`eval_gettext 'cannot cd to ${a}'`"
 }
 
-TMPDIR=''
-EXITCODE=0
+tmpdir=''
+exitcode=0
 Cleanup () {
 	cd / >/dev/null
-	if [ -n "${TMPDIR}" ]; then
-		test -d "${TMPDIR}" && rm -rf -- "${TMPDIR}"
+	if [ -n "${tmpdir}" ]
+	then
+		test -d "${tmpdir}" && rm -rf -- "${tmpdir}"
 	fi
-	TMPDIR=''
+	tmpdir=''
 	trap - EXIT HUP INT TERM
-	exit "${EXITCODE}"
+	exit "${exitcode}"
 }
 MakeTempDir () {
-	local COUNT
-	[ -n "${TMPDIR}" ] && return
+	local count
+	[ -n "${tmpdir}" ] && return
 	if command -v mktemp >/dev/null 2>&1
 	then
-		TMPDIR=`mktemp -d "/tmp/${0##*/}.XXXXXX"` || \
-			die "cannot create temporary directory"
+		tmpdir=`mktemp -d "/tmp/${0##*/}.XXXXXXXX"` || \
+			die "`gettext 'cannot create temporary directory'`"
 	else
-		COUNT=0
+		count=0
 		while true; do
-			[ ${COUNT} -eq 9999 ] && \
-				die "found no free temp after 10000 attempts"
-			COUNT="`expr ${COUNT} + 1`"
-			TMPDIR="/tmp/${0##*/}.$$.${RANDOM}.${RANDOM}.${RANDOM}"
-			test -e "${TMPDIR}" && continue
-			mkdir "${TMPDIR}" || die "cannot create ${TMPDIR}"
+			[ ${count} -eq 9999 ] && die "`gettext \
+				'found no free tempname after 10000 attempts'`"
+			count="`expr ${count} + 1`"
+			tmpdir="/tmp/${0##*/}.$$.${RANDOM}.${count}.${RANDOM}"
+			test -e "${tmpdir}" && continue
+			mkdir "${tmpdir}" || die "`eval_gettext \
+				'cannot create temporary dir ${tmpdir}'`"
 			break
 		done
 	fi
 	trap Cleanup EXIT HUP INT TERM
-	chmod -- 755 "${TMPDIR}"
-	[ -z "${1}" ] || CdDir "${TMPDIR}"
+	chmod -- 755 "${tmpdir}"
+	[ -z "${1}" ] || CdDir "${tmpdir}"
 }
 
-TMPSUB=''
+tmpsub=''
 MakeTempSub () {
-	if [ -z "${TMPSUB}" ]
+	if [ -z "${tmpsub}" ]
 	then
 		MakeTempDir
-		TMPSUB="${TMPDIR}/1"
-		( umask 000; mkdir -- "${TMPSUB}" )
+		tmpsub="${tmpdir}/1"
+		( umask 000; mkdir -- "${tmpsub}" )
 	fi
-	[ -z "${1}" ] || CdDir "${TMPSUB}"
+	[ -z "${1}" ] || CdDir "${tmpsub}"
 }
 
-TMPFILE=''
+tmpfile=''
 FetchTemp () {
-	local SOURCE
-	SOURCE="http://dev.gentooexperimental.org/eix_cache/${EIXCACHESNAME}"
+	local addr
+	addr="http://dev.gentooexperimental.org/eix_cache/${eixcachesname}"
 	MakeTempDir cd
-	TMPFILE="${TMPDIR}/${EIXCACHESNAME}"
-	( umask 000; : >"${TMPFILE}" )
-	CalcSuCmd wget -c "${SOURCE}"
-	eval "set -- ${SUCMD}"
-	RunCommand "Fetching ${EIXCACHESNAME}" "${@}" || \
-		die "could not fetch ${SOURCE}"
+	tmpfile="${tmpdir}/${eixcachesname}"
+	( umask 000; : >"${tmpfile}" )
+	CalcSuCmd wget -c "${addr}"
+	eval "set -- ${sucmd}"
+	RunCommand "`eval_gettext 'Fetching ${eixcachesname}'`" "${@}" || \
+		die "`eval_gettext 'could not fetch ${addr}'`"
 }
 
 AddArchive () {
-	local I N NAME VIRTUAL OVERLAYARG
-	RunCommand "Unpacking data" tar xjf "${1}" || die "cannot unpack ${1}"
+	local i n name virtual overlayarg
+	i="${1}"
+	RunCommand "Unpacking data" tar xjf "${i}" || \
+		die "`eval_gettext 'cannot unpack ${i}'`"
 	ClearUpdateEixArgs
 	AddLocalMethods
-	for I in *
+	for i in *
 	do
-		NAME="${I}"
-		Replace -g NAME ':' '_' || mv -- "${I}" "${NAME}"
+		name="${i}"
+		Replace -g name ':' '_' || mv -- "${i}" "${name}"
 	done
-	if [ -n "${OVERLAYNR}" ]
+	if [ -n "${overlaynr}" ]
 	then
-		OVERLAYARG=":${OVERLAYNR}"
+		overlayarg=":${overlaynr}"
 	else
-		OVERLAYARG=''
+		overlayarg=''
 	fi
-	for I in *
+	for i in *
 	do
-		NAME="${I%.eix}"
-		NAME="${NAME#_usr_portage_local_}"
-		Replace -g NAME '_' '/'
-		VIRTUAL="(${NAME})"
-		N="${2}/${I}"
-		Replace -g N '\' '\\'
-		Replace -g N ':' '\:'
-		AddMethod "${VIRTUAL}" "eix*:${N}${OVERLAYARG}"
-		AddOverlays "${VIRTUAL}"
-		AddExcludes "${OVERLAYPARENT}/${NAME}"
+		name="${i%.eix}"
+		name="${name#_usr_portage_local_}"
+		Replace -g name '_' '/'
+		virtual="(${name})"
+		n="${2}/${i}"
+		Replace -g n '\' '\\'
+		Replace -g n ':' '\:'
+		AddMethod "${virtual}" "eix*:${n}${overlayarg}"
+		AddOverlays "${virtual}"
+		AddExcludes "${OVERLAYPARENT}/${name}"
 	done
 	export KEEP_VIRTUALS=true
 	CallUpdateEix
@@ -221,25 +236,26 @@ AddArchive () {
 FetchCopy () {
 	GetFilename "${@}"
 	FetchTemp
-	[ -z "${FILENAME}" ] && return
+	[ -z "${filename}" ] && return
 	(
 		[ "${UID}" -eq 0 ] && umask 002
-		cp --preserve=timestamps -- "${TMPFILE}" "${FILENAME}"
+		cp --preserve=timestamps -- "${tmpfile}" "${filename}"
 	)
-	[ "${UID}" -eq 0 ] && chown -- portage:portage "${FILENAME}"
+	[ "${UID}" -eq 0 ] && chown -- portage:portage "${filename}"
 }
 
 Fetch () {
-	NEED_ARG=true
+	need_arg=true
 	FetchCopy "${@}"
 }
 
 Add () {
-	NEED_ARG=true
+	need_arg=true
 	GetFilename "${@}"
-	test -r "${FILENAME}" || die "cannot read ${FILENAME}"
+	test -r "${filename}" || \
+		die "`eval_gettext 'cannot read ${filename}'`"
 	MakeTempDir cd
-	AddArchive "${FILENAME}" "${TMPDIR}"
+	AddArchive "${filename}" "${tmpdir}"
 }
 
 Remove () {
@@ -252,15 +268,15 @@ Remove () {
 Update () {
 	FetchCopy "${@}"
 	MakeTempSub cd
-	AddArchive "${TMPFILE}" "${TMPSUB}"
+	AddArchive "${tmpfile}" "${tmpsub}"
 }
 
-MAIN_COMMAND="${1}"
+main_command="${1}"
 [ ${#} -gt 0 ] && shift
 
 [ -n "${UID}" ] || UID="`id -u`"
 
-case "${MAIN_COMMAND}" in
+case "${main_command}" in
 	update|both)        Update "${@}";;
 	fetch*|get|wget)    Fetch "${@}";;
 	add*)               Add "${@}";;
