Avoid using sed: use POSIX shell's pattern matching instead.
git-svn-id: https://svn.gentooexperimental.org/eix/trunk@528 3c3e6e0f-8f03-0410-a2c1-9066eb21f691

diff --git a/src/update-eix-functions.sh.in b/src/update-eix-functions.sh.in
--- a/src/update-eix-functions.sh.in
+++ b/src/update-eix-functions.sh.in
@@ -3,7 +3,7 @@
 # terms of the GNU General Public License v2.
 #
 # Author and Copyright (c):
-#   Martin Väth <vaeth@mathematik.uni-wuerzburg.de>
+#   Martin V\"ath <vaeth@mathematik.uni-wuerzburg.de>
 #
 # This file must be "source"d by POSIX scripts.
 #
@@ -51,29 +51,51 @@ RunCommand () {
 	return ${RET}
 }
 
-SedVar() {
-	local V_="${1}" A_
-	shift
-	eval "A_=\"\${${V_}}\""
-	A_="$(echo "X${A_}X" | sed -e '1s/^X//' -e '$s/X$//' "${@}" \
-		-e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/")"
-	eval "${V_}=${A_}"
+# Usage: Replace [-g] VAR Search Replace
+# Search and Replace will be evaluated between " ", so quote correspondingly!
+# Option -g means: Replace all occurrences
+# Exit status is the number of replacements (or 127 if there are more)
+Replace() {
+	local ReplaceA_='' ReplaceB_ ReplaceC_=''
+	case "${1}" in
+		-*) ReplaceC_=0; shift;;
+	esac
+	eval "while {
+		ReplaceB_=\"\${${1}%%\"${2}\"*}\"
+		[ \"\${ReplaceB_}\" != \"\${${1}}\" ]
+	}
+	do
+		ReplaceA_=\"\${ReplaceA_}\${ReplaceB_}${3}\"
+		${1}=\"\${${1}#*\"${2}\"}\"
+		if [ -z \"\${ReplaceC_}\" ]; then
+			${1}=\"\${ReplaceA_}\${${1}}\"
+			return 1
+		fi
+		[ \${ReplaceC_} -ge 127 ] || \
+			ReplaceC_=\$(( \${ReplaceC_} + 1 ))
+	done
+	${1}=\"\${ReplaceA_}\${${1}}\""
+	return ${ReplaceC_}
 }
 
+# Usage: Push [-c] VAR Args
+# Append all Args to VAR, quoted such that
+#    eval "${VAR}" is 'safe' and groups Args correctly.
+# With option -c, VAR is cleaned in advance.
 Push() {
-	local A_='' S_='' V_="${1}" I_
-	shift
-	case "${V_}" in
-		-*) V_="${1}"; shift; eval "${V_}=''";;
+	case "${1}" in
+		-*) shift; eval "${1}=''";;
 	esac
-	for I_; do
-		A_="${A_}${S_}$(echo "X${I_}X" | \
-			sed -e "s/'/'\\\\''/g" -e "1s/^X/'/" -e "\$s/X\$/'/")"
-		S_=' '
-	done
-	[ -z "${S_}" ] && return
-	eval "[ -z \"\${${V_}}\" ]" && S_=''
-	eval "${V_}=\"\${${V_}}\${S_}\${A_}\""
+	local PushA_="${1}" PushB_
+	shift
+	eval "for PushB_; do
+		Replace -g PushB_ \"'\" \"'\\\\\\\\''\"
+		if [ -z \"\${${PushA_}}\" ]; then
+			${PushA_}=\"'\${PushB_}'\"
+		else
+			${PushA_}=\"\${${PushA_}} '\${PushB_}'\"
+		fi
+	done"
 }
 
 AddUpdateArgs() {
@@ -83,7 +105,9 @@ AddUpdateArgs() {
 AddUpdateQuoting() {
 	local K="$1"
 	shift
-	SedVar K -e 's/\([?*[]\)/\\\1/g'
+	Replace -g K '?' '\\?'
+	Replace -g K '*' '\\*'
+	Replace -g K '[' '\\['
 	AddUpdateArgs "${K}" "${@}"
 }
 
@@ -128,7 +152,8 @@ AddLocalMethods() {
 }
 
 # Consider variables (arguments) as paths and normalize them.
-# If READLINK=readlink (default), resolve even to "true" pathnames.
+# If HAVE_READLINK=true (if possible), use readlink to resolve to "true"
+# pathnames.
 # Return with 1 if at least one variable is empty.
 # Set RELATIVE to a list of all variables which are relative paths
 # (the first token in RELATIVE will be a space if the list is not empty).
@@ -136,26 +161,33 @@ AddLocalMethods() {
 HAVE_READLINK=false
 command -v readlink >/dev/null 2>&1 && HAVE_READLINK=true
 NormalizeNames () {
-	local T_ N_ I_ S_=0
+	local NormA_ NormB_ NormC_ NormD_=0
 	RELATIVE=''
-	for I_; do
-		eval "T_=\"\${${I_}}\""
-		if [ -z "${T_}" ]; then
-			S_=1
+	for NormC_; do
+		eval "NormA_=\"\${${NormC_}}\""
+		if [ -z "${NormA_}" ]; then
+			NormD_=1
 			continue
 		fi
-		case "${T_}" in
+		case "${NormA_}" in
 			/*) :;;
-			*) RELATIVE="${RELATIVE} ${I_}";;
+			*) RELATIVE="${RELATIVE} ${NormC_}";;
 		esac
 		if ${HAVE_READLINK}; then
-			N_="$(readlink -f -- "${T_}")" && [ -n "${N_}" ] && \
-				T_="${N_}"
+			# Append A to avoid loss of trailing \n in $(...)
+			NormB_="$(readlink -f -- "${NormA_}" && echo -n A)" &&
+				NormB="${NormB%A}" && NormB="${NormB%"
+"}" &&
+				[ -n "${NormB_}" ] && \
+					NormA_="${NormB_}"
 		fi
-		eval "${I_}=\"\${T_}\""
-		SedVar "${I_}" -e 's://*:/:g'
-		eval "[ \"\${${I_}}\" = '/' ] || ${I_}=\"\${${I_}%/}\""
+		eval "${NormC_}=\"\${NormA_}\""
+		while ! Replace -g "${NormC_}" '//' '/'; do
+			:
+		done
+		eval "[ \"\${${NormC_}}\" = '/' ] || \
+			${NormC_}=\"\${${NormC_}%/}\""
 	done
-	return ${S_}
+	return ${NormD_}
 }
 
